In [1]:
import os
import re

import pandas as pd
import numpy as np
import geopandas as gpd

In [2]:
g_drive = 'G:/My Drive/Work/ADB/SAR/combined_datasets'
local = 'D:/Work/ADB/SAR/datasets'

## Yield Data

In [27]:
poly = gpd.read_file('D:/Work/ADB/SAR/gadm41_VNM_1.json')
poly['VARNAME_1'] = poly['VARNAME_1'].apply(lambda x: re.sub(r"(\w)([A-Z])", r"\1 \2",x ))
poly['VARNAME_1'] = poly['VARNAME_1'].str.replace('-', ' - ')
poly = poly[['VARNAME_1']]
poly = poly.rename({'VARNAME_1': 'Province'}, axis=1)
poly

             Province
0            An Giang
1   Ba Ria - Vung Tau
2           Bac Giang
3             Bac Kan
4            Bac Lieu
..                ...
58           Tra Vinh
59        Tuyen Quang
60          Vinh Long
61          Vinh Phuc
62            Yen Bai

[63 rows x 1 columns]

In [28]:
provinces = poly['Province'].to_list()

In [32]:
df_total = pd.read_excel(os.path.join(local, 'Total paddy yield.xlsm'))
# df_total = df_total.replace(0, np.nan)
df_total

      Province  2018  2019  2020  2021  2022
0       Ha Noi  57.1  56.5  58.8  60.7  60.1
1    Vinh Phuc  58.4  57.9  58.1  59.8  53.1
2     Bac Ninh  61.8  61.4  63.7  64.9  65.2
3   Quang Ninh  50.8  50.6  51.6  51.9  51.9
4    Hai Duong  60.4  59.4  60.6  62.9  63.2
..         ...   ...   ...   ...   ...   ...
58     Can Tho  60.1  60.7  62.5  63.6  63.2
59   Hau Giang  64.0  64.2  65.3  67.4  66.6
60   Soc Trang  60.6  61.0  58.8  62.8  61.4
61    Bac Lieu  60.3  61.0  62.4  64.2  63.4
62      Ca Mau  45.2  45.5  39.8  45.8  49.0

[63 rows x 6 columns]

In [36]:
paths = ['Total paddy yield.xlsm', 'Spring paddy yield.xlsm',
         'Autumn paddy yield.xlsm', 'Winter paddy yield.xlsm']

for p in paths:
    df = pd.read_excel(os.path.join(local, p))
    df = df.replace(0, np.nan)
    df['Province'] = df['Province'].str.replace('  ', ' ')
    df.to_csv(os.path.join(local, p).replace('xlsm', 'csv'), index=False)

In [38]:
df_a = pd.read_csv(os.path.join(local, 'Autumn paddy yield.csv'))
df_a = pd.merge(poly, df_a, on=['Province'], how='left')
df_a

             Province  2018  2019  2020  2021  Prel. 2022
0            An Giang  56.7  57.8  58.3  60.3        60.5
1   Ba Ria - Vung Tau  49.5  51.6  52.0  54.3        58.3
2           Bac Giang   NaN   NaN   NaN   NaN         NaN
3             Bac Kan   NaN   NaN   NaN   NaN         NaN
4            Bac Lieu  58.0  58.7  58.2  59.3        58.6
..                ...   ...   ...   ...   ...         ...
58           Tra Vinh  52.5  51.8  50.3  51.4        47.6
59        Tuyen Quang   NaN   NaN   NaN   NaN         NaN
60          Vinh Long  56.5  56.1  57.3  55.4        53.8
61          Vinh Phuc   NaN   NaN   NaN   NaN         NaN
62            Yen Bai   NaN   NaN   NaN   NaN         NaN

[63 rows x 6 columns]

In [39]:
df_a.to_csv(os.path.join(local, 'Autumn paddy yield.csv'), index=False)

## Production Data

In [40]:
paths = ['Total paddy production.xlsx', 'Spring paddy production.xlsx',
         'Autumn paddy production.xlsx', 'Winter paddy production.xlsx']

for p in paths:
    df = pd.read_excel(os.path.join(local, p))
    df = df.replace(0, np.nan)
    df['Province'] = df['Province'].str.replace('  ', ' ')
    df.to_csv(os.path.join(local, p).replace('xlsx', 'csv'), index=False)

In [42]:
df_a = pd.read_csv(os.path.join(local, 'Autumn paddy production.csv'))
df_a = pd.merge(poly, df_a, on=['Province'], how='left')
df_a

             Province    2018    2019    2020    2021    2022
0            An Giang  2199.1  2241.0  2348.6  2350.8  2242.8
1   Ba Ria - Vung Tau    42.6    42.3    42.6    44.4    48.2
2           Bac Giang     NaN     NaN     NaN     NaN     NaN
3             Bac Kan     NaN     NaN     NaN     NaN     NaN
4            Bac Lieu   596.7   605.6   585.4   609.5   580.9
..                ...     ...     ...     ...     ...     ...
58           Tra Vinh   815.0   795.0   716.7   759.7   640.3
59        Tuyen Quang     NaN     NaN     NaN     NaN     NaN
60          Vinh Long   597.7   562.6   534.8   482.6   354.9
61          Vinh Phuc     NaN     NaN     NaN     NaN     NaN
62            Yen Bai     NaN     NaN     NaN     NaN     NaN

[63 rows x 6 columns]

In [5]:
df_a.to_csv(os.path.join(local, 'Autumn paddy production.csv'), index=False)

SyntaxError: invalid decimal literal (792992810.py, line 1)

## Leaf based

In [3]:
df = pd.read_csv(os.path.join(local, 'LEAF_NORTH.csv'), dtype={'lat': 'str',
                                                                'lon': 'str'})
coords = pd.read_csv('datasets/province_by_coords.csv', dtype={'lat': 'str',
                                                                'lon': 'str'})

In [4]:
df = pd.merge(df, coords, on=['lon', 'lat'], how='left')
df['year'] = df['Timestamp'].str[:4]
df = df.drop(['lat', 'lon', 'Timestamp'], axis=1)
df

          LAI_mean  NDVI_mean    Province  year
0          0.12890   0.068094     Ha Tinh  2017
1          0.03160   0.051050     Ha Tinh  2017
2          0.07153   0.073072     Ha Tinh  2017
3          0.12800   0.082849     Ha Tinh  2017
4          0.05440   0.058809     Ha Tinh  2017
...            ...        ...         ...   ...
80697802   0.74170   0.253189  Quang Ninh  2022
80697803   0.67600   0.245521  Quang Ninh  2022
80697804   0.37130   0.185990  Quang Ninh  2022
80697805   0.33180   0.177492  Quang Ninh  2022
80697806   0.43700   0.212762  Quang Ninh  2022

[80697807 rows x 4 columns]

In [5]:
gb = df.groupby(['Province', 'year']).agg({'LAI_mean': 'mean',
                                           'NDVI_mean': 'mean'}).reset_index()

# gb = df.groupby(['Province', 'year']).agg({'VV': 'mean',
#                                            'VH': 'mean',
#                                            'VV/VH': 'mean'}).reset_index()

gb

      Province  year  LAI_mean  NDVI_mean
0    Bac Giang  2017  0.439976   0.116264
1    Bac Giang  2018  0.515554   0.149337
2    Bac Giang  2019  0.545825   0.147878
3    Bac Giang  2020      -inf   0.136536
4    Bac Giang  2021       inf   0.138898
..         ...   ...       ...        ...
133    Yen Bai  2018  0.562835   0.146008
134    Yen Bai  2019  0.644082   0.159010
135    Yen Bai  2020  0.514839   0.135078
136    Yen Bai  2021  0.527350   0.157629
137    Yen Bai  2022  0.438442   0.135865

[138 rows x 4 columns]

In [6]:
gb.to_csv('datasets/aggregated/LEAF_GB_NORTH.csv', index=False)