In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
df = pd.read_csv("D:\Work\ADB\SAR\datasets\SVN_pmdeviation_maps.csv")
df

<>:1: SyntaxWarning: invalid escape sequence '\W'
<>:1: SyntaxWarning: invalid escape sequence '\W'
C:\Users\sonle\AppData\Local\Temp\ipykernel_17372\4011149418.py:1: SyntaxWarning: invalid escape sequence '\W'
  df = pd.read_csv("D:\Work\ADB\SAR\datasets\SVN_pmdeviation_maps.csv")

,id,lon,lat,pm25_adev_2017_SepDec,pm25_mxdev_2017_SepDec,pm25_adev_2018_JanFeb,pm25_mxdev_2018_JanFeb,pm25_adev_2019_MarApr,pm25_mxdev_2019_MarApr,pm25_adev_2019_Sep,...,pm25_adev_2020_Aug,pm25_mxdev_2020_Aug,pm25_adev_2020_Jan,pm25_mxdev_2020_Jan,pm25_adev_2020_Jul,pm25_mxdev_2020_Jul,pm25_adev_2020_NovDec,pm25_mxdev_2020_NovDec,pm25_adev_2021_Aug,pm25_mxdev_2021_Aug
0,1,104.54997,10.455043,0.065542,0.000000,0.467612,0.369086,0.142744,0.004637,0.517558,...,0.0,0.0,0.000000,0.070406,0.0,0.000000,0.0,0.0,0.0,0.188444
1,2,104.55087,10.292447,0.046584,0.000000,0.467612,0.369086,0.142744,0.004637,0.517558,...,0.0,0.0,0.000000,0.070406,0.0,0.000000,0.0,0.0,0.0,0.188444
2,3,104.55087,10.297837,0.046584,0.000000,0.467612,0.369086,0.142744,0.004637,0.517558,...,0.0,0.0,0.000000,0.070406,0.0,0.000000,0.0,0.0,0.0,0.188444
3,4,104.55087,10.309515,0.046584,0.000000,0.467612,0.369086,0.142744,0.004637,0.517558,...,0.0,0.0,0.000000,0.070406,0.0,0.000000,0.0,0.0,0.0,0.188444
4,5,104.55087,10.406533,0.046584,0.000000,0.467612,0.369086,0.142744,0.004637,0.517558,...,0.0,0.0,0.000000,0.070406,0.0,0.000000,0.0,0.0,0.0,0.188444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1600342,1601162,106.99968,11.932771,0.215933,0.086999,0.638426,0.910993,0.629104,2.443164,0.000000,...,0.0,0.0,0.039611,0.000000,0.0,0.368181,0.0,0.0,0.0,0.000000
1600343,1601163,106.99968,11.933669,0.215933,0.086999,0.638426,0.910993,0.629104,2.443164,0.000000,...,0.0,0.0,0.039611,0.000000,0.0,0.368181,0.0,0.0,0.0,0.000000
1600344,1601164,106.99968,11.935466,0.215933,0.086999,0.638426,0.910993,0.629104,2.443164,0.000000,...,0.0,0.0,0.039611,0.000000,0.0,0.368181,0.0,0.0,0.0,0.000000
1600345,1601165,106.99968,11.936364,0.215933,0.086999,0.638426,0.910993,0.629104,2.443164,0.000000,...,0.0,0.0,0.039611,0.000000,0.0,0.368181,0.0,0.0,0.0,0.000000
1600346,1601166,106.99968,11.937263,0.215933,0.086999,0.638426,0.910993,0.629104,2.443164,0.000000,...,0.0,0.0,0.039611,0.000000,0.0,0.368181,0.0,0.0,0.0,0.000000

In [13]:
import dask.dataframe as dd
import geopandas as gpd
from shapely.geometry import Point


from dask.distributed import LocalCluster
cluster = LocalCluster(n_workers=6,
                       memory_limit="1.5GB")          # Fully-featured local Dask cluster
client = cluster.get_client()

c:\Users\sonle\anaconda3\envs\geospatial\Lib\site-packages\distributed\node.py:182: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 58321 instead
  warnings.warn(

In [14]:
gdf = gpd.read_file(r"D:\Work\ADB\SAR\shapefiles\gadm41_VNM_2.json")
gdf = gdf[['NAME_1', 'NAME_2', 'geometry']]
gdf['NAME_1'] = gdf['NAME_1'].str.replace(r'(?<!^)([A-Z])', r' \1', regex=True)
gdf['NAME_2'] = gdf['NAME_2'].str.replace(r'(?<!^)([A-Z])', r' \1', regex=True)
gdf = gdf.rename({'NAME_1': 'Province',
                  'NAME_2': 'District'}, axis=1)
gdf = gdf.to_crs(epsg=4326)
gdf

     Province    District                                           geometry
0    An Giang      An Phú  MULTIPOLYGON (((105.15660 10.82870, 105.16010 ...
1    An Giang     ChâuĐốc  MULTIPOLYGON (((105.10500 10.63830, 105.08150 ...
2    An Giang    Châu Phú  MULTIPOLYGON (((105.18790 10.46030, 105.17980 ...
3    An Giang  Châu Thành  MULTIPOLYGON (((105.37090 10.36220, 105.36820 ...
4    An Giang     Chợ Mới  MULTIPOLYGON (((105.48720 10.53950, 105.48840 ...
..        ...         ...                                                ...
705   Yên Bái    Trấn Yên  MULTIPOLYGON (((104.89280 21.59120, 104.89630 ...
706   Yên Bái    Văn Chấn  MULTIPOLYGON (((104.87260 21.34890, 104.86840 ...
707   Yên Bái     Văn Yên  MULTIPOLYGON (((104.71710 21.73530, 104.71880 ...
708   Yên Bái     Yên Bái  MULTIPOLYGON (((104.87250 21.68120, 104.87380 ...
709   Yên Bái    Yên Bình  MULTIPOLYGON (((104.97870 21.65970, 104.97620 ...

[710 rows x 3 columns]

In [15]:
df = dd.read_csv(r"D:\Work\ADB\SAR\datasets\VN_SOUTH_VER2.csv")
df = df[['lon', 'lat']]
df = df.drop_duplicates(subset=['lon', 'lat'])
df = df.reset_index(drop=True)
df.columns

Index(['lon', 'lat'], dtype='object')

In [16]:
df.head()

2024-11-06 14:38:04,655 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 543e2a636a2c10ae9b9f8c9a21132065 initialized by task ('shuffle-transfer-543e2a636a2c10ae9b9f8c9a21132065', 16) executed on worker tcp://127.0.0.1:58365
2024-11-06 14:38:14,062 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 543e2a636a2c10ae9b9f8c9a21132065 deactivated due to stimulus 'task-finished-1730878694.0611258'
2024-11-06 14:38:23,373 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 0a84360989709d41a291ff55de44f727 initialized by task ('shuffle-transfer-0a84360989709d41a291ff55de44f727', 16) executed on worker tcp://127.0.0.1:58352
2024-11-06 14:38:41,744 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 0a84360989709d41a291ff55de44f727 deactivated due to stimulus 'task-finished-1730878721.7432723'

          lon       lat
0  104.929064  9.001568
1  104.976675  9.028518
2  104.895827  9.041094
3  104.877860  9.063552
4  104.888640  9.063552

In [17]:
def assign_municipalities(df, poly, col_name):
    localdf = df[['lon', 'lat']].copy(deep=True)
    try:
        local_gdf = gpd.GeoDataFrame(
            localdf, crs='epsg:4326',
            geometry=[Point(xy) for xy in zip(localdf['lon'], localdf['lat'])]
        )
        local_gdf = gpd.sjoin(
            local_gdf, poly, how='left', op='within')
        
        if col_name in local_gdf.columns:
            return local_gdf[col_name].reset_index(drop=True)
        else:
            raise ValueError(f"Column '{col_name}' not found in the joined GeoDataFrame.")
        
    except ValueError as ve:
        print(ve)
        series = pd.Series([np.nan] * len(localdf))
        return series

def create_bounding_box(df, center_lon_col, center_lat_col, side_length_m):
    
    side_length_deg = side_length_m /111000

    half_side = side_length_deg / 2

    # Calculate bounding box corners
    df['min_lon'] = df[center_lon_col] - half_side
    df['max_lon'] = df[center_lon_col] + half_side
    df['min_lat'] = df[center_lat_col] - half_side
    df['max_lat'] = df[center_lat_col] + half_side
    
    return df[['lon', 'lat', 'min_lon', 'min_lat', 'max_lon', 'max_lat']]

In [18]:
# df['Province'] = df.map_partitions(assign_municipalities, gdf, 'Province')
# df['District'] = df.map_partitions(assign_municipalities, gdf, 'District')

df_bbox = df.map_partitions(create_bounding_box, 'lon', 'lat', 100)

In [ ]:
df_bbox.head(2)

          lon       lat     min_lon   min_lat     max_lon   max_lat
0  104.929064  9.001568  104.928614  9.001118  104.929515  9.002019
1  104.976675  9.028518  104.976224  9.028067  104.977125  9.028968

In [19]:
# df.to_csv(r"D:\Work\ADB\SAR\datasets\VN_SOUTH_VER2_spatial.csv", index=False, single_file = True)
df_bbox.to_csv(r"D:\Work\ADB\SAR\datasets\VN_SOUTH_VER2_bbox.csv", index=False, single_file = True)

['D:\\Work\\ADB\\SAR\\datasets\\VN_SOUTH_VER2_bbox.csv']

In [2]:
from shapely.geometry import Polygon

df_bbox = dd.read_csv(r"D:\Work\ADB\SAR\datasets\VN_SOUTH_VER2_bbox.csv")
def create_polygon_from_bbox(row):
    # Extract bounding box coordinates
    # Define the four corners of the bounding box in the order needed for a Polygon
    return Polygon([(row['min_lon'], row['min_lat']), (row['min_lon'], row['max_lat']), (row['max_lon'], row['max_lat']), (row['max_lon'], row['min_lat']), (row['min_lon'], row['min_lat'])])

df_bbox['geometry'] = df_bbox.map_partitions(lambda df: df.apply(create_polygon_from_bbox, axis=1), meta=('polygon', 'object'))
df_bbox[['lon', 'lat', 'geometry']].to_csv(r"D:\Work\ADB\SAR\datasets\VN_SOUTH_VER2_bbox.csv", index=False, single_file = True)

# gdf = gpd.GeoDataFrame(df_bbox[['lon', 'lat']],
#                        crs='epsg:4326',
#                        geometry=df_bbox['polygon'])

['D:\\Work\\ADB\\SAR\\datasets\\VN_SOUTH_VER2_bbox.csv']

In [23]:
import pandas as pd
from shapely.geometry import Polygon
df = pd.read_csv(r"D:\Work\ADB\SAR\datasets\VN_SOUTH_VER2_bbox.csv")
def bbox_to_polygon(row):
    return Polygon([
        (row['min_lon'], row['min_lat']),
        (row['min_lon'], row['max_lat']),
        (row['max_lon'], row['max_lat']),
        (row['max_lon'], row['min_lat']),
        (row['min_lon'], row['min_lat'])  # Close the polygon
    ])

# Apply the function to create a 'geometry' column with polygons
df['geometry'] = df.apply(bbox_to_polygon, axis=1)

# Convert DataFrame to GeoDataFrame with CRS (Coordinate Reference System)
gdf = gpd.GeoDataFrame(df, geometry='geometry', crs="EPSG:4326")

# Drop the original bounding box columns if needed
gdf = gdf.drop(columns=['min_lon', 'min_lat', 'max_lon', 'max_lat'])

In [25]:
gdf.to_file(r"D:/Work/ADB/SAR/shapefiles/VN_SOUTH.json", driver='GeoJSON', index=False)