In [4]:
import os
import glob
import json
import sys
import time
import requests
from datetime import datetime

import pandas as pd
import numpy as np
import rasterio
import rasterstats
import rioxarray as rxr
import geopandas as gpd
from osgeo import gdal
from shapely.geometry import box
from tqdm.notebook import tqdm_notebook as tqdm

In [5]:
dir = os.getcwd()

In [6]:
# df = pd.read_csv(os.path.join(dir, 'datasets/South_VNM_3per_sampleID.csv'))
df = pd.read_csv(os.path.join(dir, 'datasets\South_sample_5x10000.csv'))
df

<>:2: SyntaxWarning: invalid escape sequence '\S'
<>:2: SyntaxWarning: invalid escape sequence '\S'
C:\Users\sonle\AppData\Local\Temp\ipykernel_36436\445749686.py:2: SyntaxWarning: invalid escape sequence '\S'
  df = pd.read_csv(os.path.join(dir, 'datasets\South_sample_5x10000.csv'))

,id,lon,lat,sample_1,sample_2,sample_3,sample_4,sample_5
0,518582,105.34409,9.759747,0,0,0,0,1
1,306736,105.16891,10.705672,0,0,0,0,1
2,515851,105.34139,9.483066,0,0,0,0,1
3,398571,105.24168,10.394855,0,0,0,0,1
4,807982,105.56148,10.331973,0,0,0,0,1
...,...,...,...,...,...,...,...,...
49391,664345,105.46446,9.630389,0,0,0,1,0
49392,1527014,106.54154,10.091225,0,0,0,1,0
49393,967309,105.67736,9.376165,0,0,1,0,0
49394,578874,105.39799,10.594281,0,1,0,0,0
49395,1438174,106.23431,10.621231,0,0,1,0,0

In [10]:
sample = df[df['sample_4'] == 1]
sample

,id,lon,lat,sample_1,sample_2,sample_3,sample_4,sample_5
267,948854,105.66389,9.595355,0,0,0,1,1
307,1429893,106.21365,10.983252,0,0,0,1,1
446,1192168,105.87229,9.810052,0,0,0,1,1
659,38861,104.74042,10.393957,0,0,0,1,1
791,1570086,106.65562,10.376889,0,0,0,1,1
...,...,...,...,...,...,...,...,...
49383,1102484,105.78786,10.845810,0,0,0,1,0
49389,626787,105.43751,10.224175,0,0,0,1,0
49390,107306,104.90302,9.078823,0,0,0,1,0
49391,664345,105.46446,9.630389,0,0,0,1,0
49392,1527014,106.54154,10.091225,0,0,0,1,0

In [11]:
api_key = '73f784c939b7c0017b23be2e72b482cc'

lats = sample['lat'].to_list()
lons = sample['lon'].to_list()

def create_json(lat:str, lon:str, start: int, end: int) -> dict:
    hist_url = f'http://api.openweathermap.org/data/2.5/air_pollution/history?lat={lat}&lon={lon}&start={start}&end={end}&appid={api_key}'
    r = requests.get(hist_url)
    json_out = r.json()

    return json_out

for i in tqdm(range(len(lats))[:]):

    print(lats[i], lons[i])
    

    start_1 = int(time.mktime(datetime(2022, 1, 1).timetuple()))
    end_1 = int(time.mktime(datetime(2022, 12, 31).timetuple()))
   
    # Dumps json file
    json_1 = create_json(lats[i], lons[i], start_1, end_1)
    with open(f"datasets/owm/{lats[i]}_{lons[i]}_2022.json", "w") as outfile: 
        json.dump(json_1, outfile)

  0%|          | 0/10000 [00:00<?, ?it/s]

9.595355 105.66389
10.983252 106.21365
9.8100519 105.87229
10.393957 104.74042
10.376889 106.65562
10.463127 106.1885
11.771074 106.58286
10.156802 105.56328
10.610451 106.32145
9.7866955 105.5507
10.521518 105.96482
9.6079311 105.79324
10.564637 105.23718
9.9699526 105.21114
10.776639 105.66479
10.418212 104.63082
10.443364 106.63227
9.9169512 105.37373
10.608654 106.28282
9.9007816 105.47973
9.723814 105.15903
9.8432894 105.41955
10.841318 105.24976
10.611349 106.42297
10.940133 105.56687
10.72274 105.68365
10.835928 105.87679
10.304126 104.64789
9.8289165 105.73575
10.590688 105.07639
10.319397 105.12669
10.485585 105.15903
10.29065 105.07639
10.425398 106.16515
10.741605 106.15527
9.8702393 105.51836
10.14692 105.07279
10.409228 105.3899
9.921443 105.97919
9.8540697 105.30546
10.730825 106.15437
9.8298149 105.5525
10.035529 105.91991
10.712859 105.48153
9.7274075 105.80492
10.182853 105.05393
9.5010319 105.68814
10.735317 106.17413
10.644587 105.29917
10.546671 105.68185
10.442466 106.23971
10.252023 105.11861
10.96798 105.43302
10.142428 105.17161
10.22148 105.03956
10.870962 105.11412
9.5495405 105.18419
9.8962908 105.55339
10.487382 106.75893
10.094818 106.15437
10.955404 106.58736
10.160395 106.00614
9.7462721 105.57495
10.229566 106.64395
10.502653 106.31427
10.410127 104.75569
10.089428 105.35666
9.7705259 105.37463
9.5513372 105.77438
10.49367 105.85793
9.8935957 105.28929
10.932048 106.1885
10.76586 106.11664
9.6537457 105.84804
10.634706 105.06831
10.267295 105.1752
10.031037 105.21832
10.561044 105.31983
10.086733 105.42763
9.6052361 105.36385
9.4336576 105.57854
10.750588 106.11754
10.554755 105.66389
10.340957 104.95242
10.120869 105.96572
10.417314 105.0701
10.802691 105.47434
10.247532 105.06561
10.244837 105.53542
10.50984 105.37463
9.8199339 105.72497
10.159496 105.34678
9.9627657 105.31803
10.668841 105.57675
10.490077 105.24258
9.6717119 105.98638
10.556552 105.02878
9.9007816 105.77528
9.8989849 105.36205
10.808081 105.96123
10.580807 105.88307
10.608654 105.71868
9.8648491 105.45818
10.013071 105.45638
9.7777128 105.25066
10.81886 105.40068
10.217887 104.82217
10.933845 105.6055
10.778436 105.59113
10.038224 105.61268
10.407432 104.94524
10.929353 105.77528
10.4775 105.68904
9.7498646 105.54172
10.108293 105.39978
10.182853 105.8714
10.40294 106.64934
10.464025 105.23629
10.458635 104.78893
9.5917616 105.79774
10.187345 105.40697
10.91498 105.15634
10.258311 106.71491
10.981455 105.68455
9.9591722 105.15454
10.906895 105.12759
10.780232 105.45188
10.040919 105.16622
9.3914375 105.60639
10.912285 105.66658
10.104699 106.12383
10.810776 105.77258
9.9852238 105.27581
10.101107 105.95314
10.140632 105.50129
10.912285 105.47973
10.151412 105.23718
9.6474571 105.20036
10.434381 105.06741
9.7822046 105.06201
9.704051 105.50398
9.3743696 105.54441
10.483788 106.23611
10.517026 105.62795
10.545773 105.09705
10.522416 105.89385
10.549366 106.47955
9.7372885 105.70701
10.047207 105.37643
10.110988 106.59095
10.397551 106.76343
10.831436 105.70251
10.300532 106.72121
10.9042 106.48944
10.715554 106.87032
10.301431 104.66406
10.296939 105.32073
10.736216 106.5622
10.57901 106.11304
10.793707 105.55788
9.7345934 105.88487
10.409228 105.11142
9.7417803 105.20215
10.658062 106.24869
10.330176 105.6028
9.3294535 105.55339
10.167582 104.89942
10.624824 105.26144
10.400246 105.32433
10.015766 105.44021
10.283464 105.10873
10.917675 105.66119
10.870064 105.40517
10.352634 104.76198
10.379584 105.65311
9.6357784 105.48153
10.66974 105.8175
9.1911125 104.9632
10.393957 104.6946
10.652672 106.34391
10.769453 106.0304
9.8810186 105.16532
10.454144 106.25228
10.484687 104.80869
9.7543564 105.19586
10.21609 104.90661
10.32299 104.97218
10.111886 105.57226
10.641892 105.74384
10.641892 105.48962
10.478398 105.8714
10.031936 105.42583
10.421804 105.51476
10.146022 106.00884
10.814368 106.02232
10.719147 105.93877
10.721842 105.97201
10.245735 104.76467
10.220582 105.12041
10.060682 106.16515
10.379584 105.32073
10.342753 105.03956
10.57901 105.50129
10.104699 105.41056
10.826945 105.74653
9.8118486 105.94955
10.612247 105.97111
10.15231 105.34947
10.203514 105.76989
10.186446 105.84984
9.9942064 105.53094
10.847607 105.79324
10.431686 104.58231
10.460432 104.77366
10.795504 105.91811
10.063377 106.15527
10.227769 105.70071
10.889827 105.83996
10.367007 106.62868
9.8396969 105.9756
10.532297 106.09328
10.521518 105.77708
10.384974 104.71257
10.199022 105.8714
10.554755 105.53542
10.5844 105.13657
9.3959284 105.72048
9.5612183 105.90015
10.0508 105.38721
10.72813 105.82468
9.5172014 105.80222
10.104699 105.16173
10.252023 104.79521
10.009478 105.13119
10.736216 106.27294
9.4228783 105.71239
10.148717 105.83366
10.56284 105.1752
10.43528 105.15544
9.3528099 104.87786
10.134344 105.89206
10.608654 106.11484
10.720943 105.72497
9.7076445 105.31983
10.291549 104.74222
9.8711376 105.60819
10.486484 106.43015
10.700282 105.79684
9.5198965 105.95045
10.310413 104.99374
9.704051 105.16442
10.931149 105.74833
10.196327 105.30995
10.326583 104.95422
10.958998 106.57208
10.399347 104.90391
10.071462 105.58573
10.093021 105.23718
10.569128 106.41039
10.544874 105.0162
10.17387 105.11501
10.878149 105.96123
10.959896 105.46356
10.83503 105.4941
10.452348 105.13837
10.687706 105.26504
9.4165897 105.62436
10.381381 104.84013
9.9331217 105.40158
9.8181372 105.87948
10.683214 105.05303
9.5073195 105.7088
10.716453 105.88218
10.851199 105.33151
9.3096905 105.50668
10.714656 105.19048
9.9286299 105.58214
10.224175 106.63946
10.043614 105.10154
9.6690168 105.45547
10.239447 105.19048
9.7768145 105.34499
10.247532 105.54261
10.720045 105.90194
9.5872698 105.66029
10.637401 105.75102
10.321194 105.2794
10.254718 105.80312
10.273582 105.15095
9.9034767 105.61089
10.495466 105.42583
10.375093 105.19497
10.069665 105.20305
10.12536 105.75462
10.218785 105.40427
10.046309 105.30815
10.615841 105.45818
9.4579124 105.63783
9.7327967 105.05123
10.190938 105.26054
10.428991 104.84462
10.015766 105.29018
10.315804 104.59309
10.346346 106.54514
10.470314 104.74491
10.849402 105.25515
10.213396 105.68455
10.433483 105.21024
9.7058477 105.56328
10.231362 105.34768
10.55206 105.55698
9.9501896 105.32343
10.252921 106.68168
9.7938824 105.31174
10.927556 106.29271
10.296041 105.01171
10.849402 106.34122
10.742503 105.43391
10.443364 106.18581
10.66974 106.0313
10.166683 105.07279
9.1704512 104.91918
9.5881681 105.63065
10.672435 105.4429
9.6052361 105.71599
9.5980501 105.68634
10.441567 105.0189
9.9843254 105.34589
9.6771011 105.53992
10.526908 105.14017
10.325686 106.54333
10.004088 105.43571
10.463127 106.23342
10.025648 105.21652
10.306821 105.45278
10.883539 105.21563
10.724537 105.42134
10.967082 106.23611
10.114581 105.20305
9.7866955 105.62526
10.636502 105.6576
10.02475 105.4977
10.588891 105.30007
10.417314 106.26575
10.366109 106.77061
10.851199 106.23611
10.3176 105.08268
10.985947 106.2981
10.870064 105.6567
10.686808 106.03669
10.495466 104.70898
10.902404 105.14466
10.331973 105.58573
10.882641 105.27671
10.533195 106.02411
10.743402 105.85433
9.7893906 105.34229
9.8405952 105.43122
10.078649 106.14898
10.307718 104.82935
11.772871 106.59903
10.550263 105.66299
9.9915113 105.30007
9.9780369 105.32253
9.7570515 105.8184
9.4516239 105.47794
10.492772 104.87157
10.184649 105.22371
10.431686 104.75569
10.915878 106.55322
9.4201832 105.59831
10.481992 104.62094
10.566434 105.87679
10.775741 105.57675
9.5791855 105.4968
10.280769 105.22102
9.8873072 105.23449
10.523314 106.68347
10.32299 105.53453
10.257413 104.82217
10.113683 105.30096
10.747893 105.28659
10.853894 105.51926
9.5405579 105.2848
10.791911 105.94595
10.73891 105.68724
10.709266 106.12023
10.340058 104.67574
10.812572 105.18688
10.795504 105.10244
10.314007 104.78983
9.6923723 105.98548
9.3123856 105.8184
10.958998 105.61089
10.464025 105.84265
9.3914375 105.48063
9.4588108 105.64502
10.596976 106.51369
10.070563 106.18581
10.139733 105.80312
10.852098 105.60819
9.7893906 105.94955
9.4183865 105.62257
10.5844 106.14089
10.91498 106.32864
10.454144 105.77528
10.5844 105.71329
10.81347 105.69173
10.358923 105.07549
10.453246 106.04298
10.580807 106.21365
10.467619 104.70448
10.633807 106.31876
10.446958 106.64664
10.16848 105.91451
10.078649 105.62346
9.9627657 105.25515
10.542179 105.7088
9.3797588 105.78426
10.614943 105.3881
10.629315 106.35469
10.371499 104.78444
9.3204699 105.75372
10.699384 105.67646
10.251125 105.37912
10.583502 105.31174
9.3887424 105.50398
10.428991 104.66496
10.466721 106.06633
10.4245 105.83906
10.308617 105.26144
9.9439011 105.19227
10.102902 106.02142
10.56284 105.74474
9.8343067 105.9756
10.49906 104.80959
10.359821 105.63873
10.492772 106.63406
10.4775 104.9668
10.655367 105.80402
9.6160164 105.53273
10.912285 106.62059
9.7426786 105.06381
9.5315742 105.70341
10.342753 105.34589
10.443364 105.98189
10.937438 105.61448
10.311312 105.46176
9.533371 105.62077
10.417314 105.37283
9.1021795 104.88595
10.473009 105.42403
10.807182 105.99536
10.685011 105.90913
10.162191 105.20934
9.6178122 105.93069
10.356228 104.8051
10.65357 105.31444
10.872759 105.4429
10.676028 105.98638
10.850301 105.56238
10.495466 106.10406
10.66435 105.74474
9.4408445 105.98817
9.9636641 105.22371
10.679622 106.1885
10.965285 105.6549
10.146022 105.36205
10.267295 105.11412
9.5621166 105.48422
10.764063 105.9217
9.980732 105.48782
10.760469 105.73755
9.9888172 105.46985
10.738011 105.90913
10.181056 105.37463
10.711062 105.17071
10.606857 105.93967
10.502653 105.67107
10.35533 106.70683
10.450551 105.9226
10.261006 105.17161
10.038224 105.88128
10.078649 105.16442
10.007682 106.10765
10.192735 105.442
10.334668 105.63783
10.673333 105.8148
9.713932 105.57585
10.533195 106.65832
10.571823 106.62688
10.057987 105.27581
9.4390478 105.48602
9.9654608 105.95045
9.2818422 105.56328
10.821555 105.90643
10.130751 105.98458
10.656265 105.03687
9.9151554 105.37733
10.487382 105.93248
10.090326 105.25515
9.7372885 105.59113
9.9744434 105.27402
10.912285 106.23252
9.8181372 105.26144
10.322092 105.46806
10.671536 105.46535
10.341855 105.61987
9.3222666 105.71329
9.6384735 105.72318
10.133446 105.1761
10.555654 105.12041
10.332871 104.90031
10.195429 105.28659
9.6232023 105.13567
10.393059 105.95943
9.3231649 105.53453
10.382278 104.93625
10.437077 105.36385
9.6312876 105.9244
10.426296 106.64754
9.3878441 105.57944
10.905996 106.57388
10.513433 105.09975
9.6285925 105.69712
9.3069954 105.58394
10.205311 105.07369
10.314007 105.13657
9.6986609 105.52644
9.4758787 105.72408
9.6744061 105.42313
10.596976 105.7088
10.155005 106.58376
10.331075 104.9641
9.3797588 105.61179
10.228667 104.97578
10.362516 105.08088
10.089428 106.57837
10.367906 104.7503
10.457737 104.61375
9.4219799 105.6558
9.6860847 105.59023
9.1803331 105.20664
10.014868 105.50488
10.402041 104.70898
10.853894 105.42583
10.193633 104.82037
9.3635893 105.66568
10.785623 105.90463
10.650875 105.071
10.923064 105.55698
10.578112 105.54261
10.803589 106.21815
10.423601 105.14017
10.478398 105.42044
10.985048 106.36278
10.872759 105.94147
10.163988 105.45099
9.6357784 105.4968
10.878149 105.7088
10.325686 104.6955
10.459534 105.20664
10.652672 105.93877
10.322092 105.54082
10.383177 106.62508
9.7049494 105.72048
9.4803705 104.93446
10.907793 105.41595
10.90959 106.5658
10.615841 106.31606
10.085835 105.25785
10.641892 105.85433
9.6267958 105.72856
9.9151554 105.19048
9.2935209 105.53542
10.006783 106.12383
10.457737 105.2318
9.9780369 105.45009
10.580807 106.32325
9.4354544 105.54261
9.8747311 105.42943
9.9816303 105.4959
10.966184 105.68724
10.630214 105.56507
9.3492165 105.81031
9.2351303 104.83743
10.538586 105.19407
9.6726103 105.60639
9.3447247 105.64143
10.565536 105.85343
10.632909 105.38181
10.826047 105.85793
10.302329 105.33151
9.8316116 105.50938
9.3968267 105.63783
9.7229156 105.92081
9.147994 104.93894
10.455941 105.70161
10.151412 106.06543
10.076852 106.58736
10.453246 104.68652
10.542179 105.4474
10.507145 106.35379
10.822453 105.80133
10.020258 105.29558
10.330176 106.66371
10.062479 105.84444
9.792984 105.2309
10.947319 105.7654
10.544874 105.11771
10.128954 105.25515
10.794605 105.39169
10.487382 105.79145
9.6528473 105.87679
10.23765 105.16622
10.727232 105.47614
10.28616 105.24437
10.305923 105.00362
10.754182 106.1382
10.049004 105.34319
9.5252857 105.72946
10.159496 105.38541
10.342753 104.97039
10.613146 105.37822
10.135242 105.24886
10.409228 106.04657
10.55206 106.00704
10.200819 105.31893
9.6294909 105.72767
10.412822 106.25947
9.5585241 105.78426
10.748792 105.18867
10.667943 105.70431
10.698486 105.80222
9.8459845 105.57585
10.767656 106.02052
9.4731836 105.58753
10.198124 106.07352
10.153209 104.87696
10.919472 106.26216
10.684113 106.54243
10.524213 105.30815
10.874556 105.27851
9.5854731 105.47973
10.325686 106.68168
10.07775 105.17161
10.689503 106.26306
10.579908 105.40517
10.301431 105.73486
10.448754 106.12473
10.223277 105.7654
10.844013 105.35397
10.590688 105.45009
10.470314 106.31516
10.102902 105.98458
9.7390852 105.4411
10.65357 105.66299
10.762266 105.3881
10.547569 106.05555
10.496365 106.06184
10.62662 105.5525
10.577213 105.27671
10.40833 105.33061
10.192735 105.06112
9.9852238 105.5516
9.7121353 105.21114
9.3528099 105.53184
9.6357784 105.84534
10.16309 105.83636
10.157701 104.88954
10.933845 106.44722
9.4004202 105.548
9.76334 105.56417
10.034631 105.19946
10.682316 106.1382
9.3186731 105.46087
10.667045 105.99806
10.810776 105.88757
10.433483 105.37553
10.090326 105.20485
9.3285551 105.77708
10.630214 105.63245
10.606857 105.90733
10.208006 104.92278
10.760469 105.09435
10.860183 105.62975
10.069665 105.47344
9.6375751 105.82199
9.3501148 105.48063
10.376889 104.63352
10.500856 105.67736
10.708367 105.67017
10.261905 105.74833
9.6187105 105.51207
9.3132839 105.5507
10.746995 105.97919
10.652672 105.32162
10.943726 105.51566
10.216989 105.46266
10.836826 105.77887
10.583502 105.46716
10.5844 106.71222
9.0887051 105.18149
9.7642384 105.67916
10.870064 106.29091
10.107394 105.98728
9.4695902 105.78965
10.372397 105.24617
10.500856 105.77887
10.821555 105.73126
10.763165 105.47075
10.802691 106.04208
9.3959284 105.47614
10.774842 105.36655
10.783826 105.21204
9.9456978 105.31983
10.163988 105.47614
10.06697 106.14089
10.364312 106.77331
9.296216 105.46806
10.777537 106.18311
10.428093 105.09256
10.187345 105.43391
9.2153673 104.85001
10.346346 105.56328
10.369702 106.74187
10.437077 105.33511
10.713758 105.41955
10.852996 105.10423
9.7884922 105.59292
9.6214056 105.35666
10.733521 106.29271
10.611349 105.63065
10.448754 105.80133
10.281668 104.67484
10.252023 104.93176
10.57901 105.91631
10.544874 106.08789
10.707469 106.02142
9.1273327 105.14825
10.545773 105.25785
10.191836 105.177
10.808081 106.20916
10.746097 105.40787
10.24843 105.34947
10.16309 105.26054
10.725435 106.99789
10.843115 105.45997
9.335742 105.56507
10.189141 105.03776
10.405635 104.98925
10.271786 105.08627
10.319397 105.20036
10.757774 105.10693
10.561942 106.10046
9.8693409 105.38541
10.452348 104.6407
9.2539949 105.78516
10.35533 105.61089
10.46133 104.7521
10.729927 106.1382
10.186446 105.39169
9.4282684 105.79324
10.652672 105.82019
9.9600706 105.9747
10.783826 106.09418
10.885336 105.46985
10.415517 105.18239
10.700282 105.59472
10.965285 105.61358
10.034631 105.34947
9.8909006 105.28749
10.905996 105.73934
10.241243 104.81229
10.711961 105.77618
10.24304 105.77708
10.828742 105.30276
9.563015 105.97111
9.5666084 105.5516
10.943726 106.17323
10.665248 106.15347
10.679622 106.28642
9.634881 105.82558
10.166683 105.89835
10.536789 105.89116
9.8316116 105.30995
10.808081 105.59561
10.637401 105.70341
10.915878 105.43571
10.970675 106.27654
10.196327 104.95512
10.786521 106.98171
10.643688 105.68455
10.352634 105.27312
9.0698404 104.91828
9.9277315 105.52914
10.515229 105.6055
10.32299 106.59544
10.222379 106.05555
9.5773888 105.56866
10.792809 105.99716
10.524213 105.58035
10.526908 106.68258
10.035529 105.40787
10.175667 105.09166
10.735317 105.26952
10.523314 105.91182
10.534992 105.37283
10.194531 104.93984
9.8953924 105.27132
9.4704885 105.73396
10.229566 106.04567
10.208006 105.89385
10.706571 106.0286
9.6510506 105.5525
10.84042 105.45638
10.335567 104.70988
10.873657 105.2848
9.8154421 105.66748
10.640994 105.11861
10.852996 105.10334
10.086733 106.59724
10.496365 104.6973
10.338262 105.17251
10.151412 104.97668
10.597875 105.79863
10.55745 105.89116
10.700282 106.05914
10.31221 105.39978
10.788318 105.98009
10.369702 105.177
10.396652 105.12849
10.060682 105.13298
9.493845 105.50848
10.915878 106.35379
10.759571 105.77797
10.380483 106.58286
9.7345934 105.54082
10.811673 105.19048
9.5324726 105.7654
10.884438 105.56507
9.7345934 105.93607
9.3114872 105.59292
10.975167 106.28372
10.471212 104.79971
10.861979 105.59651
9.6537457 105.99626
9.8747311 105.70251
10.219684 105.06291
10.861979 105.2821
9.8693409 105.73665
10.659859 105.41865
9.4920483 105.60639
10.277176 105.41236
9.8747311 105.64053
10.473907 105.3881
10.119073 105.64771
10.111886 105.85612
10.155904 104.9102
9.6312876 105.91541
10.178361 105.53004
10.421804 105.11412
9.6537457 105.39529
10.81886 105.866
10.793707 106.41488
10.563739 106.10676
9.5711002 105.50848
9.3339453 104.88415
11.817787 106.72121
10.614943 106.07082
9.3662844 105.79594
10.352634 106.60532
10.291549 105.01081
10.706571 105.8175
10.917675 106.36996
10.068767 105.42583
10.140632 105.19946
10.223277 105.46535
10.229566 105.4986
9.9304266 105.41775
10.182853 105.35577
9.5082178 105.78156
10.476602 104.83833
10.857488 105.58304
10.586197 105.07459
10.291549 105.47973
9.4974384 105.7097
9.733695 105.97021
10.794605 105.32612
9.5567274 105.61987
10.503551 106.57837
10.796402 105.7618
10.491874 105.43481
9.474082 105.62705
10.577213 106.03489
9.6860847 105.70071
9.4103022 105.77528
9.4911499 105.548
10.112784 105.19497
10.297837 105.02338
10.704774 105.82558
10.091225 105.2336
10.739808 105.3899
9.3833523 105.41865
10.297837 105.41415
10.177463 105.36744
10.460432 105.84265
10.910488 105.95135
10.035529 106.20377
10.913183 105.05932
10.539484 105.02069
10.863776 105.24976
10.222379 105.23539
10.987743 105.78246
9.2845373 105.81211
10.671536 106.01962
10.958099 106.57748
10.619434 105.53542
10.203514 105.49141
10.82425 106.36637
10.446059 105.04765
10.374194 104.8033
9.9394093 105.56507
10.938336 105.61448
10.827844 106.25049
9.5684052 105.97291
9.7094412 105.66927
10.468517 104.72514
10.741605 106.27654
10.837725 105.3378
9.9645624 105.59382
10.068767 105.93787
9.5064211 105.7636
9.8495779 105.67916
10.46133 104.5913
9.6627283 105.75821
9.3878441 105.71958
10.254718 105.13029
10.098412 105.06831
10.565536 105.7106
10.361618 104.65508
9.8792219 105.4995
9.2791481 105.54261
10.180158 105.87409
10.643688 105.08268
10.677825 105.4465
9.3537083 105.67287
9.872036 105.47524
10.820657 105.62795
9.8468828 105.61717
10.519721 106.16155
10.319397 105.61179
10.23765 104.74401
11.780058 106.63317
10.7973 105.52106
10.739808 105.2318
9.3393345 105.5462
10.508043 105.27492
10.691299 106.32684
10.690401 105.25695
9.8262215 105.27851
9.5818796 105.76989
9.7426786 105.59202
10.587993 105.82468
10.739808 105.83726
10.14692 105.86511
10.802691 105.09166
10.802691 106.15077
10.296041 106.72031
10.422703 104.72784
9.5324726 105.7079
10.070563 105.9747
9.7848988 105.85703
9.6860847 105.84894
10.601468 106.37086
10.22148 105.84085
10.727232 105.18688
10.23765 104.71436
9.822628 105.57316
10.39216 104.66496
9.3698778 105.48512
10.340957 104.98296
10.567332 106.32684
10.527806 106.57298
10.296939 106.63586
10.103801 106.62868
10.094818 105.58304
9.812747 105.40517
10.302329 105.2327
10.934743 106.5631
9.6303892 105.90374
10.192735 106.03669
10.285261 105.04765
10.383177 105.48243
10.621231 105.57316
9.6600332 105.99986
9.2081804 104.83743
10.129852 106.62868
9.1533833 104.85271
10.468517 106.1364
10.444263 105.49051
10.932946 105.80402
10.411923 106.05106
10.074157 105.60909
10.574518 105.93159
10.194531 105.12489
10.550263 105.64413
10.820657 106.33313
10.09392 105.30995
9.8037634 105.22282
10.075055 105.35577

In [14]:
sample = df[df['sample_5'] == 1]

lats = sample['lat'].to_list()
lons = sample['lon'].to_list()

def create_json(lat:str, lon:str, start: int, end: int) -> dict:
    hist_url = f'http://api.openweathermap.org/data/2.5/air_pollution/history?lat={lat}&lon={lon}&start={start}&end={end}&appid={api_key}'
    r = requests.get(hist_url)
    json_out = r.json()

    return json_out

for i in tqdm(range(len(lats))[1262+1718:]):

    print(lats[i], lons[i])
    

    start_1 = int(time.mktime(datetime(2022, 1, 1).timetuple()))
    end_1 = int(time.mktime(datetime(2022, 12, 31).timetuple()))
   
    # Dumps json file
    json_1 = create_json(lats[i], lons[i], start_1, end_1)
    with open(f"datasets/owm/{lats[i]}_{lons[i]}_2022.json", "w") as outfile: 
        json.dump(json_1, outfile)

  0%|          | 0/7020 [00:00<?, ?it/s]

10.522416 105.87948
10.127157 105.64053
10.798199 105.50039
10.25921 105.02338
10.804487 105.65401
10.142428 105.29648
10.171175 105.02788
10.396652 106.0304
10.734419 105.98997
9.0321112 105.24707
10.56284 105.55968
10.132547 105.89116
10.012173 105.41775
10.630214 105.63963
10.826945 105.64682
9.2288418 104.83295
10.783826 105.97381
9.7759161 105.88667
9.1839266 105.19138
10.773046 105.91631
10.002292 105.46356
10.890725 105.22192
10.923963 105.51656
9.5046253 105.73215
10.3176 106.69246
11.972297 106.59903
10.078649 105.54172
10.821555 105.24707
9.9933081 105.49321
9.2629776 105.21114
10.66435 105.09525
10.303227 104.99194
9.8909006 105.2857
10.475703 105.66927
9.5387611 105.55878
10.356228 105.09166
10.458635 105.22551
10.218785 105.47344
10.851199 105.68095
10.046309 105.62616
10.620333 105.98997
10.692198 105.59113
9.1821299 104.92368
10.165785 105.1231
10.571823 106.16695
10.423601 106.16784
9.4381495 105.57585
9.2737579 105.57585
10.300532 105.2803
9.4309626 105.52285
10.260108 105.68185
10.906895 105.70341
10.763165 105.10693
10.706571 105.61538
10.843115 105.60011
10.154107 105.48332
10.030139 105.15095
10.232261 105.495
10.514331 105.94865
9.4138947 105.71239
10.870064 105.53542
10.24304 104.81318
9.4624043 105.67916
10.806284 105.60819
10.16309 105.48332
9.3267584 105.56866
9.6178122 105.7645
10.363414 104.65148
9.8432894 105.41955
10.292447 104.7512
10.484687 106.38613
10.640994 106.09058
9.8379002 105.47075
9.7857971 105.97201
10.453246 105.87679
10.746097 105.89835
10.718248 105.75821
10.685011 106.31157
10.659859 105.27402
9.7579498 105.06561
10.755079 105.37103
10.66974 106.14539
10.156802 106.0834
10.449653 105.08537
10.926658 106.57208
10.356228 104.95691
10.630214 105.95135
10.66435 106.5074
10.712859 105.32433
9.306097 105.6549
10.38677 104.77814
9.7911873 105.55968
10.239447 105.4977
9.5118113 105.80133
10.137938 105.90643
10.614943 105.8148
10.025648 105.50758
10.002292 105.29108
10.711961 105.63873
10.931149 105.68455
10.923963 106.29001
10.900607 106.44273
9.4624043 105.5489
9.8989849 105.50578
9.5261841 105.82648
9.3564024 105.72946
9.7875938 105.51836
10.098412 105.495
10.65357 105.46446
10.553857 106.11574
10.329278 105.43841
9.6312876 105.67646
10.575417 105.53902
9.7157288 105.29018
10.143327 105.20215
9.9995966 105.91003
10.256515 105.02338
9.7417803 105.36655
10.880844 105.54531
10.682316 106.0843
10.671536 105.40966
9.5342693 105.84984
10.719147 105.67826
10.063377 106.10316
10.941929 105.70701
9.6564398 105.32073
9.812747 105.17071
10.075055 105.50309
10.167582 105.1752
10.157701 105.04135
9.7426786 105.06471
10.351736 105.55788
10.895217 105.6576
10.580807 105.52016
10.438872 105.01171
10.203514 106.07082
9.6878815 105.87589
9.4965401 105.66568
9.9331217 105.42763
10.157701 105.82019
10.636502 105.13747
10.719147 105.20664
9.812747 105.34858
10.951811 105.77168
10.479297 104.75838
10.633807 105.8184
9.5216932 105.87769
10.59518 105.49321
9.9403076 105.49321
9.3635893 105.77797
9.4489298 105.71329
10.56284 105.66838
10.670638 106.33762
9.812747 105.11412
9.5935583 105.79145
10.292447 105.4438
9.9025784 105.19946
10.946421 105.44469
10.034631 106.03669
9.1192474 104.82037
10.551162 106.50111
10.282566 105.45458
9.7318983 105.23718
10.369702 104.84821
10.418212 105.0153
10.374194 104.86349
10.4245 106.69605
9.4489298 105.59292
10.577213 105.28659
10.481093 105.12669
10.697588 105.26773
10.885336 105.57585
10.338262 106.63317
10.219684 105.43841
10.188243 105.19048
10.801792 105.91451
10.688604 106.47507
10.021156 106.2972
10.596976 106.0843
10.412822 104.67035
10.803589 105.5471
9.6070328 105.92081
10.444263 106.1328
10.368804 105.33421
10.308617 105.21922
10.369702 104.965
9.7256107 105.17341
10.305923 106.55592
10.241243 105.29558
10.335567 106.77869
10.742503 106.48854
10.862878 105.67646
10.754182 106.06723
9.6465588 105.87948
9.743577 105.29018
10.65896 105.11322
9.8729343 105.50398
10.273582 105.2812
9.634881 105.5516
10.048105 105.50578
10.201717 105.73486
9.555829 105.91272
10.258311 105.82558
10.930251 106.62418
10.854793 106.32056
10.087631 106.59364
10.400246 105.40427
10.586197 105.66119
10.084936 105.56687
9.7588482 105.72497
10.607756 106.26846
10.633807 105.46266
9.5198965 105.9765
9.3213682 105.74743
10.514331 105.26234
9.8639507 105.25785
10.755079 105.41505
9.7624416 105.83816
10.950912 106.5631
10.833233 105.14017
10.353533 104.73682
10.508942 105.24886
10.490975 106.12652
10.890725 105.72677
9.1129599 104.81588
10.925759 105.68634
10.151412 105.90733
10.299634 105.20215
9.572897 105.45278
10.053495 105.54531
10.571823 106.3987
9.951088 105.37822
10.343652 106.75803
10.895217 105.21563
9.4201832 105.74743
9.2746563 105.45368
9.385149 105.7079
10.368804 104.78174
10.137938 105.10963
10.014868 105.47524
9.4884548 105.63783
9.6753044 105.19227
10.720045 105.6567
10.870962 105.74564
9.6357784 105.66568
10.457737 104.85899
10.19004 105.9774
10.142428 105.3881
9.7372885 105.10064
9.9924097 105.25426
9.2692661 105.5471
10.670638 106.05466
9.8980865 105.28659
9.1336203 104.82037
9.9250364 105.1806
9.7561531 105.32433
10.544874 105.68993
10.852098 105.57136
9.8657475 105.68724
10.772148 106.9368
9.8971882 105.5471
10.449653 105.30546
10.698486 105.72587
10.544874 105.79774
10.240345 104.93625
10.737113 105.37553
10.135242 105.1806
10.399347 105.47704
10.416415 104.68023
10.854793 105.11053
10.213396 106.06633
10.048105 105.19676
10.465822 104.5895
9.4327593 105.72318
9.5540323 105.96482
10.257413 105.0171
10.091225 106.02142
9.4381495 105.59472
10.609552 105.87319
10.159496 105.55609
10.465822 106.09058
9.6519489 105.38271
10.839521 106.22174
9.6753044 105.82378
9.5091162 105.53094
10.624824 105.06381
10.117276 105.34409
10.841318 105.24976
10.41372 105.11322
10.194531 105.1743
10.137938 105.88218
9.4210815 105.55429
10.228667 105.34409
10.327481 104.71886
10.516128 106.59544
10.084936 105.29468
10.181056 105.04854
9.7525597 105.06741
10.932048 106.38793
10.715554 105.7079
9.8756294 105.20934
9.743577 105.36744
10.256515 105.7088
10.393059 104.65867
9.7202206 105.34139
10.965285 105.68005
10.225074 106.07621
10.940133 105.46266
10.381381 105.53812
10.735317 105.79684
9.7489662 105.62795
10.385872 105.57226
9.8181372 105.4429
10.404737 105.96662
10.466721 105.04675
9.5459471 105.55788
10.411025 104.83115
9.9223413 105.177
9.8630524 105.42134
9.5100145 105.54351
10.384974 105.03327
10.474806 104.88505
10.676028 106.85685
10.085835 106.59544
9.3150806 105.45997
10.209803 104.83384
9.5324726 105.4959
10.269989 105.70521
10.718248 106.11754
10.826945 105.87589
10.663451 106.70683
10.4775 106.04747
10.010376 106.11574
10.038224 105.09076
9.5612183 105.89475
9.9196463 105.40158
9.9888172 105.21383
10.087631 106.06184
9.9124603 105.40787
10.576315 105.14017
10.886233 106.47057
10.780232 105.18149
9.9187479 105.2309
10.472111 105.00991
10.201717 105.548
9.3043003 105.5525
10.772148 105.5525
10.495466 104.83743
10.711961 105.68993
10.535891 105.67736
10.064276 106.14898
10.720943 105.82378
10.783826 105.68185
10.471212 105.09705
10.318499 104.81408
10.288854 105.0162
10.607756 106.32325
10.262803 105.04765
10.143327 105.27851
10.572721 105.84624
10.755079 105.47794
10.520619 105.99716
10.425398 104.64879
9.424675 105.55698
9.4085054 105.56866
10.465822 105.67377
9.8163404 105.33421
10.135242 105.23898
10.081344 105.48512
10.870962 105.41325
10.399347 106.64664
10.906895 105.41415
9.8774261 105.71149
10.769453 106.01333
10.092123 105.20574
10.553857 105.08447
10.32299 104.76736
10.900607 105.13478
9.1120615 104.87157
10.084038 105.68365
10.211599 105.46895
10.462229 104.76467
10.791911 106.06723
9.5935583 105.95584
10.094818 105.88307
10.538586 106.49303
10.395754 105.40158
10.652672 106.05735
10.505348 106.68078
10.63201 106.31786
10.441567 105.23898
10.812572 105.75282
10.689503 105.42134
10.256515 104.83654
10.167582 105.84624
10.075953 106.57927
10.538586 105.9765
10.469416 104.87786
9.3348436 104.90031
9.9160528 105.18329
10.370601 106.69875
10.417314 105.40517
10.285261 105.03956
9.9259348 105.13567
10.634706 106.723
10.77125 105.86062
10.353533 105.58842
10.165785 105.10693
10.670638 105.40337
10.602366 106.28552
10.378686 105.15454
10.544874 106.59814
10.321194 105.37643
10.793707 105.10873
9.8190355 105.20305
10.458635 104.65238
10.623028 105.30546
10.923963 105.7142
10.434381 106.15437
10.632909 106.70054
9.5387611 105.61807
10.363414 105.11053
9.9430027 105.67646
9.9376125 105.6046
10.489179 104.83295
10.603265 105.42583
10.546671 105.78786
10.474806 106.07532
10.179259 105.40427
10.987743 106.27205
10.304126 105.10064
9.7462721 105.46806
10.603265 105.21293
9.8271198 105.67646
10.464924 104.76467
9.76334 105.84804
10.700282 105.6055
10.215192 105.39259
10.686808 106.30798
10.134344 105.0719
10.981455 106.25677
9.4659977 105.73306
10.455941 104.59669
10.832335 105.34678
10.459534 105.21473
10.838623 105.8175
9.4435396 105.72227
10.641892 106.27474
9.6932707 105.62257
10.639197 105.11591
10.439771 104.86528
10.897912 106.22893
9.9969015 105.18598
11.625547 106.6188
10.48828 105.69533
9.6375751 105.38631
10.458635 105.67736
9.8145437 105.63963
10.826047 105.18778
10.449653 105.89026
10.566434 106.32504
10.751487 105.56687
10.383177 105.56956
10.468517 105.16263
10.541281 105.62616
9.7247124 105.91182
10.117276 105.20126
10.112784 105.18958
10.040919 105.57944
10.739808 106.5658
10.00319 105.40247
10.969777 106.22983
9.8181372 105.98189
10.25921 105.46895
10.507145 105.73396
10.422703 104.98116
10.332871 104.97398
10.473009 106.72659
10.60057 106.03848
9.8989849 105.43302
10.72274 105.14286
10.269092 104.76647
10.514331 105.81211
10.353533 106.71851
10.300532 105.39169
10.572721 105.78067
9.8190355 105.52554
10.054394 105.18419
10.572721 106.12562
9.7965775 105.97919
9.76334 105.48422
10.376889 104.92368
10.296041 104.96949
10.479297 105.10783
10.138836 105.43122
10.447856 104.86259
10.748792 105.95045
10.672435 105.30456
10.714656 106.25408
10.679622 106.28552
10.654469 105.13657
9.7489662 105.47434
9.5360661 105.51926
9.6007442 105.07369
10.660757 105.69712
9.2396221 105.21024
10.388567 105.11501
10.556552 105.99267
10.208904 105.82828
10.365211 105.31983
10.569128 105.87769
10.655367 105.04854
10.048105 105.85522
10.872759 105.60819
10.084936 106.05645
10.725435 106.1355
10.436178 105.15634
10.535891 106.58017
10.887132 105.36834
10.331973 105.08537
10.271786 105.30995
10.078649 105.37822
9.8370018 105.4995
10.32299 104.92727
10.481992 105.10963
10.627519 105.78516
10.666146 105.75642
10.729029 106.01962
10.958099 105.78875
9.7678308 105.47884
10.874556 105.7627
10.437974 105.88397
10.223277 105.32971
10.508942 105.71599
10.638299 105.31803
10.810776 105.46356
10.527806 105.57854
10.905996 105.76
10.369702 106.6152
10.474806 106.04836
10.5844 105.92529
10.393059 105.6549
10.176565 105.74204
10.745198 105.65849
10.879047 106.36367
9.5055227 105.61807
9.8441877 105.59023
9.5594225 105.88487
10.215192 105.79414
10.932048 105.5489
10.923064 105.50309
10.836826 105.16173
10.930251 106.22264
9.5989475 105.93428
10.967082 105.65221
9.8585615 105.15005
10.453246 106.12921
10.023851 105.20126
10.158598 105.866
10.451449 105.82738
9.7974758 105.95673
10.08314 106.04118
10.589789 105.7142
10.499958 105.72048
9.6627283 105.79324
10.492772 105.2282
9.1740446 104.91828
10.07236 105.27581
10.711961 105.95584
9.2998085 105.63335
9.6160164 105.39349
9.694169 105.16083
10.121767 105.95314
9.3977251 105.72946
10.212498 104.83205
10.091225 105.20844
9.802866 105.08088
10.404737 106.65293
10.465822 105.30995
10.40294 104.65508
10.065173 106.14089
10.758673 105.59023
10.99493 106.32504
10.895217 106.16245
10.081344 105.10423
10.07236 105.95763
11.994755 106.80295
10.261905 104.99194
9.1821299 105.07998
10.175667 105.95045
9.7965775 105.26144
10.263701 104.79432
10.855691 106.42925
9.9474945 105.48422
10.553857 105.57944
10.643688 105.69982
10.36072 105.79594
10.149615 105.73486
9.5351677 105.71509
10.907793 106.47955
10.985947 106.24869
10.3176 104.73503
10.951811 105.62795
10.450551 105.46087
10.195429 105.08897
10.485585 105.89835
10.094818 105.9765
10.166683 105.77618
10.480195 105.33421
9.513608 105.90733
10.229566 105.08986
10.147819 106.16874
10.23765 105.91003
10.508942 105.89565
9.8091536 105.36025
10.959896 106.49123
10.534094 105.83097
10.561044 105.06291
10.698486 105.06651
10.123564 105.25156
10.923064 105.71599
10.051699 106.13461
10.679622 106.20737
10.74969 105.56866
10.062479 106.05466
10.487382 104.72155
10.686808 106.14539
10.020258 105.42583
10.457737 105.78875
9.9546804 105.34589
10.441567 104.56884
10.543976 106.37266
9.4974384 105.56238
10.787419 105.8184
10.226871 104.9659
10.848504 105.11232
10.423601 105.47884
10.067868 105.97381
10.232261 105.47884
10.398449 105.11951
10.238548 105.20664
10.315804 104.94883
10.525111 106.07352
9.7768145 105.63335
10.294244 105.67736
10.156802 105.11142
10.457737 106.05555
10.643688 106.58017
9.8289165 105.50848
10.513433 105.94595
10.658062 105.25336
10.494568 104.87247
10.84581 105.98279
9.7076445 105.08537
10.396652 105.54531
10.158598 105.5471
10.750588 105.3369
10.60057 105.68455
9.5980501 105.57136
9.147994 105.05393
10.500856 105.2318
10.450551 105.24617
10.602366 105.17161
9.5684052 105.88218
9.5719986 105.4959
10.08853 105.34858
9.3546066 105.56058
10.937438 105.75911
9.1578751 105.03057
9.842391 105.36565
10.49367 105.79504
10.481093 105.43212
10.171175 105.96033
10.32299 105.62346
10.9042 105.80312
10.621231 106.28642
10.150514 105.40877
11.918398 106.81463
10.817063 105.91092
10.706571 105.17071
10.713758 105.91362
10.202616 105.76809
10.102004 105.58304
10.33916 104.88864
10.16848 105.18688
9.7480679 105.26773
10.605062 105.58932
9.7408819 105.23539
10.110089 105.92799
10.611349 105.3369
9.9726467 105.46985
10.172972 105.82468
10.206209 105.27312
10.366109 105.9756
9.2971144 105.53363
10.029241 105.62167
10.367007 104.84103
10.041818 105.69263
10.23765 105.94506
9.5163031 105.59561
10.254718 105.25336
10.590688 106.26037
10.973371 105.75642
10.342753 105.01171
10.398449 106.62149
10.376889 104.67035
10.676927 105.59472
10.24843 104.97218
10.340058 105.1797
10.433483 106.2945
10.88803 106.49213
10.445161 105.48782
10.160395 105.52734
9.6052361 105.69443
10.371499 105.21204
9.1066713 104.86977
9.872036 105.53184
10.41372 104.67304
10.40833 106.71043
9.7965775 105.94237
10.643688 106.34212
10.266397 104.71796
9.3043003 104.88415
10.105597 105.83636
9.6708136 105.35127
10.661655 105.45368
10.340058 105.40966
10.758673 106.95387
10.187345 104.90391
9.6717119 105.87319
10.579908 106.43644
10.09931 105.21473
10.972472 106.28103
10.611349 105.80043
10.269092 105.75821
10.549366 106.01513
10.820657 105.26773
9.862154 105.48872
10.974269 105.74294
10.570026 105.15185
10.508942 105.18598
10.070563 105.26144
10.422703 105.92619
9.0994844 104.8572
10.603265 105.74294
10.828742 105.32433
9.194706 104.87337
10.316702 105.62346
9.5261841 105.19946
10.176565 104.85001
10.358923 105.13657
9.1686554 104.97847
9.6905766 105.20754
10.39216 105.25426
9.483964 105.61987
9.7130337 105.61179
10.078649 105.09435
10.857488 105.13298
9.7345934 105.48332
10.144225 105.84444
9.6905766 105.84715
10.463127 104.84013
10.001393 106.58915
10.705672 105.1752
10.252023 105.69892
10.564637 106.48405
10.374194 104.66406
10.319397 104.88684
10.071462 105.08717
10.625722 106.2433
10.737113 105.25874
10.245735 104.68652
9.7408819 105.19676
10.092123 106.57927
10.133446 106.00614
10.60057 106.25677
10.953608 106.25947
10.343652 105.40787
9.2944193 105.21024
10.661655 105.13657
10.287058 105.35666
9.6384735 105.51207
9.4615059 105.75012
10.24304 105.71689
10.501755 105.89925
10.662553 105.61358
9.4794722 105.99267
10.870064 105.26054
10.531399 105.93069
10.33916 105.02698
10.474806 105.93248
10.570925 105.03687
10.7443 105.27851
10.326583 106.69605
9.8387985 105.50309
9.3725729 105.57585
9.066247 104.91559
9.2054863 104.92098
10.288854 104.7485
10.427195 106.2999
10.337363 105.30815
9.7292032 105.42943
10.122665 105.77168
10.065173 106.09867
9.8935957 105.21114
10.051699 105.53722
9.5540323 105.57495
10.541281 106.58466
10.420008 106.72929
10.779334 105.442
10.555654 105.73126
10.250227 106.68258
9.90168 105.99536
9.6124229 105.81031
10.623926 105.93518
10.827844 106.41667
10.512534 105.46087
10.975167 105.76899
9.5055227 105.80582
10.43528 105.48063
10.180158 105.94237
9.9430027 105.4474
10.047207 106.18401
9.6564398 105.37553
9.4228783 105.4986
9.5279808 105.94775
9.4471331 105.54172
10.155005 105.15723
10.457737 104.98476
10.236752 105.04765
10.229566 105.36834
10.850301 105.72227
10.411025 104.86618
10.877251 105.39529
9.5216932 105.27042
9.4004202 105.78336
9.951088 105.21204
10.885336 106.55681
10.362516 104.82307
9.4363527 105.71149
9.8396969 105.32162
10.142428 105.76989
10.48828 104.7476
10.709266 105.5516
10.287956 104.97218
10.543077 105.77887
10.683214 106.28372
9.7247124 105.18508
9.6402702 105.58035
10.337363 104.74042
10.915878 105.14556
10.395754 105.2291
10.395754 105.04405
10.759571 105.39978
9.8684425 105.16532
10.350838 106.51908
10.790114 106.47596
9.59266 105.6549
9.1192474 104.92906
9.0994844 104.92727
10.407432 104.71616
10.439771 106.22174
10.437077 106.68617
9.5648117 105.80043
10.163988 105.17071
10.695791 105.66658
10.862878 105.49231
10.622129 105.84715
10.827844 105.23988
10.417314 105.24258
10.441567 106.06723
10.399347 105.09525
10.501755 105.67467
9.3096905 105.65041
10.614943 105.32792
10.098412 105.3881
10.670638 106.18581
9.6573381 105.53363
10.63201 105.48692
10.410127 104.73503
10.412822 105.78786
9.6833897 105.37463
9.5675068 105.495
10.529603 105.57136
10.500856 106.00704
10.463127 105.98009
9.3590975 105.5498
10.667943 105.94685
10.619434 105.54441
10.596078 105.58573
9.8154421 105.6567
9.4713869 105.548
10.359821 106.72839
10.943726 106.19928
9.5046253 105.72227
10.76586 106.23072
10.078649 106.59364
10.501755 106.11395
10.769453 105.10603
9.7426786 105.91362
10.781131 105.43661
9.8361034 105.4959
10.819758 106.02142
10.399347 105.84265
10.685011 106.0322
10.232261 104.92727
10.611349 106.42297
10.822453 105.79234
9.7076445 105.90104
10.275379 104.73772
10.490077 106.69156
9.1345186 104.97128
10.791911 105.14735
10.310413 105.55429
10.111886 106.5667
9.454319 105.57764
9.0994844 104.89403
10.940133 105.56687
9.83251 105.09435
10.022953 105.45547
10.278074 104.79432
9.595355 105.37733
9.9546804 105.59472
9.6591349 105.97111
9.6932707 105.86331
10.241243 105.05034
9.7678308 105.29468
10.622129 105.70701
10.852098 105.10513
10.313108 105.23
10.14153 105.16982
10.213396 105.77618
10.387669 106.73468
9.3546066 105.67646
10.884438 105.62885
10.217887 104.82396
10.831436 105.80043
10.266397 105.64951
10.954506 106.34481
9.7166271 105.46176
10.021156 105.25246
9.595355 105.62616
10.654469 105.04135
10.939235 105.73486
9.5962534 105.00722
10.191836 106.07532
10.642791 105.29018
10.274481 105.32971
10.868267 105.77528
10.64818 106.17503
10.841318 105.33421
9.7678308 105.57585
10.361618 105.4995
10.455043 105.14735
10.867369 105.68185
10.238548 105.31084
9.7660351 105.56238
10.39216 105.35936
10.216989 105.48332
9.296216 105.44469
9.59266 105.72946
9.7705259 105.05303
9.8513746 105.11142
10.624824 105.1806
9.2926226 105.58394
9.375267 105.68814
10.3176 105.08717
10.847607 105.69443
10.791013 105.43481
9.5540323 105.89835
10.063377 106.12292
10.743402 106.00974
10.189141 106.06454
10.528705 106.0807
10.574518 105.58214
10.033732 105.1761
10.633807 105.67467
10.464924 106.2433
10.40294 104.91918
10.932946 106.58736
9.3986235 105.78067
9.5818796 105.98369
10.164886 105.42313
9.1929092 104.97847
10.478398 105.8696
10.109191 106.1894
9.3824539 105.72497
10.349939 105.02159
9.980732 105.124
9.6771011 105.42044
10.2646 105.07909
10.561044 105.01171
9.9762402 105.58035
9.9007816 105.24796
10.721842 105.42853
10.48289 106.05106
10.119073 105.42853
10.291549 105.48782
10.973371 105.66838
10.910488 106.36816
10.364312 105.60819
10.357126 105.56328
10.610451 105.89296
9.7911873 105.50848
9.4875565 105.72587
10.359821 104.81498
9.8756294 105.29648
10.897014 106.17413
10.698486 106.0277
10.288854 105.14376
10.496365 105.1222
10.639197 105.79504

In [44]:
with open('JAXA_subtiles.json', 'r') as json_file:
    jaxa_subtiles = json.load(json_file)

tiles = list(jaxa_subtiles.keys())[1:16]
tiles.extend(list(jaxa_subtiles.keys())[33:])

bbox = [jaxa_subtiles[tile] for tile in tiles]

bbox = [box(tile[0], tile[1], tile[2], tile[3]) for tile in bbox]

tiles_gdf = gpd.GeoDataFrame({'tile': tiles, 
                              'geometry': bbox})
tiles_gdf = tiles_gdf.set_crs(epsg=4326)
tiles_gdf.head()
tiles_gdf.to_file('chosen_tiles.json', driver='GeoJSON', index=False)

In [35]:
tiles_gdf.crs

In [38]:
dist_gdf = gpd.read_file('gadm41_VNM_2.json')
dist_gdf = dist_gdf.to_crs(tiles_gdf.crs)
dist_gdf.head()

,GID_2,GID_0,COUNTRY,GID_1,NAME_1,NL_NAME_1,NAME_2,VARNAME_2,NL_NAME_2,TYPE_2,ENGTYPE_2,CC_2,HASC_2,geometry
0,VNM.1.1_1,VNM,Vietnam,VNM.1_1,AnGiang,NA,AnPhú,AnPhu,NA,Huyện,District,NA,VN.TT.AL,"MULTIPOLYGON (((105.15660 10.82870, 105.16010 ..."
1,VNM.1.3_1,VNM,Vietnam,VNM.1_1,AnGiang,NA,ChâuĐốc,ChauDoc,NA,Thànhphố,City,NA,VN.KG.AB,"MULTIPOLYGON (((105.10500 10.63830, 105.08150 ..."
2,VNM.1.4_1,VNM,Vietnam,VNM.1_1,AnGiang,NA,ChâuPhú,ChauPhu,NA,Huyện,District,NA,VN.HP.AD,"MULTIPOLYGON (((105.18790 10.46030, 105.17980 ..."
3,VNM.1.5_1,VNM,Vietnam,VNM.1_1,AnGiang,NA,ChâuThành,ChauThanh,NA,Huyện,District,NA,VN.GL.AK,"MULTIPOLYGON (((105.37090 10.36220, 105.36820 ..."
4,VNM.1.2_1,VNM,Vietnam,VNM.1_1,AnGiang,NA,ChợMới,ChoMoi,NA,Huyện,District,NA,VN.BD.AL,"MULTIPOLYGON (((105.48720 10.53950, 105.48840 ..."

In [78]:
dist_geom = [geom for geom in dist_gdf.geometry]

intersects_geom = []
for geom in dist_geom:
    gdf = tiles_gdf.iloc[tiles_gdf.sindex.query(geom, predicate='intersects')]
    if len(gdf) > 0:
        intersects_geom.append(geom)

In [98]:
intersects_geom = list(set(intersects_geom))
dist_filtered = dist_gdf[dist_gdf.geometry.isin(intersects_geom)]

In [99]:
dist_filtered['lon'] = dist_filtered.centroid.x
dist_filtered['lat'] = dist_filtered.centroid.y
dist_filtered = dist_filtered[['GID_2', 'lat', 'lon']]
dist_dict = dist_filtered.set_index('GID_2').to_dict('index')
dist_dict

C:\Users\sonle\AppData\Local\Temp\ipykernel_28392\439494382.py:1: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  dist_filtered['lon'] = dist_filtered.centroid.x
c:\Users\sonle\anaconda3\envs\geospatial\Lib\site-packages\geopandas\geodataframe.py:1528: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
C:\Users\sonle\AppData\Local\Temp\ipykernel_28392\439494382.py:2: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  dist_filtered['lat'] = dist_filtered.centroid.y
c:\Users\sonle\anaconda3\envs\geospatial\Lib\site-packages\geopandas\geodataframe.py:1528: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

{'VNM.1.1_1': {'lat': 10.846404435922919, 'lon': 105.10074651097067},
 'VNM.1.3_1': {'lat': 10.674122054506455, 'lon': 105.08741946173457},
 'VNM.1.4_1': {'lat': 10.557603596145857, 'lon': 105.1797822230923},
 'VNM.1.5_1': {'lat': 10.421303385083814, 'lon': 105.26575383802694},
 'VNM.1.2_1': {'lat': 10.474944476027188, 'lon': 105.46144105444661},
 'VNM.1.6_1': {'lat': 10.371310030995655, 'lon': 105.42804673733518},
 'VNM.1.7_1': {'lat': 10.654870714342247, 'lon': 105.2757414511293},
 'VNM.1.9_1': {'lat': 10.800174081298888, 'lon': 105.18645918433309},
 'VNM.1.10_1': {'lat': 10.29683597866068, 'lon': 105.25556484274274},
 'VNM.1.8_1': {'lat': 10.547266352717338, 'lon': 105.01170710864969},
 'VNM.1.11_1': {'lat': 10.412558176021932, 'lon': 104.95909074038255},
 'VNM.7.5_1': {'lat': 10.5767716473971, 'lon': 107.08808543963191},
 'VNM.3.1_1': {'lat': 21.27452053546984, 'lon': 106.19658531724376},
 'VNM.3.2_1': {'lat': 21.324537974828658, 'lon': 105.96767319204977},
 'VNM.3.3_1': {'lat': 21.375265303697944, 'lon': 106.25353826985783},
 'VNM.3.4_1': {'lat': 21.282227696405553, 'lon': 106.46394219598645},
 'VNM.3.5_1': {'lat': 21.437154300988922, 'lon': 106.64073185958205},
 'VNM.3.6_1': {'lat': 21.309618967191483, 'lon': 106.85391325148451},
 'VNM.3.7_1': {'lat': 21.38631608931258, 'lon': 106.10326691816228},
 'VNM.3.8_1': {'lat': 21.27327270334532, 'lon': 106.09031285904712},
 'VNM.3.9_1': {'lat': 21.208523699429236, 'lon': 106.25254189799601},
 'VNM.3.10_1': {'lat': 21.519312093890722, 'lon': 106.13422514935968},
 'VNM.4.3_1': {'lat': 22.187349305492997, 'lon': 105.57411636155781},
 'VNM.4.4_1': {'lat': 21.98334234242168, 'lon': 105.84969344070213},
 'VNM.4.5_1': {'lat': 22.165469098406337, 'lon': 106.09068738441636},
 'VNM.2.1_1': {'lat': 9.270148882834658, 'lon': 105.76006522147505},
 'VNM.2.2_1': {'lat': 9.146158314072437, 'lon': 105.4222409150234},
 'VNM.2.3_1': {'lat': 9.264503862583094, 'lon': 105.3907122901949},
 'VNM.2.5_1': {'lat': 9.25431392452984, 'lon': 105.61397318689535},
 'VNM.2.4_1': {'lat': 9.515464238258716, 'lon': 105.40450752413687},
 'VNM.2.6_1': {'lat': 9.387981817925294, 'lon': 105.42085753929125},
 'VNM.2.7_1': {'lat': 9.357475102697261, 'lon': 105.70238858368658},
 'VNM.5.1_1': {'lat': 21.170589039947348, 'lon': 106.07411386095086},
 'VNM.5.2_1': {'lat': 21.075268930376033, 'lon': 106.20880132442728},
 'VNM.5.3_1': {'lat': 21.022603408852333, 'lon': 106.22604504678323},
 'VNM.5.4_1': {'lat': 21.140874221024465, 'lon': 106.17875776629543},
 'VNM.5.6_1': {'lat': 21.03719924238379, 'lon': 106.07648328889977},
 'VNM.5.7_1': {'lat': 21.114984571469147, 'lon': 106.03285665055495},
 'VNM.5.5_1': {'lat': 21.126532906506693, 'lon': 105.95949056728294},
 'VNM.5.8_1': {'lat': 21.208023556445625, 'lon': 105.97359109166437},
 'VNM.6.2_1': {'lat': 10.062987234466304, 'lon': 106.59568270453141},
 'VNM.6.1_1': {'lat': 10.238518959142223, 'lon': 106.37261842254041},
 'VNM.6.3_1': {'lat': 10.176887662077924, 'lon': 106.64783681966894},
 'VNM.6.5_1': {'lat': 10.290487750533405, 'lon': 106.30513518145705},
 'VNM.6.4_1': {'lat': 10.23006395544472, 'lon': 106.16019683386469},
 'VNM.6.6_1': {'lat': 10.156419439442443, 'lon': 106.46768846937505},
 'VNM.6.7_1': {'lat': 10.180149879460549, 'lon': 106.28972851332321},
 'VNM.6.8_1': {'lat': 10.06973704036731, 'lon': 106.35840373071349},
 'VNM.6.9_1': {'lat': 9.927977357469766, 'lon': 106.5509578334737},
 'VNM.9.5_1': {'lat': 10.90801193980671, 'lon': 106.77621999951585},
 'VNM.9.7_1': {'lat': 11.063133589193216, 'lon': 106.75220044352966},
 'VNM.9.8_1': {'lat': 11.021636950764123, 'lon': 106.66454602911246},
 'VNM.9.9_1': {'lat': 10.935455586456957, 'lon': 106.7102020124969},
 'VNM.10.1_1': {'lat': 11.683650597389345, 'lon': 106.58537732428621},
 'VNM.10.2_1': {'lat': 11.99308957051549, 'lon': 106.82156901643296},
 'VNM.10.4_1': {'lat': 12.024320359394432, 'lon': 107.04708861462404},
 'VNM.10.5_1': {'lat': 11.469439413915516, 'lon': 106.66534586208618},
 'VNM.10.6_1': {'lat': 11.497401643724752, 'lon': 106.9552793018042},
 'VNM.10.7_1': {'lat': 11.519676486536591, 'lon': 106.84710000840535},
 'VNM.10.8_1': {'lat': 11.618742720027555, 'lon': 106.61238195656014},
 'VNM.10.9_1': {'lat': 11.846661603516084, 'lon': 106.5724444322269},
 'VNM.10.10_1': {'lat': 11.73669558331828, 'lon': 106.90017256412447},
 'VNM.10.11_1': {'lat': 11.824561917670339, 'lon': 106.99672346278408},
 'VNM.13.1_1': {'lat': 9.171786016037853, 'lon': 105.19073109558677},
 'VNM.13.2_1': {'lat': 9.005028594256576, 'lon': 105.05302995528227},
 'VNM.13.3_1': {'lat': 8.96041418363201, 'lon': 105.2423355855557},
 'VNM.13.6_1': {'lat': 8.891565410982148, 'lon': 104.88339394137542},
 'VNM.13.7_1': {'lat': 9.368509322568412, 'lon': 105.13881361143413},
 'VNM.13.8_1': {'lat': 9.13192834756218, 'lon': 104.91928959026733},
 'VNM.13.9_1': {'lat': 9.371531806738366, 'lon': 104.94893377351754},
 'VNM.12.1_1': {'lat': 10.063414816290054, 'lon': 105.72317861524228},
 'VNM.12.3_1': {'lat': 9.991199348775488, 'lon': 105.78683461424293},
 'VNM.12.2_1': {'lat': 10.12691419840647, 'lon': 105.46076051545232},
 'VNM.12.4_1': {'lat': 10.030877117281348, 'lon': 105.76444699955354},
 'VNM.12.5_1': {'lat': 10.12679530380432, 'lon': 105.63323780922968},
 'VNM.12.6_1': {'lat': 9.998282609777052, 'lon': 105.66314802037238},
 'VNM.12.8_1': {'lat': 10.030653992080458, 'lon': 105.53856998513818},
 'VNM.12.7_1': {'lat': 10.24199393080869, 'lon': 105.54703486818579},
 'VNM.12.9_1': {'lat': 10.2139187404841, 'lon': 105.36901395571917},
 'VNM.17.1_1': {'lat': 10.917952995938165, 'lon': 106.88097653427613},
 'VNM.17.5_1': {'lat': 10.765147506866247, 'lon': 107.02316510061164},
 'VNM.17.6_1': {'lat': 10.692007807886403, 'lon': 106.88790814676024},
 'VNM.17.9_1': {'lat': 10.969338073247451, 'lon': 107.03513959654012},
 'VNM.17.10_1': {'lat': 11.23858163965196, 'lon': 107.05006999236262},
 'VNM.18.2_1': {'lat': 10.48883159364153, 'lon': 105.70496819049595},
 'VNM.18.1_1': {'lat': 10.455672707773553, 'lon': 105.61977824155866},
 'VNM.18.3_1': {'lat': 10.22665352476896, 'lon': 105.81841229854851},
 'VNM.18.5_1': {'lat': 10.815929994371904, 'lon': 105.2812002023233},
 'VNM.18.4_1': {'lat': 10.818532344234784, 'lon': 105.37948998891295},
 'VNM.18.7_1': {'lat': 10.248929712327993, 'lon': 105.65777601794854},
 'VNM.18.6_1': {'lat': 10.359199859121633, 'lon': 105.60279745498451},
 'VNM.18.8_1': {'lat': 10.317962379127176, 'lon': 105.74041430257842},
 'VNM.18.9_1': {'lat': 10.728753721368069, 'lon': 105.52461955439067},
 'VNM.18.10_1': {'lat': 10.873785852653786, 'lon': 105.48637883522451},
 'VNM.18.11_1': {'lat': 10.609085454501733, 'lon': 105.47360699389823},
 'VNM.18.12_1': {'lat': 10.561909003557268, 'lon': 105.7977731596112},
 'VNM.28.1_1': {'lat': 20.491748198834127, 'lon': 106.03757094645132},
 'VNM.28.2_1': {'lat': 20.637455701095547, 'lon': 105.97194897968595},
 'VNM.28.3_1': {'lat': 20.57307558606602, 'lon': 105.84690033357153},
 'VNM.28.4_1': {'lat': 20.55877906235136, 'lon': 106.09137286484369},
 'VNM.28.5_1': {'lat': 20.545807358514928, 'lon': 105.9323825672596},
 'VNM.28.6_1': {'lat': 20.4537547469135, 'lon': 105.91951296054403},
 'VNM.27.3_1': {'lat': 21.036053318917627, 'lon': 105.82643556962704},
 'VNM.27.4_1': {'lat': 21.141261635515555, 'lon': 105.38291683235605},
 'VNM.27.2_1': {'lat': 21.071029524565844, 'lon': 105.76140143522692},
 'VNM.27.5_1': {'lat': 21.030723215473234, 'lon': 105.79173389812519},
 'VNM.27.8_1': {'lat': 21.113835644963938, 'lon': 105.67684518504777},
 'VNM.27.9_1': {'lat': 21.1367748303897, 'lon': 105.84020159521363},
 'VNM.27.7_1': {'lat': 21.015613227410185, 'lon': 105.82519940986224},
 'VNM.27.10_1': {'lat': 21.029036242022695, 'lon': 105.95055474818221},
 'VNM.27.12_1': {'lat': 21.005504125671884, 'lon': 105.85781353346894},
 'VNM.27.13_1': {'lat': 21.024093932238465, 'lon': 105.69927347897188},
 'VNM.27.14_1': {'lat': 21.028804276471984, 'lon': 105.85369883702813},
 'VNM.27.15_1': {'lat': 20.97436994219681, 'lon': 105.86325720385912},
 'VNM.27.16_1': {'lat': 21.041860739255107, 'lon': 105.89421126344347},
 'VNM.27.18_1': {'lat': 21.183399409964306, 'lon': 105.70616189403174},
 'VNM.27.19_1': {'lat': 21.01300912913894, 'lon': 105.76154707499927},
 'VNM.27.20_1': {'lat': 20.735766413989666, 'lon': 105.90092876826289},
 'VNM.27.21_1': {'lat': 21.117086465508667, 'lon': 105.58364459182391},
 'VNM.27.22_1': {'lat': 20.967647867619196, 'lon': 105.5979318693799},
 'VNM.27.23_1': {'lat': 21.27271618806807, 'lon': 105.83004979976629},
 'VNM.27.24_1': {'lat': 21.096871543299834, 'lon': 105.47962367044728},
 'VNM.27.25_1': {'lat': 21.07088004803283, 'lon': 105.81993841410615},
 'VNM.27.26_1': {'lat': 21.018855764994875, 'lon': 105.53083114344872},
 'VNM.27.29_1': {'lat': 20.99479742302002, 'lon': 105.81549899266142},
 'VNM.29.1_1': {'lat': 18.194506725937647, 'lon': 106.00575967689835},
 'VNM.29.2_1': {'lat': 18.44012175519265, 'lon': 105.73333379861121},
 'VNM.29.3_1': {'lat': 18.495233084728877, 'lon': 105.6062046172194},
 'VNM.29.5_1': {'lat': 18.355122100042305, 'lon': 105.90297903457902},
 'VNM.29.4_1': {'lat': 18.530892516879923, 'lon': 105.7089913847516},
 'VNM.29.6_1': {'lat': 18.17718300146895, 'lon': 105.6794276305807},
 'VNM.29.7_1': {'lat': 18.47812772032529, 'lon': 105.30642145179152},
 'VNM.29.10_1': {'lat': 18.46864745052706, 'lon': 105.864571286428},
 'VNM.29.12_1': {'lat': 18.339566308797846, 'lon': 105.87442806964438},
 'VNM.29.13_1': {'lat': 18.32479133391186, 'lon': 105.44677136900954},
 'VNM.22.1_1': {'lat': 20.87368604269143, 'lon': 106.18852135304273},
 'VNM.22.2_1': {'lat': 20.954604968243395, 'lon': 106.21508986309776},
 'VNM.22.3_1': {'lat': 21.134420792759, 'lon': 106.40089470890157},
 'VNM.22.4_1': {'lat': 20.850670130932937, 'lon': 106.28855637894988},
 'VNM.22.5_1': {'lat': 20.939720041521248, 'lon': 106.32824487746714},
 'VNM.22.6_1': {'lat': 20.935980535202653, 'lon': 106.48872317803126},
 'VNM.22.7_1': {'lat': 21.01478851833068, 'lon': 106.50837588069307},
 'VNM.22.8_1': {'lat': 21.01472170745267, 'lon': 106.3368653657053},
 'VNM.22.9_1': {'lat': 20.74753101889215, 'lon': 106.33410180579055},
 'VNM.22.11_1': {'lat': 20.89505389947492, 'lon': 106.43217508404855},
 'VNM.22.12_1': {'lat': 20.780451244728958, 'lon': 106.21594217675292},
 'VNM.22.10_1': {'lat': 20.80857926576364, 'lon': 106.40713582458346},
 'VNM.23.1_1': {'lat': 20.88048527601215, 'lon': 106.59146443128338},
 'VNM.23.2_1': {'lat': 20.803074662033712, 'lon': 106.56105945034113},
 'VNM.23.4_1': {'lat': 20.800240969708973, 'lon': 106.989597780119},
 'VNM.23.5_1': {'lat': 20.725455749589212, 'lon': 106.76022730397374},
 'VNM.23.6_1': {'lat': 20.781535555508576, 'lon': 106.71362127237661},
 'VNM.23.7_1': {'lat': 20.822197260952343, 'lon': 106.75672566101976},
 'VNM.23.8_1': {'lat': 20.87214157413891, 'lon': 106.64800411007919},
 'VNM.23.9_1': {'lat': 20.804428364295394, 'lon': 106.63909266734164},
 'VNM.23.10_1': {'lat': 20.73393535919466, 'lon': 106.67312666341839},
 'VNM.23.11_1': {'lat': 20.835922113694558, 'lon': 106.67904759452108},
 'VNM.23.12_1': {'lat': 20.85704110053765, 'lon': 106.70101385828531},
 'VNM.23.13_1': {'lat': 20.94743569346222, 'lon': 106.67549086247877},
 'VNM.23.14_1': {'lat': 20.69557256534961, 'lon': 106.59517033258028},
 'VNM.23.15_1': {'lat': 20.674632265107647, 'lon': 106.4941484654077},
 'VNM.24.2_1': {'lat': 9.922094033495451, 'lon': 105.81662305310144},
 'VNM.24.1_1': {'lat': 9.930186092084126, 'lon': 105.62910385513626},
 'VNM.24.4_1': {'lat': 9.648442684770036, 'lon': 105.47827806138093},
 'VNM.24.3_1': {'lat': 9.684019935638439, 'lon': 105.61341316903562},
 'VNM.24.5_1': {'lat': 9.831116897001118, 'lon': 105.82125356642413},
 'VNM.24.6_1': {'lat': 9.794514640458722, 'lon': 105.70648917891793},
 'VNM.24.7_1': {'lat': 9.748582583457399, 'lon': 105.42828610840087},
 'VNM.24.8_1': {'lat': 9.798515365917043, 'lon': 105.53717455669982},
 'VNM.25.1_1': {'lat': 10.733723409462975, 'lon': 106.5757112693471},
 'VNM.25.2_1': {'lat': 10.764573795231234, 'lon': 106.59747965098208},
 'VNM.25.3_1': {'lat': 10.811834707922861, 'lon': 106.71598939838942},
 'VNM.25.4_1': {'lat': 10.5105676877504, 'lon': 106.87455633147555},
 'VNM.25.5_1': {'lat': 11.009730499858652, 'lon': 106.51069366573911},
 'VNM.25.6_1': {'lat': 10.838305925577526, 'lon': 106.66728862236242},
 'VNM.25.7_1': {'lat': 10.885690163635678, 'lon': 106.58977316544174},
 'VNM.25.8_1': {'lat': 10.654165890094232, 'lon': 106.73044708840465},
 'VNM.25.9_1': {'lat': 10.800423834324496, 'lon': 106.6781308051629},
 'VNM.25.13_1': {'lat': 10.776049957206707, 'lon': 106.69732029300198},
 'VNM.25.10_1': {'lat': 10.77236263166765, 'lon': 106.66828813446253},
 'VNM.25.11_1': {'lat': 10.764127436417892, 'lon': 106.64763804132299},
 'VNM.25.12_1': {'lat': 10.864579134876607, 'lon': 106.65710668178201},
 'VNM.25.14_1': {'lat': 10.779164411649996, 'lon': 106.75641740832856},
 'VNM.25.15_1': {'lat': 10.78150474443508, 'lon': 106.68282363500406},
 'VNM.25.16_1': {'lat': 10.758541442506365, 'lon': 106.7057143337658},
 'VNM.25.17_1': {'lat': 10.754951797448783, 'lon': 106.66966583282714},
 'VNM.25.18_1': {'lat': 10.745741500173489, 'lon': 106.63535568567208},
 'VNM.25.19_1': {'lat': 10.736338075817534, 'lon': 106.72939021674962},
 'VNM.25.20_1': {'lat': 10.72524648739265, 'lon': 106.6417145128972},
 'VNM.25.21_1': {'lat': 10.8232427316654, 'lon': 106.82283965686753},
 'VNM.25.22_1': {'lat': 10.808977285690734, 'lon': 106.6523589259668},
 'VNM.25.23_1': {'lat': 10.792439494117586, 'lon': 106.62685798105822},
 'VNM.25.24_1': {'lat': 10.855608448837645, 'lon': 106.74521559257742},
 'VNM.30.2_1': {'lat': 20.909202194334352, 'lon': 105.09360180317766},
 'VNM.30.4_1': {'lat': 20.919802408291268, 'lon': 105.39410851532222},
 'VNM.30.6_1': {'lat': 20.48356082000636, 'lon': 105.4410707620902},
 'VNM.30.7_1': {'lat': 20.503473853146428, 'lon': 105.73329707615498},
 'VNM.30.10_1': {'lat': 20.60543069738318, 'lon': 105.23586399954752},
 'VNM.30.11_1': {'lat': 20.42193595256236, 'lon': 105.62692169080677},
 'VNM.31.1_1': {'lat': 20.813298588892845, 'lon': 106.10303503345581},
 'VNM.31.2_1': {'lat': 20.65777644787298, 'lon': 106.06398545714224},
 'VNM.31.3_1': {'lat': 20.82511017886929, 'lon': 105.97303165902551},
 'VNM.31.4_1': {'lat': 20.74621393020857, 'lon': 106.03274617440957},
 'VNM.31.5_1': {'lat': 20.931012265959396, 'lon': 106.09988793215655},
 'VNM.31.6_1': {'lat': 20.713574155538794, 'lon': 106.19070738917506},
 'VNM.31.7_1': {'lat': 20.683371475960616, 'lon': 106.13058879371017},
 'VNM.31.8_1': {'lat': 20.932468619503876, 'lon': 105.94892614894773},
 'VNM.31.9_1': {'lat': 20.977778652709944, 'lon': 106.04267499162522},
 'VNM.31.10_1': {'lat': 20.89145722200901, 'lon': 106.02768039870787},
 'VNM.33.1_1': {'lat': 9.82189134305548, 'lon': 105.04624295920364},
 'VNM.33.2_1': {'lat': 9.66078519276529, 'lon': 104.9377737470812},
 'VNM.33.3_1': {'lat': 9.94434253938821, 'lon': 105.16894304012247},
 'VNM.33.5_1': {'lat': 10.452028756976802, 'lon': 104.67255326147547},
 'VNM.33.4_1': {'lat': 9.911358353987175, 'lon': 105.36725436145832},
 'VNM.33.6_1': {'lat': 9.741238010255898, 'lon': 105.29547810087148},
 'VNM.33.7_1': {'lat': 10.38987727987213, 'lon': 104.5072332151789},
 'VNM.33.8_1': {'lat': 10.22178783432047, 'lon': 104.94104129940602},
 'VNM.33.10_1': {'lat': 10.292873060876367, 'lon': 104.65422078322271},
 'VNM.33.12_1': {'lat': 10.033412970613943, 'lon': 105.10862931137639},
 'VNM.33.13_1': {'lat': 10.091583047276695, 'lon': 105.2428713802304},
 'VNM.33.14_1': {'lat': 9.627110776786239, 'lon': 105.12641004119293},
 'VNM.33.15_1': {'lat': 9.539861138317361, 'lon': 105.23850131098114},
 'VNM.35.1_1': {'lat': 21.8262699110745, 'lon': 106.26602410175269},
 'VNM.35.2_1': {'lat': 22.056943307328723, 'lon': 106.3085045891051},
 'VNM.35.3_1': {'lat': 21.888473622526483, 'lon': 106.82414321932085},
 'VNM.35.4_1': {'lat': 21.66889992029641, 'lon': 106.61691020613308},
 'VNM.35.5_1': {'lat': 21.536422910007186, 'lon': 107.13436658194611},
 'VNM.35.6_1': {'lat': 21.56098367696176, 'lon': 106.34071485818613},
 'VNM.35.7_1': {'lat': 21.84980484698783, 'lon': 106.74330073930673},
 'VNM.35.8_1': {'lat': 21.688328830925055, 'lon': 106.94208815023626},
 'VNM.35.10_1': {'lat': 22.05615306627506, 'lon': 106.5846260079487},
 'VNM.35.11_1': {'lat': 21.83884313695012, 'lon': 106.53460443827348},
 'VNM.39.1_1': {'lat': 10.6918392583577, 'lon': 106.45107936150471},
 'VNM.39.2_1': {'lat': 10.53147319895411, 'lon': 106.60107267656078},
 'VNM.39.3_1': {'lat': 10.582793808912166, 'lon': 106.66865848293487},
 'VNM.39.4_1': {'lat': 10.45895474273421, 'lon': 106.49414656859763},
 'VNM.39.5_1': {'lat': 10.889066855350283, 'lon': 106.4091137715446},
 'VNM.39.6_1': {'lat': 10.86647999911014, 'lon': 106.25687163128751},
 'VNM.39.7_1': {'lat': 10.783936694361175, 'lon': 105.90895939749122},
 'VNM.39.8_1': {'lat': 10.753901597410978, 'lon': 106.01986807653154},
 'VNM.39.9_1': {'lat': 10.532590054761917, 'lon': 106.40271897577014},
 'VNM.39.10_1': {'lat': 10.831959555566364, 'lon': 105.68673651030059},
 'VNM.39.11_1': {'lat': 10.613863990175703, 'lon': 105.96203445578368},
 'VNM.39.12_1': {'lat': 10.533210776979717, 'lon': 106.50804701967988},
 'VNM.39.13_1': {'lat': 10.673966959890127, 'lon': 106.17520828366885},
 'VNM.39.14_1': {'lat': 10.660515339895142, 'lon': 106.33467882394308},
 'VNM.39.15_1': {'lat': 10.902587735400788, 'lon': 105.7802346280687},
 'VNM.40.1_1': {'lat': 20.249915837649464, 'lon': 106.46895278927414},
 'VNM.40.2_1': {'lat': 20.149989263323224, 'lon': 106.26927312934541},
 'VNM.40.3_1': {'lat': 20.4569570604492, 'lon': 106.13461068859391},
 'VNM.40.4_1': {'lat': 20.423719859807477, 'lon': 106.16939665154024},
 'VNM.40.5_1': {'lat': 20.33907060951831, 'lon': 106.21240169348056},
 'VNM.40.6_1': {'lat': 20.106988977754092, 'lon': 106.15647106887988},
 'VNM.40.7_1': {'lat': 20.247196147913257, 'lon': 106.24784966761479},
 'VNM.40.8_1': {'lat': 20.374485910806534, 'lon': 106.09583522304662},
 'VNM.40.9_1': {'lat': 20.30180058557385, 'lon': 106.3547654751005},
 'VNM.40.10_1': {'lat': 20.32205633968068, 'lon': 106.02431334271297},
 'VNM.41.1_1': {'lat': 18.95002832846517, 'lon': 105.05796203064723},
 'VNM.41.3_1': {'lat': 19.023673430278073, 'lon': 104.81875077622144},
 'VNM.41.4_1': {'lat': 19.00150968604149, 'lon': 105.57565829262005},
 'VNM.41.5_1': {'lat': 18.897628449433586, 'lon': 105.34443045649168},
 'VNM.41.6_1': {'lat': 19.265429551268276, 'lon': 105.70598120820475},
 'VNM.41.9_1': {'lat': 18.68006866766806, 'lon': 105.52138439596929},
 'VNM.41.10_1': {'lat': 18.811345714892692, 'lon': 105.60424893726285},
 'VNM.41.11_1': {'lat': 19.357158503603028, 'lon': 105.42503690146077},
 'VNM.41.12_1': {'lat': 19.705730824735475, 'lon': 104.89484899030262},
 'VNM.41.13_1': {'lat': 19.54023350209133, 'lon': 105.08183597338791},
 'VNM.41.14_1': {'lat': 19.322439783607564, 'lon': 105.15598108272276},
 'VNM.41.15_1': {'lat': 19.20855163517931, 'lon': 105.60441505504754},
 'VNM.41.16_1': {'lat': 19.111589287084207, 'lon': 105.21798276457946},
 'VNM.41.17_1': {'lat': 19.289646940451014, 'lon': 105.44566358033649},
 'VNM.41.18_1': {'lat': 18.73954199175892, 'lon': 105.23930859635699},
 'VNM.41.21_1': {'lat': 19.022982740648736, 'lon': 105.44160433434034},
 'VNM.42.1_1': {'lat': 20.341614245747397, 'lon': 105.86187174409822},
 'VNM.42.2_1': {'lat': 20.25379420596277, 'lon': 105.92842799324788},
 'VNM.42.3_1': {'lat': 20.057369648481362, 'lon': 106.08949192775229},
 'VNM.42.4_1': {'lat': 20.291171934076612, 'lon': 105.74399427790215},
 'VNM.42.5_1': {'lat': 20.246487750349473, 'lon': 105.97190141175145},
 'VNM.42.6_1': {'lat': 20.156536077838517, 'lon': 105.8917438965759},
 'VNM.42.7_1': {'lat': 20.18960998797833, 'lon': 106.08766414636425},
 'VNM.42.8_1': {'lat': 20.128996979058215, 'lon': 105.99584242292606},
 'VNM.44.1_1': {'lat': 21.402337332638137, 'lon': 105.09395288997722},
 'VNM.44.2_1': {'lat': 21.61830078849463, 'lon': 105.15349321003752},

In [126]:
list(dist_dict.keys()).index('VNM.44.10_1')

290

In [127]:
list(dist_dict.keys())[290:]

['VNM.44.10_1',
 'VNM.44.11_1',
 'VNM.44.12_1',
 'VNM.44.13_1',
 'VNM.46.8_1',
 'VNM.49.1_1',
 'VNM.49.2_1',
 'VNM.49.3_1',
 'VNM.49.4_1',
 'VNM.49.5_1',
 'VNM.49.6_1',
 'VNM.49.7_1',
 'VNM.49.8_1',
 'VNM.49.9_1',
 'VNM.49.10_1',
 'VNM.49.11_1',
 'VNM.49.12_1',
 'VNM.49.13_1',
 'VNM.49.14_1',
 'VNM.51.1_1',
 'VNM.51.3_1',
 'VNM.51.4_1',
 'VNM.51.5_1',
 'VNM.51.6_1',
 'VNM.51.7_1',
 'VNM.51.8_1',
 'VNM.51.9_1',
 'VNM.51.10_1',
 'VNM.51.11_1',
 'VNM.53.9_1',
 'VNM.55.1_1',
 'VNM.55.2_1',
 'VNM.55.3_1',
 'VNM.55.4_1',
 'VNM.55.5_1',
 'VNM.55.6_1',
 'VNM.55.7_1',
 'VNM.55.8_1',
 'VNM.56.1_1',
 'VNM.56.2_1',
 'VNM.56.3_1',
 'VNM.56.4_1',
 'VNM.56.5_1',
 'VNM.56.6_1',
 'VNM.56.7_1',
 'VNM.56.8_1',
 'VNM.56.9_1',
 'VNM.57.2_1',
 'VNM.57.1_1',
 'VNM.57.3_1',
 'VNM.57.4_1',
 'VNM.57.6_1',
 'VNM.57.5_1',
 'VNM.57.7_1',
 'VNM.57.8_1',
 'VNM.57.11_1',
 'VNM.57.10_1',
 'VNM.57.12_1',
 'VNM.57.13_1',
 'VNM.57.14_1',
 'VNM.57.16_1',
 'VNM.57.17_1',
 'VNM.57.15_1',
 'VNM.57.18_1',
 'VNM.57.19_1',
 'VNM.57.21_1',
 'VNM.57.22_1',
 'VNM.57.20_1',
 'VNM.57.23_1',
 'VNM.57.24_1',
 'VNM.57.25_1',
 'VNM.57.26_1',
 'VNM.57.27_1',
 'VNM.58.1_1',
 'VNM.58.3_1',
 'VNM.58.2_1',
 'VNM.58.5_1',
 'VNM.58.4_1',
 'VNM.58.8_1',
 'VNM.58.6_1',
 'VNM.58.7_1',
 'VNM.58.9_1',
 'VNM.58.10_1',
 'VNM.58.11_1',
 'VNM.59.3_1',
 'VNM.59.1_1',
 'VNM.59.9_1',
 'VNM.60.1_1',
 'VNM.60.2_1',
 'VNM.60.5_1',
 'VNM.60.6_1',
 'VNM.60.7_1',
 'VNM.61.1_1',
 'VNM.61.2_1',
 'VNM.61.3_1',
 'VNM.61.4_1',
 'VNM.61.5_1',
 'VNM.61.6_1',
 'VNM.61.7_1',
 'VNM.61.8_1',
 'VNM.62.1_1',
 'VNM.62.2_1',
 'VNM.62.3_1',
 'VNM.62.4_1',
 'VNM.62.5_1',
 'VNM.62.6_1',
 'VNM.62.7_1',
 'VNM.62.8_1',
 'VNM.62.9_1',
 'VNM.63.9_1']

In [128]:
api_key = 'ac31e02046794bd3f959fbc98fc25231'

def create_json(location_name:str, start: int, end: int) -> dict:
    global dist_dict
    lat = dist_dict[location_name]['lat']
    lon = dist_dict[location_name]['lon']
    hist_url = f'http://api.openweathermap.org/data/2.5/air_pollution/history?lat={lat}&lon={lon}&start={start}&end={end}&appid={api_key}'
    r = requests.get(hist_url)
    json_out = r.json()
    json_out['name'] = location_name

    return json_out

for location_name in list(dist_dict.keys())[290:]:

    print(location_name)
    
    # 6 month extraction to avoid request timeout from OWM
    # loc_dict = {}

    for year in list(range(2018, 2023, 1)):
        print('     ', year)
        # January - June 
        start_1 = int(time.mktime(datetime(year, 1, 1).timetuple()))
        end_1 = int(time.mktime(datetime(year, 6, 30).timetuple()))

        # Dumps json file
        json_1 = create_json(location_name, start_1, end_1)
        with open(f"owm_pollution/HN_{location_name}_16_{year}.json", "w") as outfile: 
            json.dump(json_1, outfile)

        # July - December 
        start_2 = int(time.mktime(datetime(year, 7, 1).timetuple()))
        end_2 = int(time.mktime(datetime(year, 12, 31).timetuple()))

        # Dumps json file
        json_2 = create_json(location_name, start_2, end_2)
        with open(f"owm_pollution/HN_{location_name}_712_{year}.json", "w") as outfile: 
            json.dump(json_2, outfile)

        # full_json = json_1 | json_2
    
    # loc_dict.update(full_json)

VNM.44.10_1
      2018
      2019
      2020
      2021
      2022
VNM.44.11_1
      2018
      2019
      2020
      2021
      2022
VNM.44.12_1
      2018
      2019
      2020
      2021
      2022
VNM.44.13_1
      2018
      2019
      2020
      2021
      2022
VNM.46.8_1
      2018
      2019
      2020
      2021
      2022
VNM.49.1_1
      2018
      2019
      2020
      2021
      2022
VNM.49.2_1
      2018
      2019
      2020
      2021
      2022
VNM.49.3_1
      2018
      2019
      2020
      2021
      2022
VNM.49.4_1
      2018
      2019
      2020
      2021
      2022
VNM.49.5_1
      2018
      2019
      2020
      2021
      2022
VNM.49.6_1
      2018
      2019
      2020
      2021
      2022
VNM.49.7_1
      2018
      2019
      2020
      2021
      2022
VNM.49.8_1
      2018
      2019
      2020
      2021
      2022
VNM.49.9_1
      2018
      2019
      2020
      2021
      2022
VNM.49.10_1
      2018
      2019
      2020
      2021
      2022
VNM.49.11_1
      2018
      2019
      2020
      2021
      2022
VNM.49.12_1
      2018
      2019
      2020
      2021
      2022
VNM.49.13_1
      2018
      2019
      2020
      2021
      2022
VNM.49.14_1
      2018
      2019
      2020
      2021
      2022
VNM.51.1_1
      2018
      2019
      2020
      2021
      2022
VNM.51.3_1
      2018
      2019
      2020
      2021
      2022
VNM.51.4_1
      2018
      2019
      2020
      2021
      2022
VNM.51.5_1
      2018
      2019
      2020
      2021
      2022
VNM.51.6_1
      2018
      2019
      2020
      2021
      2022
VNM.51.7_1
      2018
      2019
      2020
      2021
      2022
VNM.51.8_1
      2018
      2019
      2020
      2021
      2022
VNM.51.9_1
      2018
      2019
      2020
      2021
      2022
VNM.51.10_1
      2018
      2019
      2020
      2021
      2022
VNM.51.11_1
      2018
      2019
      2020
      2021
      2022
VNM.53.9_1
      2018
      2019
      2020
      2021
      2022
VNM.55.1_1
      2018
      2019
      2020
      2021
      2022
VNM.55.2_1
      2018
      2019
      2020
      2021
      2022
VNM.55.3_1
      2018
      2019
      2020
      2021
      2022
VNM.55.4_1
      2018
      2019
      2020
      2021
      2022
VNM.55.5_1
      2018
      2019
      2020
      2021
      2022
VNM.55.6_1
      2018
      2019
      2020
      2021
      2022
VNM.55.7_1
      2018
      2019
      2020
      2021
      2022
VNM.55.8_1
      2018
      2019
      2020
      2021
      2022
VNM.56.1_1
      2018
      2019
      2020
      2021
      2022
VNM.56.2_1
      2018
      2019
      2020
      2021
      2022
VNM.56.3_1
      2018
      2019
      2020
      2021
      2022
VNM.56.4_1
      2018
      2019
      2020
      2021
      2022
VNM.56.5_1
      2018
      2019
      2020
      2021
      2022
VNM.56.6_1
      2018
      2019
      2020
      2021
      2022
VNM.56.7_1
      2018
      2019
      2020
      2021
      2022
VNM.56.8_1
      2018
      2019
      2020
      2021
      2022
VNM.56.9_1
      2018
      2019
      2020
      2021
      2022
VNM.57.2_1
      2018
      2019
      2020
      2021
      2022
VNM.57.1_1
      2018
      2019
      2020
      2021
      2022
VNM.57.3_1
      2018
      2019
      2020
      2021
      2022
VNM.57.4_1
      2018
      2019
      2020
      2021
      2022
VNM.57.6_1
      2018
      2019
      2020
      2021
      2022
VNM.57.5_1
      2018
      2019
      2020
      2021
      2022
VNM.57.7_1
      2018
      2019
      2020
      2021
      2022
VNM.57.8_1
      2018
      2019
      2020
      2021
      2022
VNM.57.11_1
      2018
      2019
      2020
      2021
      2022
VNM.57.10_1
      2018
      2019
      2020
      2021
      2022
VNM.57.12_1
      2018
      2019
      2020
      2021
      2022
VNM.57.13_1
      2018
      2019
      2020
      2021
      2022
VNM.57.14_1
      2018
      2019
      2020
      2021
      2022
VNM.57.16_1
      2018
      2019
      2020
      2021
      2022
VNM.57.17_1
      2018
      2019
      2020
      2021
      2022
VNM.57.15_1
      2018
      2019
      2020
      2021
      2022
VNM.57.18_1
      2018
      2019
      2020
      2021
      2022
VNM.57.19_1
      2018
      2019
      2020
      2021
      2022
VNM.57.21_1
      2018
      2019
      2020
      2021
      2022
VNM.57.22_1
      2018
      2019
      2020
      2021
      2022
VNM.57.20_1
      2018
      2019
      2020
      2021
      2022
VNM.57.23_1
      2018
      2019
      2020
      2021
      2022
VNM.57.24_1
      2018
      2019
      2020
      2021
      2022
VNM.57.25_1
      2018
      2019
      2020
      2021
      2022
VNM.57.26_1
      2018
      2019
      2020
      2021
      2022
VNM.57.27_1
      2018
      2019
      2020
      2021
      2022
VNM.58.1_1
      2018
      2019
      2020
      2021
      2022
VNM.58.3_1
      2018
      2019
      2020
      2021
      2022
VNM.58.2_1
      2018
      2019
      2020
      2021
      2022
VNM.58.5_1
      2018
      2019
      2020
      2021
      2022
VNM.58.4_1
      2018
      2019
      2020
      2021
      2022
VNM.58.8_1
      2018
      2019
      2020
      2021
      2022
VNM.58.6_1
      2018
      2019
      2020
      2021
      2022
VNM.58.7_1
      2018
      2019
      2020
      2021
      2022
VNM.58.9_1
      2018
      2019
      2020
      2021
      2022
VNM.58.10_1
      2018
      2019
      2020
      2021
      2022
VNM.58.11_1
      2018
      2019
      2020
      2021
      2022
VNM.59.3_1
      2018
      2019
      2020
      2021
      2022
VNM.59.1_1
      2018
      2019
      2020
      2021
      2022
VNM.59.9_1
      2018
      2019
      2020
      2021
      2022
VNM.60.1_1
      2018
      2019
      2020
      2021
      2022
VNM.60.2_1
      2018
      2019
      2020
      2021
      2022
VNM.60.5_1
      2018
      2019
      2020
      2021
      2022
VNM.60.6_1
      2018
      2019
      2020
      2021
      2022
VNM.60.7_1
      2018
      2019
      2020
      2021
      2022
VNM.61.1_1
      2018
      2019
      2020
      2021
      2022
VNM.61.2_1
      2018
      2019
      2020
      2021
      2022
VNM.61.3_1
      2018
      2019
      2020
      2021
      2022
VNM.61.4_1
      2018
      2019
      2020
      2021
      2022
VNM.61.5_1
      2018
      2019
      2020
      2021
      2022
VNM.61.6_1
      2018
      2019
      2020
      2021
      2022
VNM.61.7_1
      2018
      2019
      2020
      2021
      2022
VNM.61.8_1
      2018
      2019
      2020
      2021
      2022
VNM.62.1_1
      2018
      2019
      2020
      2021
      2022
VNM.62.2_1
      2018
      2019
      2020
      2021
      2022
VNM.62.3_1
      2018
      2019
      2020
      2021
      2022
VNM.62.4_1
      2018
      2019
      2020
      2021
      2022
VNM.62.5_1
      2018
      2019
      2020
      2021
      2022
VNM.62.6_1
      2018
      2019
      2020
      2021
      2022
VNM.62.7_1
      2018
      2019
      2020
      2021
      2022
VNM.62.8_1
      2018
      2019
      2020
      2021
      2022
VNM.62.9_1
      2018
      2019
      2020
      2021
      2022
VNM.63.9_1
      2018
      2019
      2020
      2021
      2022

In [7]:
paths = glob.glob('D:\Work\ADB\SAR\datasets\owm/*.json')
paths.sort()
paths

<>:1: SyntaxWarning: invalid escape sequence '\W'
<>:1: SyntaxWarning: invalid escape sequence '\W'
C:\Users\sonle\AppData\Local\Temp\ipykernel_36436\440931412.py:1: SyntaxWarning: invalid escape sequence '\W'
  paths = glob.glob('D:\Work\ADB\SAR\datasets\owm/*.json')

['D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.10064_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.13927_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.14197_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.15185_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.18778_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.19856_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.2309_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.24258_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.25874_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.30186_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.31893_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.34678_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.34768_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.35307_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.37373_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.41955_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.42583_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.47165_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.48782_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.4995_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.51746_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.53363_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.56058_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.57136_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.57764_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.72587_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.93159_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.96303_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.97111_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.98279_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_106.10406_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_106.22623_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_106.23162_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_106.25228_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_106.57748_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_106.57927_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.14466_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.15005_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.15454_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.15903_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.15993_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.16173_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.1806_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.18149_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.19676_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.19766_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.2309_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.24617_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.28929_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.30636_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.32971_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.34947_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.36924_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.37283_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.40966_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.42493_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.42583_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.46716_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.48243_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.50758_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.52734_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.53632_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.55609_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.59831_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.72946_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.89385_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.91901_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.97381_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.98009_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_106.05914_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_106.08699_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_106.12652_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_106.57837_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_106.58915_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.10154_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.10693_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.10963_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.13567_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.15275_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.18329_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.18508_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.20215_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.20844_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.21652_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.2327_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.2336_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.24437_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.29108_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.31714_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.33151_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.34499_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.34858_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.35666_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.36205_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.37463_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.40697_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.40787_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.4438_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.46356_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.48332_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.50039_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.52016_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.52285_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.5507_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.56776_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.56956_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.58304_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.58483_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.60011_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.60729_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.88667_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.88757_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_106.08969_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_106.58017_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_106.59814_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.124_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.13208_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.15723_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.15993_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.1752_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.18239_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.18508_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.19407_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.20395_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.21114_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.24437_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.27851_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.33421_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.3387_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.34139_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.34768_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.35756_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.36295_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.36924_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.38002_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.38092_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.40247_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.41325_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.42583_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.42763_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.44469_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.47973_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.48332_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.56866_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.58663_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.61268_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.88397_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.93967_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.95135_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.96841_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.98189_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_106.06004_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_106.10406_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_106.22713_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_106.60173_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004088_105.16173_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004088_105.18239_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004088_105.21383_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004088_105.21563_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004088_105.32971_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004088_105.34229_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004088_105.37103_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004088_105.41325_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004088_105.43122_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004088_105.43391_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004088_105.43571_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004088_105.49141_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004088_105.51028_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004088_105.5507_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004088_105.57764_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004088_105.58035_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004088_105.6037_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004088_105.61538_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004088_105.88577_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004088_105.94057_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004088_105.96931_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004088_106.08699_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004088_106.11035_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004088_106.11574_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004088_106.22893_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004088_106.59634_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.10873_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.10963_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.11142_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.12669_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.13119_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.14197_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.14645_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.21024_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.22012_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.23539_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.24527_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.27312_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.28659_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.31714_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.31893_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.34139_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.35756_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.40517_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.42493_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.46895_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.51117_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.51746_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.52644_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.52824_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.548_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.58753_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.59292_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.95763_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.96572_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.97111_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.97829_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_106.03848_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_106.08879_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_106.09328_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_106.11933_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_106.13101_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_106.15617_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_106.15886_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_106.24061_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_106.29091_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_106.59544_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_105.15813_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_105.16532_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_105.19497_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_105.21563_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_105.23449_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_105.24527_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_105.28839_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_105.3387_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_105.34049_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_105.34319_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_105.40877_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_105.40966_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_105.41865_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_105.45997_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_105.46806_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_105.47075_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_105.47794_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_105.495_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_105.50219_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_105.51746_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_105.52734_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_105.5471_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_105.88667_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_105.93697_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_105.93967_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_105.95943_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_105.97021_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_105.97291_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_106.11035_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_106.11124_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_106.16065_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_106.16605_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_106.23701_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_106.48585_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_106.58646_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_106.59454_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_106.60083_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.11053_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.14107_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.20036_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.24886_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.25066_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.25426_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.25695_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.26144_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.26683_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.2812_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.29558_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.30367_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.30636_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.33061_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.3899_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.42403_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.43122_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.45009_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.50668_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.50938_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.5516_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.55519_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.55788_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.56238_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.57047_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.57136_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.57316_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.58304_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.58573_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.58663_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.60729_2022.json',

In [8]:
dfs = []

for path in tqdm(paths):
    with open(path, 'r') as f:
        d = json.load(f)
    dates = []
    pm25s = []

    for i in range(len(d['list'])):
        dates.append(d['list'][i]['dt'])
        pm25s.append(d['list'][i]['components']['pm2_5'])


    lat_l = path.rindex('\\')
    lat_r = path.index('_')
    lon_r = path.rindex('_')

    df_p = pd.DataFrame({'lat': path[lat_l+1:lat_r],
                        'lon': path[lat_r+1:lon_r],
                        'dt': dates,
                        'pm25': pm25s})
    df_p['dt'] = pd.to_datetime(df_p['dt'], unit='s')
    df_p['dt'] = df_p['dt'].dt.tz_localize('UTC').dt.tz_convert('Asia/Saigon')
    df_p['month'] = df_p['dt'].dt.month
    df_p = df_p.groupby(['lat', 'lon', 'month']).agg({'pm25': 'mean'}).reset_index()

    df_p['lat'] = df_p['lat'].astype('float64')
    df_p['lon'] = df_p['lon'].astype('float64')

    dfs.append(df_p)

  0%|          | 0/95911 [00:00<?, ?it/s]

In [9]:
df_all = pd.concat(dfs, axis=0).reset_index(drop=True)
df_all

               lat        lon  month       pm25
0        10.000495  105.10064      1  30.825722
1        10.000495  105.10064      2  24.829599
2        10.000495  105.10064      3  25.805780
3        10.000495  105.10064      4  35.481083
4        10.000495  105.10064      5  15.307204
...            ...        ...    ...        ...
1150927   9.999597  105.98009      8  30.194556
1150928   9.999597  105.98009      9  21.298597
1150929   9.999597  105.98009     10  56.314220
1150930   9.999597  105.98009     11  42.334556
1150931   9.999597  105.98009     12  62.719615

[1150932 rows x 4 columns]

In [11]:
df

,id,lon,lat,sample_1,sample_2,sample_3,sample_4,sample_5
0,518582,105.34409,9.759747,0,0,0,0,1
1,306736,105.16891,10.705672,0,0,0,0,1
2,515851,105.34139,9.483066,0,0,0,0,1
3,398571,105.24168,10.394855,0,0,0,0,1
4,807982,105.56148,10.331973,0,0,0,0,1
...,...,...,...,...,...,...,...,...
49391,664345,105.46446,9.630389,0,0,0,1,0
49392,1527014,106.54154,10.091225,0,0,0,1,0
49393,967309,105.67736,9.376165,0,0,1,0,0
49394,578874,105.39799,10.594281,0,1,0,0,0
49395,1438174,106.23431,10.621231,0,0,1,0,0

In [12]:
df_out = pd.merge(df, df_all, on=['lat', 'lon'], how='inner')
df_out

,id,lon,lat,sample_1,sample_2,sample_3,sample_4,sample_5,month,pm25
0,518582,105.34409,9.759747,0,0,0,0,1,1,23.142625
1,518582,105.34409,9.759747,0,0,0,0,1,2,19.527114
2,518582,105.34409,9.759747,0,0,0,0,1,3,22.524194
3,518582,105.34409,9.759747,0,0,0,0,1,4,33.457819
4,518582,105.34409,9.759747,0,0,0,0,1,5,17.502218
...,...,...,...,...,...,...,...,...,...,...
592747,1438174,106.23431,10.621231,0,0,1,0,0,8,22.739489
592748,1438174,106.23431,10.621231,0,0,1,0,0,9,21.350389
592749,1438174,106.23431,10.621231,0,0,1,0,0,10,36.954409
592750,1438174,106.23431,10.621231,0,0,1,0,0,11,44.703403
592751,1438174,106.23431,10.621231,0,0,1,0,0,12,53.147581

In [13]:
df_out.to_csv('datasets/owm_pm25_2022_2nd_batch.csv', index=False)