In [1]:
import os
import glob
import json
import sys
import time
import requests
from datetime import datetime

import pandas as pd
import numpy as np
import rasterio
import rasterstats
import rioxarray as rxr
import geopandas as gpd
from osgeo import gdal
from shapely.geometry import box
from tqdm.notebook import tqdm_notebook as tqdm

In [2]:
dir = os.getcwd()

In [4]:
# df = pd.read_csv(os.path.join(dir, 'datasets/South_VNM_3per_sampleID.csv'))
df = pd.read_csv(os.path.join(dir, 'datasets\South_sample_5x10000.csv'))
df

<>:2: SyntaxWarning: invalid escape sequence '\S'
<>:2: SyntaxWarning: invalid escape sequence '\S'
C:\Users\sonle\AppData\Local\Temp\ipykernel_14488\445749686.py:2: SyntaxWarning: invalid escape sequence '\S'
  df = pd.read_csv(os.path.join(dir, 'datasets\South_sample_5x10000.csv'))

,id,lon,lat,sample_1,sample_2,sample_3,sample_4,sample_5
0,518582,105.34409,9.759747,0,0,0,0,1
1,306736,105.16891,10.705672,0,0,0,0,1
2,515851,105.34139,9.483066,0,0,0,0,1
3,398571,105.24168,10.394855,0,0,0,0,1
4,807982,105.56148,10.331973,0,0,0,0,1
...,...,...,...,...,...,...,...,...
49391,664345,105.46446,9.630389,0,0,0,1,0
49392,1527014,106.54154,10.091225,0,0,0,1,0
49393,967309,105.67736,9.376165,0,0,1,0,0
49394,578874,105.39799,10.594281,0,1,0,0,0
49395,1438174,106.23431,10.621231,0,0,1,0,0

In [7]:
sample = df[df['sample_1'] == 1]
sample

,id,lon,lat,sample_1,sample_2,sample_3,sample_4,sample_5
406,1151467,105.83366,9.403115,1,0,0,0,1
494,817216,105.56776,10.552958,1,0,0,0,1
570,1413880,106.17323,10.038224,1,0,0,0,1
769,582335,105.40158,9.667220,1,0,1,0,1
1165,988863,105.69353,9.341131,1,0,0,0,1
...,...,...,...,...,...,...,...,...
49375,879837,105.61268,10.075055,1,0,0,0,0
49380,755053,105.52554,9.334844,1,0,0,0,0
49381,1412410,106.16874,10.920370,1,0,0,0,0
49382,426142,105.26414,10.153209,1,0,0,0,0
49388,1261189,105.94057,10.447856,1,0,0,0,0

In [14]:
api_key = '73f784c939b7c0017b23be2e72b482cc'

lats = sample['lat'].to_list()
lons = sample['lon'].to_list()

def create_json(lat:str, lon:str, start: int, end: int) -> dict:
    hist_url = f'http://api.openweathermap.org/data/2.5/air_pollution/history?lat={lat}&lon={lon}&start={start}&end={end}&appid={api_key}'
    r = requests.get(hist_url)
    json_out = r.json()

    return json_out

for i in tqdm(range(len(lats))[299:]):

    print(lats[i], lons[i])
    

    start_1 = int(time.mktime(datetime(2022, 1, 1).timetuple()))
    end_1 = int(time.mktime(datetime(2022, 12, 31).timetuple()))
   
    # Dumps json file
    json_1 = create_json(lats[i], lons[i], start_1, end_1)
    with open(f"datasets/owm/{lats[i]}_{lons[i]}_2022.json", "w") as outfile: 
        json.dump(json_1, outfile)

  0%|          | 0/9701 [00:00<?, ?it/s]

10.08853 105.36744
10.802691 106.20287
10.065173 106.64934
10.017563 105.46895
10.685011 105.94057
10.455043 105.80133
9.6061344 105.389
9.0985861 104.98296
10.302329 104.92547
9.8747311 105.36115
10.269989 105.42044
9.9843254 105.26414
10.879946 105.47884
9.8648491 105.51746
10.359821 104.83295
10.76586 105.65849
10.075055 105.43122
9.8370018 105.37643
10.592484 105.10154
10.329278 105.13029
9.6124229 105.88487
10.29065 106.71312
9.6501522 105.88307
10.907793 105.61538
10.215192 105.00812
10.42989 104.67484
10.370601 104.78623
9.6896782 105.97201
10.769453 105.2273
9.7687292 105.56328
10.863776 105.26144
10.175667 105.36744
9.6779995 105.46895
10.040021 105.56507
9.7893906 105.96123
10.441567 106.55502
10.432585 104.62543
10.319397 104.95422
10.561942 105.0701
10.680519 105.03416
10.948217 106.57298
10.862878 105.52016
10.42989 105.35217
10.236752 105.67646
10.439771 105.71599
9.6636267 105.93787
9.9861221 105.35397
10.181056 105.09615
10.367906 105.68993
10.912285 106.38434
10.07775 106.10586
10.347244 104.64429
10.378686 105.35487
10.822453 105.45188
10.543976 105.58394
10.60057 105.03147
10.833233 105.52734
10.036427 105.59292
10.49906 105.38002
9.493845 105.83097
10.609552 105.283
10.897912 105.83277
10.057089 105.548
10.310413 104.83295
10.72813 105.87948
10.481992 106.37086
10.625722 106.36547
9.8387985 105.82289
9.8953924 105.62885
10.174768 104.86079
9.7875938 105.25874
9.3078938 105.93159
9.6681185 105.9765
10.313108 105.02428
10.702977 106.21815
10.82425 106.23431
10.038224 105.36744
10.332871 105.23988
10.927556 105.73575
10.399347 105.47794
10.299634 104.74132
9.4417429 105.59023
10.172972 104.99734
9.7983742 105.58124
10.806284 106.2945
10.349041 105.02698
10.594281 105.29737
10.004088 105.51028
10.652672 106.50201
10.737113 105.95673
10.654469 106.36098
10.305024 105.72318
10.709266 106.25857
9.4489298 105.60819
10.597875 106.3493
10.266397 105.78696
10.332871 105.61807
10.611349 105.12939
10.449653 105.16891
10.508942 105.77977
10.300532 106.65024
10.901505 106.16245
9.0671453 104.92817
10.814368 105.08268
10.887132 105.70071
9.582778 105.19497
10.72274 106.16155
9.7094412 105.19048
10.455043 104.72245
10.871861 105.73755
10.863776 105.0701
9.9430027 105.31803
9.1327219 104.94703
9.1506882 105.04675
10.825149 105.23988
9.4165897 105.52914
10.594281 105.4977
10.72274 105.88577
10.494568 105.99716
10.828742 105.74923
9.1138573 105.00452
10.954506 105.62885
10.067868 105.48962
10.776639 105.80133
10.952709 106.53705
10.321194 106.60622
10.832335 106.19749
10.609552 105.05842
9.960969 105.44919
10.105597 106.14089
9.5944567 105.71689
10.476602 105.15185
10.103801 105.98009
9.753458 105.48422
10.100208 106.55771
10.064276 105.11591
10.35533 104.79881
9.7678308 105.52914
10.431686 106.23342
10.307718 105.07549
9.7956791 105.07279
10.132547 105.9756
9.9780369 105.41685
10.21609 105.93697
9.5836763 105.64413
10.239447 105.24168
10.307718 105.70611
10.905996 105.57405
9.9564772 105.99267
9.3339453 105.74114
10.876352 105.70521
10.524213 105.16532
10.610451 105.71689
10.57901 106.39781
10.731724 105.18508
9.4372511 105.56866
10.026546 105.23808
10.101107 105.57316
10.335567 106.77779
9.8405952 105.37643
10.546671 105.09795
10.926658 105.71239
10.417314 105.73755
10.997624 105.78246
10.438872 104.68472
9.5118113 105.71239
10.033732 105.53363
11.947145 106.63856
10.679622 105.10963
10.348143 104.67215
9.960969 105.40966
10.41911 105.49321
9.4399462 105.65311
10.692198 105.75552
10.673333 105.08986
9.6824913 105.52016
10.463127 106.00435
11.988466 106.81912
10.683214 105.97111
10.811673 105.36025
10.729927 106.00435
10.712859 105.45997
10.398449 106.62868
10.335567 106.71132
9.4677935 105.52375
10.093021 106.57568
10.33916 106.60981
9.4516239 105.55429
10.322092 105.0135
10.389465 106.53436
9.7220173 105.59831
10.269092 105.42853
9.6303892 105.98458
10.398449 104.70628
10.906895 105.4474
9.8244247 105.26234
10.218785 105.23629
10.916777 105.60909
9.4731836 105.63873
9.8486795 105.77078
10.469416 105.20305
10.77125 105.91901
10.323889 106.6691
9.9133587 105.47075
9.3222666 105.63873
10.683214 105.98638
10.915878 106.20647
10.42989 105.15723
10.710164 106.30528
10.566434 106.10855
10.601468 105.84804
10.380483 104.78803
10.486484 106.63496
10.376889 105.04225
9.3716745 105.5462
10.652672 105.46985
9.3941317 105.69263
10.843115 105.68185
10.553857 105.42943
10.50984 105.37373
10.425398 104.70628
10.279871 105.00542
10.384974 105.23
9.9690542 105.23898
10.411025 105.47434
10.862878 105.14915
10.210701 105.08537
9.4291668 105.50668
9.7705259 105.08807
10.387669 105.03956
10.170277 106.07442
9.9358158 105.35037
9.704051 105.66299
10.649977 105.95853
10.146022 106.69335
10.590688 105.95494
9.6124229 105.93248
10.615841 106.45081
10.683214 106.18671
10.226871 105.1752
10.456839 104.77814
9.9250364 105.15095
10.96798 106.28103
10.498161 105.19497
9.9771385 105.41415
10.198124 105.9217
9.4776754 105.5462
10.025648 105.1222
10.705672 105.93967
10.727232 105.37643
10.437974 104.98566
9.8504763 105.11951
10.023851 105.48962
10.911386 105.15544
9.7543564 105.442
9.2459097 105.61358
9.5872698 105.85253
10.486484 104.73772
10.336465 105.19497
10.625722 106.07172
10.126259 105.12041
10.421804 104.74311
9.5917616 105.45458
10.869165 105.14556
10.859284 105.51207
9.375267 105.49321
10.448754 104.58591
10.313108 106.64484
9.1821299 104.8572
10.579908 105.25605
10.396652 104.95961
10.84042 105.32433
10.042716 105.25156
10.826047 105.45818
10.635604 105.57495
9.4498272 105.8193
10.65357 105.77618
10.492772 105.67197
10.372397 105.17879
10.476602 105.10693
9.7768145 105.63245
9.9888172 105.54261
10.121767 105.56956
9.3186731 105.74114
9.3096905 105.64502
10.763165 106.10676
9.7795095 105.28839
9.7902889 105.30096
9.5639133 105.93248
10.480195 105.85343
10.503551 105.89296
10.910488 105.64233
10.859284 105.69712
10.19004 106.02142
10.08853 106.13461
10.407432 106.62328
10.399347 104.88684
10.808979 105.40337
10.705672 105.70341
10.643688 105.32792
10.941929 105.65849
9.3330469 105.65221
10.700282 105.41146
9.6097279 105.46535
10.660757 105.88128
10.208006 105.99357
9.563015 105.51028
10.403838 105.91721
10.106496 105.96662
10.536789 106.64484
10.001393 105.46716
10.49906 106.10496
10.676028 105.43481
10.005885 105.23449
10.646383 105.74564
10.543077 106.5622
9.6609316 105.82828
10.032834 105.68993
10.821555 105.70611
9.4318609 105.48153
10.279871 104.67664
10.891623 105.39169
9.6995592 105.64053
10.109191 106.15617
10.513433 105.6046
10.397551 105.93967
10.556552 105.63424
10.437077 104.82396
10.933845 105.75462
9.7426786 105.32433
9.7642384 105.91721
10.319397 105.30096
10.067868 105.73215
10.521518 105.70161
9.0824165 104.97578
9.8244247 105.22282
10.32838 105.57764
10.649078 105.31174
10.613146 105.98548
10.861081 105.68993
10.458635 104.60297
10.786521 106.10855
9.1129599 104.85001
10.76586 106.89548
10.25921 104.66766
10.542179 106.50201
10.497263 104.60747
10.611349 106.01782
10.922167 106.1894
9.335742 104.8581
10.656265 105.07639
10.806284 105.14017
10.65357 105.25156
10.443364 105.79145
10.92037 106.34301
9.9852238 105.21114
10.085835 105.48602
10.102902 105.19766
9.9717484 105.40337
10.585299 105.548
10.928454 105.74474
10.821555 105.64771
9.4067087 105.68095
10.483788 105.8175
9.4112005 105.74833
9.1587734 104.83025
10.505348 106.68437
10.956303 105.61179
9.7130337 105.08178
10.965285 105.77168
9.7220173 105.55339
10.069665 105.90194
10.031037 105.48243
10.437077 105.29378
10.764063 105.5516
9.7561531 105.18149
10.234056 104.79252
10.176565 105.00632
10.278074 104.71706
10.956303 106.27384
9.3312502 105.5498
9.3123856 105.78336
10.729029 105.47165
10.384974 104.87786
9.6375751 105.92979
9.8432894 105.57764
9.7130337 105.87679
10.730825 105.73396
10.730825 105.75552
9.9951048 105.58124
10.889827 106.26216
10.464025 105.8193
10.618536 105.63245
10.660757 105.15364
10.804487 105.75012
10.995829 106.20737
10.917675 106.36098
10.384075 106.53705
10.093021 105.42313
9.7489662 105.85882
10.642791 105.0719
9.8944941 105.58124
10.9042 106.57927
10.792809 106.18491
10.201717 105.93877
10.808081 105.92709
10.401143 106.70413
10.515229 105.13747
10.500856 105.35307
10.038224 105.27671
9.2800465 105.53453
10.388567 104.70988
10.609552 105.71779
10.48289 105.26414
10.645485 105.27671
10.3176 106.66461
10.672435 105.96392
10.606857 105.31893
10.028342 105.95943
10.21609 104.96769
10.140632 105.50039
9.8145437 105.32702
10.128056 106.15257
9.1767397 104.93715
10.820657 105.76
9.9969015 105.45547
10.374194 105.24707
9.6501522 105.41865
10.071462 106.02591
10.740706 105.71599
11.957026 106.79037
10.692198 105.39619
10.609552 105.48962
10.039123 105.06022
10.416415 105.22282
10.436178 104.63082
9.3617926 105.52465
10.702977 105.39529
10.643688 106.24869
9.6537457 105.79863
9.8298149 105.73755
10.81886 105.90284
10.471212 105.20844
10.344549 105.13478
10.195429 105.98907
10.22148 104.83654
10.844013 105.56328
10.089428 105.07639
9.7471704 105.68455
9.9079685 105.14735
10.367007 105.79863
10.524213 106.04657
9.9699526 105.54351
10.140632 105.40247
9.3285551 105.95763
10.157701 106.58736
10.271786 105.37103
10.7443 105.68455
10.618536 105.72677
10.861081 106.21455
10.437077 104.74491
10.791911 106.882
10.407432 105.14915
10.474806 105.98907
9.6788979 105.44469
9.6321859 105.70521
10.433483 104.65867
10.444263 105.98728
10.591586 106.29271
10.788318 105.09076
10.949116 105.58035
10.733521 106.29271
10.802691 105.83636
9.8612556 105.62885
10.453246 106.09238
10.252023 104.93176
10.532297 105.1231
10.279871 106.74456
10.879946 105.57226
10.9042 106.24689
10.011274 105.29378
10.33377 105.12759
9.7247124 105.63694
10.464924 104.70448
10.411025 106.59903
10.393059 105.07459
10.431686 104.76288
10.161293 106.11035
10.810776 105.86781
9.8387985 105.63963
10.804487 105.94506
10.487382 105.18239
10.855691 105.62077
10.894319 105.74384
10.843115 105.45997
9.5270824 105.74923
10.478398 104.76288
10.816165 105.11232
10.32838 105.09615
10.025648 105.40427
9.9681559 105.4429
10.178361 105.36115
10.915878 105.45368
9.3096905 105.33151
9.6465588 105.4968
10.752385 105.50668
10.662553 105.83546
10.570925 106.65024
10.280769 105.39888
10.280769 105.0162
9.8873072 105.56687
10.452348 104.63891
10.956303 106.57029
10.585299 106.04388
10.305923 104.80869
10.236752 105.46356
10.764961 105.15275
10.172073 105.80312
10.258311 104.63801
10.791911 106.0331
10.475703 105.4438
9.6627283 105.7645
10.72274 105.30007
10.366109 105.62077
10.478398 105.0692
10.466721 105.16263
10.803589 105.14286
10.390364 105.79953
10.667943 105.47794
10.50445 105.89206
10.196327 105.54172
10.342753 106.6655
9.3034019 105.51476
9.1138573 105.51387
10.674232 105.61179
9.743577 105.76
10.77125 105.83277
10.381381 106.57478
10.523314 105.1743
10.183751 105.32971
10.272684 105.03416
10.453246 105.27492
10.559247 106.01603
10.439771 105.25874
10.172073 104.87965
10.449653 104.57603
10.092123 105.19138
10.303227 104.84283
10.160395 105.03237
10.679622 105.40697
10.602366 106.03399
10.298736 105.00362
10.937438 105.77438
10.040919 105.52375
10.614044 105.57854
10.354431 105.11501
10.185548 106.14987
10.672435 106.17683
10.800894 106.34301
10.416415 105.93248
10.916777 105.58304
10.382278 105.34678
10.897912 105.37643
10.466721 105.97021
9.3833523 105.69712
9.3968267 105.7106
10.105597 105.13029
9.0671453 104.89583
10.720943 105.42224
10.848504 106.46519
10.459534 104.72874
10.323889 106.76432
10.541281 106.36098
9.6779995 105.69802
9.6097279 105.36744
10.378686 105.22461
10.665248 106.05466
9.582778 105.82648
10.505348 106.63856
10.70118 105.08986
10.445161 106.71671
10.709266 105.54531
9.4031153 105.442
9.5297775 105.65939
10.521518 105.94057
10.712859 106.19928
10.952709 106.17143
9.5971518 105.63424
10.596078 106.00076
10.915878 105.50219
10.262803 105.14645
9.634881 105.61358
10.08853 105.09975
10.684113 106.04388
10.549366 105.55968
10.207108 105.36924
10.805386 105.46356
10.268193 105.78965
10.276278 105.70701
10.569128 105.62616
10.257413 104.75299
9.7786112 105.19227
9.6600332 105.1806
9.8558664 105.58214
10.577213 106.67899
10.665248 105.62077
10.144225 105.35487
10.33916 105.31624
10.615841 105.67197
10.16848 105.63604
9.6294909 105.36834
10.234056 104.87427
10.485585 105.95584
10.72813 105.74294
10.31221 105.02159
10.926658 106.28372
9.4471331 105.60191
10.643688 106.02411
9.7965775 105.98997
10.767656 105.4474
10.257413 104.93625
10.510738 106.15796
10.716453 106.11304
9.7076445 105.17161
10.580807 105.87409
10.781131 106.08879
10.272684 104.98386
10.694893 105.90374
10.666146 105.60909
10.917675 106.15706
10.967082 105.77887
10.758673 105.52375
10.225972 105.29648
10.941031 105.53992
10.440669 104.62723
10.296041 105.73215
10.643688 106.41129
10.784724 105.38092
10.820657 105.69712
9.2944193 105.51476
9.5899649 105.65311
10.496365 105.22282
10.346346 104.86079
10.433483 104.82127
10.892522 105.48962
10.974269 106.16695
9.7265091 105.55609
9.7157288 105.87679
10.472111 105.3378
10.65896 105.61089
9.3375378 105.96751
9.6690168 105.42403
10.766758 105.56148
10.025648 105.47075
10.145123 105.98907
10.956303 106.352
10.642791 105.00003
10.300532 105.07639
10.349041 106.5658
10.796402 105.52195
10.942827 106.1894
10.577213 105.73215
9.8145437 105.97919
10.472111 104.87247
10.149615 105.54261
10.954506 106.16784
10.705672 105.30815
10.117276 105.80582
10.473907 105.33511
10.291549 105.73396
9.7220173 105.29018
10.568231 105.79863
10.425398 106.26486
10.758673 105.29558
10.380483 105.56238
10.506247 105.21383
9.8783236 105.68095
10.869165 105.15095
10.202616 105.90463
10.441567 105.50309
9.9133587 105.21114
9.6052361 105.37014
9.7992725 105.45997
10.536789 105.65221
10.305024 105.32253
9.6276941 105.40158
10.830538 105.13119
10.764063 106.08789
10.471212 105.22012
10.528705 106.21186
10.345448 105.55609
10.093021 105.38541
10.569128 105.76989
10.201717 104.80151
9.9564772 105.26683
9.1659603 104.87517
10.376889 104.63441
10.378686 105.54531
10.269092 105.65041
10.739808 105.83726
10.323889 104.95961
10.91498 105.52465
9.6321859 105.45547
10.556552 105.11412
9.9897156 105.53184
9.8702393 105.34139
10.635604 105.85882
10.201717 105.15813
10.745198 105.39259
9.1417055 104.9075
10.888928 105.57675
10.895217 105.25605
10.446059 104.75658
9.7058477 105.7142
9.335742 105.59741
9.9430027 105.25785
10.746097 105.40607
9.5836763 105.62346
10.714656 105.6549
10.453246 104.78803
10.068767 106.64754
10.42989 106.64125
10.7443 105.99088
9.8091536 105.5516
10.590688 105.86781
10.155904 105.30995
10.447856 106.10586
10.599671 106.38972
9.5854731 105.80133
9.9277315 105.4977
10.471212 105.69263
10.356228 104.76108
9.3608942 105.52734
9.4192848 105.52375
9.8334084 105.9226
10.654469 106.7751
9.3222666 105.69802
9.4848623 105.69533
9.6663218 105.52554
9.9331217 105.44829
10.177463 105.42313
10.174768 105.87589
10.90959 106.42117
9.4866581 105.72048
9.3734713 105.60909
10.491874 104.82665
9.8307133 105.14017
9.9178495 105.60819
10.720943 105.25336
10.117276 106.10046
9.3483181 105.47704
9.6483555 105.78156
10.022953 105.43391
10.776639 105.84715
10.05619 105.43032
10.150514 105.84984
10.635604 105.67107
10.440669 105.36655
10.36072 105.64682
10.002292 105.52016
10.776639 105.28929
10.427195 104.78983
10.22148 105.00452
9.1982994 104.92368
10.314905 106.58915
10.552958 105.21832
10.570026 106.48135
10.426296 104.82307
10.331973 105.37373
9.7094412 105.53004
10.349939 104.91199
10.450551 104.85899
9.2917242 105.5516
10.959896 106.32504
10.153209 105.19676
10.062479 105.09885
9.7166271 105.53632
9.723814 105.57226
10.866471 106.38523
9.5342693 105.5507
10.101107 105.20036
9.6339827 105.83187
9.7920856 105.5516
10.780232 105.99177
10.200819 105.13119
10.415517 106.69425
10.101107 105.22192
10.641892 106.36098
10.073258 105.73126
10.040919 105.53902
10.49906 105.89745
10.410127 105.38002
10.688604 105.9244
10.617638 105.20574
10.702079 105.78516
10.301431 105.05663
9.5423536 105.65849
10.114581 105.14286
10.902404 105.6055
10.853894 106.49303
10.999421 105.70701
10.84581 106.23252
10.094818 106.1355
10.591586 105.5489
9.6438637 105.46266
10.431686 106.26935
10.017563 106.14179
10.144225 105.27222
10.895217 105.04765
10.527806 106.47507
9.3213682 105.59921
11.950737 106.86314
10.33916 105.39349
10.265498 105.41056
10.801792 105.41775
10.231362 104.94883
10.593383 105.59023
10.841318 106.00345
10.300532 106.7248
10.308617 104.85989
10.122665 105.12939
10.865573 106.86134
10.161293 105.72677
9.8711376 105.49231
9.135417 104.99015
10.545773 105.82648
9.9196463 105.37733
10.067868 105.68993
9.7247124 105.56417
10.630214 106.352
10.420906 105.27761
10.367007 105.12579
9.8900023 105.67826
10.905996 105.42853
10.040021 105.21652
10.211599 105.31264
10.729927 105.69623
10.746097 105.8166
10.340957 105.62077
10.081344 105.16711
9.026721 105.15903
10.875454 105.07729
9.802866 105.68993
10.127157 105.31264
10.591586 106.33942
9.1147556 104.87786
9.1426039 105.00183
9.6061344 105.39259
10.932048 105.5507
10.28616 105.12939
10.075953 105.52554
10.281668 105.29468
10.605959 105.47254
10.72813 105.39439
10.534094 105.34139
10.38677 105.27222
10.694893 105.71329
9.5163031 105.79145
10.638299 106.3529
10.628417 105.95404
10.678723 106.1373
9.2791481 105.55429
9.236927 104.86618
10.680519 106.21994
10.421804 106.2963
9.6717119 105.63245
10.269989 105.18958
10.650875 105.90913
10.085835 105.61627
10.875454 105.97829
10.340957 104.79342
10.541281 105.57136
10.082242 106.54962
10.261006 105.30007
9.1902142 104.96769
10.274481 105.07909
10.558349 105.07639
9.6663218 105.64861
9.7462721 105.53812
9.9385109 105.46716
10.624824 105.60191
10.852098 105.45458
9.6258974 105.36115
10.284363 105.3378
10.67513 105.03057
10.633807 105.69533
10.097513 105.82109
10.746097 105.85972
10.614943 105.66748
10.507145 105.40877
10.000495 105.24258
10.295142 105.00812
10.455043 104.75838
10.651773 105.25605
9.9061718 105.13208
10.703876 106.0331
10.434381 106.04567
9.6187105 105.78426
9.5639133 105.63424
9.1300278 104.8554
9.1830282 104.84642
10.861979 105.53094
9.5082178 105.66479
10.406533 104.73413
10.135242 106.00255
10.401143 106.53885
9.8855104 105.69892
9.7220173 105.16532
10.136141 105.32702
10.110089 105.40697
9.0024662 105.20215
9.624999 105.89925
10.608654 105.61717
10.037326 105.30995
10.442466 106.69515
9.8199339 105.55878
10.241243 105.46535
10.133446 106.52986
10.670638 106.96734
10.768555 106.24959
10.803589 105.53722
10.229566 105.10963
10.3176 105.20215
10.059784 105.2812
9.5180998 105.77977
10.399347 106.75534
10.941929 106.57748
10.837725 105.69083
9.8271198 105.57047
10.148717 105.98009
10.553857 105.80492
10.735317 106.27384
9.4579124 105.79055
10.239447 105.82828
10.197226 105.92081
10.969777 106.33493
9.1318245 104.89673
9.7327967 105.30456
10.526908 105.85522
10.969777 105.64233
10.762266 105.7663
10.769453 106.03848
10.148717 105.42673
10.676028 105.77438
10.146022 105.9747
10.536789 105.16891
10.667045 105.36924
10.32838 106.73557
10.692198 105.88487
9.3249617 105.63963
10.464025 104.7512
10.102004 105.33151
10.164886 106.05824
10.478398 105.77348
9.434556 105.79774
10.547569 106.47237
10.791013 106.16605
10.927556 105.40158
10.89881 105.46266
10.794605 105.36295
10.910488 105.94775
10.372397 105.25426
10.639197 105.86511
10.24304 104.99015
10.629315 106.22264
10.651773 105.17161
10.040021 106.11484
9.1300278 104.92547
10.43528 105.81211
10.585299 105.84355
10.412822 104.90302
10.799097 105.58394
10.782029 105.90913
9.0931969 104.8554
10.449653 104.86887
9.4498272 105.55698
10.140632 105.40068
10.464924 105.73845
9.872036 105.5516
9.5028286 105.53812
10.387669 105.02788
10.357126 105.68904
10.485585 104.90211
10.075953 105.11142
10.473907 105.89116
9.6214056 105.61448
9.105773 104.82755
9.7597466 105.22102
9.4812689 105.64861
10.170277 105.85074
9.6573381 105.64951
10.261006 105.09435
10.783826 106.8811
10.591586 106.61969
10.061581 105.34589
10.08314 106.59544
10.73891 105.54351
10.627519 105.89475
9.9376125 105.57226
10.063377 105.60909
9.3303518 105.48962
10.119971 105.33511
9.2468081 104.84013
9.4237766 105.7079
10.662553 105.51476
10.148717 105.59202
9.6788979 105.82289
10.616739 105.25785
10.464924 106.04118
10.72274 105.74653

In [12]:
json_1

{'cod': 401,
 'message': 'Invalid API key. Please see https://openweathermap.org/faq#error401 for more info.'}

In [44]:
with open('JAXA_subtiles.json', 'r') as json_file:
    jaxa_subtiles = json.load(json_file)

tiles = list(jaxa_subtiles.keys())[1:16]
tiles.extend(list(jaxa_subtiles.keys())[33:])

bbox = [jaxa_subtiles[tile] for tile in tiles]

bbox = [box(tile[0], tile[1], tile[2], tile[3]) for tile in bbox]

tiles_gdf = gpd.GeoDataFrame({'tile': tiles, 
                              'geometry': bbox})
tiles_gdf = tiles_gdf.set_crs(epsg=4326)
tiles_gdf.head()
tiles_gdf.to_file('chosen_tiles.json', driver='GeoJSON', index=False)

In [35]:
tiles_gdf.crs

In [38]:
dist_gdf = gpd.read_file('gadm41_VNM_2.json')
dist_gdf = dist_gdf.to_crs(tiles_gdf.crs)
dist_gdf.head()

,GID_2,GID_0,COUNTRY,GID_1,NAME_1,NL_NAME_1,NAME_2,VARNAME_2,NL_NAME_2,TYPE_2,ENGTYPE_2,CC_2,HASC_2,geometry
0,VNM.1.1_1,VNM,Vietnam,VNM.1_1,AnGiang,NA,AnPhú,AnPhu,NA,Huyện,District,NA,VN.TT.AL,"MULTIPOLYGON (((105.15660 10.82870, 105.16010 ..."
1,VNM.1.3_1,VNM,Vietnam,VNM.1_1,AnGiang,NA,ChâuĐốc,ChauDoc,NA,Thànhphố,City,NA,VN.KG.AB,"MULTIPOLYGON (((105.10500 10.63830, 105.08150 ..."
2,VNM.1.4_1,VNM,Vietnam,VNM.1_1,AnGiang,NA,ChâuPhú,ChauPhu,NA,Huyện,District,NA,VN.HP.AD,"MULTIPOLYGON (((105.18790 10.46030, 105.17980 ..."
3,VNM.1.5_1,VNM,Vietnam,VNM.1_1,AnGiang,NA,ChâuThành,ChauThanh,NA,Huyện,District,NA,VN.GL.AK,"MULTIPOLYGON (((105.37090 10.36220, 105.36820 ..."
4,VNM.1.2_1,VNM,Vietnam,VNM.1_1,AnGiang,NA,ChợMới,ChoMoi,NA,Huyện,District,NA,VN.BD.AL,"MULTIPOLYGON (((105.48720 10.53950, 105.48840 ..."

In [78]:
dist_geom = [geom for geom in dist_gdf.geometry]

intersects_geom = []
for geom in dist_geom:
    gdf = tiles_gdf.iloc[tiles_gdf.sindex.query(geom, predicate='intersects')]
    if len(gdf) > 0:
        intersects_geom.append(geom)

In [98]:
intersects_geom = list(set(intersects_geom))
dist_filtered = dist_gdf[dist_gdf.geometry.isin(intersects_geom)]

In [99]:
dist_filtered['lon'] = dist_filtered.centroid.x
dist_filtered['lat'] = dist_filtered.centroid.y
dist_filtered = dist_filtered[['GID_2', 'lat', 'lon']]
dist_dict = dist_filtered.set_index('GID_2').to_dict('index')
dist_dict

C:\Users\sonle\AppData\Local\Temp\ipykernel_28392\439494382.py:1: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  dist_filtered['lon'] = dist_filtered.centroid.x
c:\Users\sonle\anaconda3\envs\geospatial\Lib\site-packages\geopandas\geodataframe.py:1528: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
C:\Users\sonle\AppData\Local\Temp\ipykernel_28392\439494382.py:2: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  dist_filtered['lat'] = dist_filtered.centroid.y
c:\Users\sonle\anaconda3\envs\geospatial\Lib\site-packages\geopandas\geodataframe.py:1528: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

{'VNM.1.1_1': {'lat': 10.846404435922919, 'lon': 105.10074651097067},
 'VNM.1.3_1': {'lat': 10.674122054506455, 'lon': 105.08741946173457},
 'VNM.1.4_1': {'lat': 10.557603596145857, 'lon': 105.1797822230923},
 'VNM.1.5_1': {'lat': 10.421303385083814, 'lon': 105.26575383802694},
 'VNM.1.2_1': {'lat': 10.474944476027188, 'lon': 105.46144105444661},
 'VNM.1.6_1': {'lat': 10.371310030995655, 'lon': 105.42804673733518},
 'VNM.1.7_1': {'lat': 10.654870714342247, 'lon': 105.2757414511293},
 'VNM.1.9_1': {'lat': 10.800174081298888, 'lon': 105.18645918433309},
 'VNM.1.10_1': {'lat': 10.29683597866068, 'lon': 105.25556484274274},
 'VNM.1.8_1': {'lat': 10.547266352717338, 'lon': 105.01170710864969},
 'VNM.1.11_1': {'lat': 10.412558176021932, 'lon': 104.95909074038255},
 'VNM.7.5_1': {'lat': 10.5767716473971, 'lon': 107.08808543963191},
 'VNM.3.1_1': {'lat': 21.27452053546984, 'lon': 106.19658531724376},
 'VNM.3.2_1': {'lat': 21.324537974828658, 'lon': 105.96767319204977},
 'VNM.3.3_1': {'lat': 21.375265303697944, 'lon': 106.25353826985783},
 'VNM.3.4_1': {'lat': 21.282227696405553, 'lon': 106.46394219598645},
 'VNM.3.5_1': {'lat': 21.437154300988922, 'lon': 106.64073185958205},
 'VNM.3.6_1': {'lat': 21.309618967191483, 'lon': 106.85391325148451},
 'VNM.3.7_1': {'lat': 21.38631608931258, 'lon': 106.10326691816228},
 'VNM.3.8_1': {'lat': 21.27327270334532, 'lon': 106.09031285904712},
 'VNM.3.9_1': {'lat': 21.208523699429236, 'lon': 106.25254189799601},
 'VNM.3.10_1': {'lat': 21.519312093890722, 'lon': 106.13422514935968},
 'VNM.4.3_1': {'lat': 22.187349305492997, 'lon': 105.57411636155781},
 'VNM.4.4_1': {'lat': 21.98334234242168, 'lon': 105.84969344070213},
 'VNM.4.5_1': {'lat': 22.165469098406337, 'lon': 106.09068738441636},
 'VNM.2.1_1': {'lat': 9.270148882834658, 'lon': 105.76006522147505},
 'VNM.2.2_1': {'lat': 9.146158314072437, 'lon': 105.4222409150234},
 'VNM.2.3_1': {'lat': 9.264503862583094, 'lon': 105.3907122901949},
 'VNM.2.5_1': {'lat': 9.25431392452984, 'lon': 105.61397318689535},
 'VNM.2.4_1': {'lat': 9.515464238258716, 'lon': 105.40450752413687},
 'VNM.2.6_1': {'lat': 9.387981817925294, 'lon': 105.42085753929125},
 'VNM.2.7_1': {'lat': 9.357475102697261, 'lon': 105.70238858368658},
 'VNM.5.1_1': {'lat': 21.170589039947348, 'lon': 106.07411386095086},
 'VNM.5.2_1': {'lat': 21.075268930376033, 'lon': 106.20880132442728},
 'VNM.5.3_1': {'lat': 21.022603408852333, 'lon': 106.22604504678323},
 'VNM.5.4_1': {'lat': 21.140874221024465, 'lon': 106.17875776629543},
 'VNM.5.6_1': {'lat': 21.03719924238379, 'lon': 106.07648328889977},
 'VNM.5.7_1': {'lat': 21.114984571469147, 'lon': 106.03285665055495},
 'VNM.5.5_1': {'lat': 21.126532906506693, 'lon': 105.95949056728294},
 'VNM.5.8_1': {'lat': 21.208023556445625, 'lon': 105.97359109166437},
 'VNM.6.2_1': {'lat': 10.062987234466304, 'lon': 106.59568270453141},
 'VNM.6.1_1': {'lat': 10.238518959142223, 'lon': 106.37261842254041},
 'VNM.6.3_1': {'lat': 10.176887662077924, 'lon': 106.64783681966894},
 'VNM.6.5_1': {'lat': 10.290487750533405, 'lon': 106.30513518145705},
 'VNM.6.4_1': {'lat': 10.23006395544472, 'lon': 106.16019683386469},
 'VNM.6.6_1': {'lat': 10.156419439442443, 'lon': 106.46768846937505},
 'VNM.6.7_1': {'lat': 10.180149879460549, 'lon': 106.28972851332321},
 'VNM.6.8_1': {'lat': 10.06973704036731, 'lon': 106.35840373071349},
 'VNM.6.9_1': {'lat': 9.927977357469766, 'lon': 106.5509578334737},
 'VNM.9.5_1': {'lat': 10.90801193980671, 'lon': 106.77621999951585},
 'VNM.9.7_1': {'lat': 11.063133589193216, 'lon': 106.75220044352966},
 'VNM.9.8_1': {'lat': 11.021636950764123, 'lon': 106.66454602911246},
 'VNM.9.9_1': {'lat': 10.935455586456957, 'lon': 106.7102020124969},
 'VNM.10.1_1': {'lat': 11.683650597389345, 'lon': 106.58537732428621},
 'VNM.10.2_1': {'lat': 11.99308957051549, 'lon': 106.82156901643296},
 'VNM.10.4_1': {'lat': 12.024320359394432, 'lon': 107.04708861462404},
 'VNM.10.5_1': {'lat': 11.469439413915516, 'lon': 106.66534586208618},
 'VNM.10.6_1': {'lat': 11.497401643724752, 'lon': 106.9552793018042},
 'VNM.10.7_1': {'lat': 11.519676486536591, 'lon': 106.84710000840535},
 'VNM.10.8_1': {'lat': 11.618742720027555, 'lon': 106.61238195656014},
 'VNM.10.9_1': {'lat': 11.846661603516084, 'lon': 106.5724444322269},
 'VNM.10.10_1': {'lat': 11.73669558331828, 'lon': 106.90017256412447},
 'VNM.10.11_1': {'lat': 11.824561917670339, 'lon': 106.99672346278408},
 'VNM.13.1_1': {'lat': 9.171786016037853, 'lon': 105.19073109558677},
 'VNM.13.2_1': {'lat': 9.005028594256576, 'lon': 105.05302995528227},
 'VNM.13.3_1': {'lat': 8.96041418363201, 'lon': 105.2423355855557},
 'VNM.13.6_1': {'lat': 8.891565410982148, 'lon': 104.88339394137542},
 'VNM.13.7_1': {'lat': 9.368509322568412, 'lon': 105.13881361143413},
 'VNM.13.8_1': {'lat': 9.13192834756218, 'lon': 104.91928959026733},
 'VNM.13.9_1': {'lat': 9.371531806738366, 'lon': 104.94893377351754},
 'VNM.12.1_1': {'lat': 10.063414816290054, 'lon': 105.72317861524228},
 'VNM.12.3_1': {'lat': 9.991199348775488, 'lon': 105.78683461424293},
 'VNM.12.2_1': {'lat': 10.12691419840647, 'lon': 105.46076051545232},
 'VNM.12.4_1': {'lat': 10.030877117281348, 'lon': 105.76444699955354},
 'VNM.12.5_1': {'lat': 10.12679530380432, 'lon': 105.63323780922968},
 'VNM.12.6_1': {'lat': 9.998282609777052, 'lon': 105.66314802037238},
 'VNM.12.8_1': {'lat': 10.030653992080458, 'lon': 105.53856998513818},
 'VNM.12.7_1': {'lat': 10.24199393080869, 'lon': 105.54703486818579},
 'VNM.12.9_1': {'lat': 10.2139187404841, 'lon': 105.36901395571917},
 'VNM.17.1_1': {'lat': 10.917952995938165, 'lon': 106.88097653427613},
 'VNM.17.5_1': {'lat': 10.765147506866247, 'lon': 107.02316510061164},
 'VNM.17.6_1': {'lat': 10.692007807886403, 'lon': 106.88790814676024},
 'VNM.17.9_1': {'lat': 10.969338073247451, 'lon': 107.03513959654012},
 'VNM.17.10_1': {'lat': 11.23858163965196, 'lon': 107.05006999236262},
 'VNM.18.2_1': {'lat': 10.48883159364153, 'lon': 105.70496819049595},
 'VNM.18.1_1': {'lat': 10.455672707773553, 'lon': 105.61977824155866},
 'VNM.18.3_1': {'lat': 10.22665352476896, 'lon': 105.81841229854851},
 'VNM.18.5_1': {'lat': 10.815929994371904, 'lon': 105.2812002023233},
 'VNM.18.4_1': {'lat': 10.818532344234784, 'lon': 105.37948998891295},
 'VNM.18.7_1': {'lat': 10.248929712327993, 'lon': 105.65777601794854},
 'VNM.18.6_1': {'lat': 10.359199859121633, 'lon': 105.60279745498451},
 'VNM.18.8_1': {'lat': 10.317962379127176, 'lon': 105.74041430257842},
 'VNM.18.9_1': {'lat': 10.728753721368069, 'lon': 105.52461955439067},
 'VNM.18.10_1': {'lat': 10.873785852653786, 'lon': 105.48637883522451},
 'VNM.18.11_1': {'lat': 10.609085454501733, 'lon': 105.47360699389823},
 'VNM.18.12_1': {'lat': 10.561909003557268, 'lon': 105.7977731596112},
 'VNM.28.1_1': {'lat': 20.491748198834127, 'lon': 106.03757094645132},
 'VNM.28.2_1': {'lat': 20.637455701095547, 'lon': 105.97194897968595},
 'VNM.28.3_1': {'lat': 20.57307558606602, 'lon': 105.84690033357153},
 'VNM.28.4_1': {'lat': 20.55877906235136, 'lon': 106.09137286484369},
 'VNM.28.5_1': {'lat': 20.545807358514928, 'lon': 105.9323825672596},
 'VNM.28.6_1': {'lat': 20.4537547469135, 'lon': 105.91951296054403},
 'VNM.27.3_1': {'lat': 21.036053318917627, 'lon': 105.82643556962704},
 'VNM.27.4_1': {'lat': 21.141261635515555, 'lon': 105.38291683235605},
 'VNM.27.2_1': {'lat': 21.071029524565844, 'lon': 105.76140143522692},
 'VNM.27.5_1': {'lat': 21.030723215473234, 'lon': 105.79173389812519},
 'VNM.27.8_1': {'lat': 21.113835644963938, 'lon': 105.67684518504777},
 'VNM.27.9_1': {'lat': 21.1367748303897, 'lon': 105.84020159521363},
 'VNM.27.7_1': {'lat': 21.015613227410185, 'lon': 105.82519940986224},
 'VNM.27.10_1': {'lat': 21.029036242022695, 'lon': 105.95055474818221},
 'VNM.27.12_1': {'lat': 21.005504125671884, 'lon': 105.85781353346894},
 'VNM.27.13_1': {'lat': 21.024093932238465, 'lon': 105.69927347897188},
 'VNM.27.14_1': {'lat': 21.028804276471984, 'lon': 105.85369883702813},
 'VNM.27.15_1': {'lat': 20.97436994219681, 'lon': 105.86325720385912},
 'VNM.27.16_1': {'lat': 21.041860739255107, 'lon': 105.89421126344347},
 'VNM.27.18_1': {'lat': 21.183399409964306, 'lon': 105.70616189403174},
 'VNM.27.19_1': {'lat': 21.01300912913894, 'lon': 105.76154707499927},
 'VNM.27.20_1': {'lat': 20.735766413989666, 'lon': 105.90092876826289},
 'VNM.27.21_1': {'lat': 21.117086465508667, 'lon': 105.58364459182391},
 'VNM.27.22_1': {'lat': 20.967647867619196, 'lon': 105.5979318693799},
 'VNM.27.23_1': {'lat': 21.27271618806807, 'lon': 105.83004979976629},
 'VNM.27.24_1': {'lat': 21.096871543299834, 'lon': 105.47962367044728},
 'VNM.27.25_1': {'lat': 21.07088004803283, 'lon': 105.81993841410615},
 'VNM.27.26_1': {'lat': 21.018855764994875, 'lon': 105.53083114344872},
 'VNM.27.29_1': {'lat': 20.99479742302002, 'lon': 105.81549899266142},
 'VNM.29.1_1': {'lat': 18.194506725937647, 'lon': 106.00575967689835},
 'VNM.29.2_1': {'lat': 18.44012175519265, 'lon': 105.73333379861121},
 'VNM.29.3_1': {'lat': 18.495233084728877, 'lon': 105.6062046172194},
 'VNM.29.5_1': {'lat': 18.355122100042305, 'lon': 105.90297903457902},
 'VNM.29.4_1': {'lat': 18.530892516879923, 'lon': 105.7089913847516},
 'VNM.29.6_1': {'lat': 18.17718300146895, 'lon': 105.6794276305807},
 'VNM.29.7_1': {'lat': 18.47812772032529, 'lon': 105.30642145179152},
 'VNM.29.10_1': {'lat': 18.46864745052706, 'lon': 105.864571286428},
 'VNM.29.12_1': {'lat': 18.339566308797846, 'lon': 105.87442806964438},
 'VNM.29.13_1': {'lat': 18.32479133391186, 'lon': 105.44677136900954},
 'VNM.22.1_1': {'lat': 20.87368604269143, 'lon': 106.18852135304273},
 'VNM.22.2_1': {'lat': 20.954604968243395, 'lon': 106.21508986309776},
 'VNM.22.3_1': {'lat': 21.134420792759, 'lon': 106.40089470890157},
 'VNM.22.4_1': {'lat': 20.850670130932937, 'lon': 106.28855637894988},
 'VNM.22.5_1': {'lat': 20.939720041521248, 'lon': 106.32824487746714},
 'VNM.22.6_1': {'lat': 20.935980535202653, 'lon': 106.48872317803126},
 'VNM.22.7_1': {'lat': 21.01478851833068, 'lon': 106.50837588069307},
 'VNM.22.8_1': {'lat': 21.01472170745267, 'lon': 106.3368653657053},
 'VNM.22.9_1': {'lat': 20.74753101889215, 'lon': 106.33410180579055},
 'VNM.22.11_1': {'lat': 20.89505389947492, 'lon': 106.43217508404855},
 'VNM.22.12_1': {'lat': 20.780451244728958, 'lon': 106.21594217675292},
 'VNM.22.10_1': {'lat': 20.80857926576364, 'lon': 106.40713582458346},
 'VNM.23.1_1': {'lat': 20.88048527601215, 'lon': 106.59146443128338},
 'VNM.23.2_1': {'lat': 20.803074662033712, 'lon': 106.56105945034113},
 'VNM.23.4_1': {'lat': 20.800240969708973, 'lon': 106.989597780119},
 'VNM.23.5_1': {'lat': 20.725455749589212, 'lon': 106.76022730397374},
 'VNM.23.6_1': {'lat': 20.781535555508576, 'lon': 106.71362127237661},
 'VNM.23.7_1': {'lat': 20.822197260952343, 'lon': 106.75672566101976},
 'VNM.23.8_1': {'lat': 20.87214157413891, 'lon': 106.64800411007919},
 'VNM.23.9_1': {'lat': 20.804428364295394, 'lon': 106.63909266734164},
 'VNM.23.10_1': {'lat': 20.73393535919466, 'lon': 106.67312666341839},
 'VNM.23.11_1': {'lat': 20.835922113694558, 'lon': 106.67904759452108},
 'VNM.23.12_1': {'lat': 20.85704110053765, 'lon': 106.70101385828531},
 'VNM.23.13_1': {'lat': 20.94743569346222, 'lon': 106.67549086247877},
 'VNM.23.14_1': {'lat': 20.69557256534961, 'lon': 106.59517033258028},
 'VNM.23.15_1': {'lat': 20.674632265107647, 'lon': 106.4941484654077},
 'VNM.24.2_1': {'lat': 9.922094033495451, 'lon': 105.81662305310144},
 'VNM.24.1_1': {'lat': 9.930186092084126, 'lon': 105.62910385513626},
 'VNM.24.4_1': {'lat': 9.648442684770036, 'lon': 105.47827806138093},
 'VNM.24.3_1': {'lat': 9.684019935638439, 'lon': 105.61341316903562},
 'VNM.24.5_1': {'lat': 9.831116897001118, 'lon': 105.82125356642413},
 'VNM.24.6_1': {'lat': 9.794514640458722, 'lon': 105.70648917891793},
 'VNM.24.7_1': {'lat': 9.748582583457399, 'lon': 105.42828610840087},
 'VNM.24.8_1': {'lat': 9.798515365917043, 'lon': 105.53717455669982},
 'VNM.25.1_1': {'lat': 10.733723409462975, 'lon': 106.5757112693471},
 'VNM.25.2_1': {'lat': 10.764573795231234, 'lon': 106.59747965098208},
 'VNM.25.3_1': {'lat': 10.811834707922861, 'lon': 106.71598939838942},
 'VNM.25.4_1': {'lat': 10.5105676877504, 'lon': 106.87455633147555},
 'VNM.25.5_1': {'lat': 11.009730499858652, 'lon': 106.51069366573911},
 'VNM.25.6_1': {'lat': 10.838305925577526, 'lon': 106.66728862236242},
 'VNM.25.7_1': {'lat': 10.885690163635678, 'lon': 106.58977316544174},
 'VNM.25.8_1': {'lat': 10.654165890094232, 'lon': 106.73044708840465},
 'VNM.25.9_1': {'lat': 10.800423834324496, 'lon': 106.6781308051629},
 'VNM.25.13_1': {'lat': 10.776049957206707, 'lon': 106.69732029300198},
 'VNM.25.10_1': {'lat': 10.77236263166765, 'lon': 106.66828813446253},
 'VNM.25.11_1': {'lat': 10.764127436417892, 'lon': 106.64763804132299},
 'VNM.25.12_1': {'lat': 10.864579134876607, 'lon': 106.65710668178201},
 'VNM.25.14_1': {'lat': 10.779164411649996, 'lon': 106.75641740832856},
 'VNM.25.15_1': {'lat': 10.78150474443508, 'lon': 106.68282363500406},
 'VNM.25.16_1': {'lat': 10.758541442506365, 'lon': 106.7057143337658},
 'VNM.25.17_1': {'lat': 10.754951797448783, 'lon': 106.66966583282714},
 'VNM.25.18_1': {'lat': 10.745741500173489, 'lon': 106.63535568567208},
 'VNM.25.19_1': {'lat': 10.736338075817534, 'lon': 106.72939021674962},
 'VNM.25.20_1': {'lat': 10.72524648739265, 'lon': 106.6417145128972},
 'VNM.25.21_1': {'lat': 10.8232427316654, 'lon': 106.82283965686753},
 'VNM.25.22_1': {'lat': 10.808977285690734, 'lon': 106.6523589259668},
 'VNM.25.23_1': {'lat': 10.792439494117586, 'lon': 106.62685798105822},
 'VNM.25.24_1': {'lat': 10.855608448837645, 'lon': 106.74521559257742},
 'VNM.30.2_1': {'lat': 20.909202194334352, 'lon': 105.09360180317766},
 'VNM.30.4_1': {'lat': 20.919802408291268, 'lon': 105.39410851532222},
 'VNM.30.6_1': {'lat': 20.48356082000636, 'lon': 105.4410707620902},
 'VNM.30.7_1': {'lat': 20.503473853146428, 'lon': 105.73329707615498},
 'VNM.30.10_1': {'lat': 20.60543069738318, 'lon': 105.23586399954752},
 'VNM.30.11_1': {'lat': 20.42193595256236, 'lon': 105.62692169080677},
 'VNM.31.1_1': {'lat': 20.813298588892845, 'lon': 106.10303503345581},
 'VNM.31.2_1': {'lat': 20.65777644787298, 'lon': 106.06398545714224},
 'VNM.31.3_1': {'lat': 20.82511017886929, 'lon': 105.97303165902551},
 'VNM.31.4_1': {'lat': 20.74621393020857, 'lon': 106.03274617440957},
 'VNM.31.5_1': {'lat': 20.931012265959396, 'lon': 106.09988793215655},
 'VNM.31.6_1': {'lat': 20.713574155538794, 'lon': 106.19070738917506},
 'VNM.31.7_1': {'lat': 20.683371475960616, 'lon': 106.13058879371017},
 'VNM.31.8_1': {'lat': 20.932468619503876, 'lon': 105.94892614894773},
 'VNM.31.9_1': {'lat': 20.977778652709944, 'lon': 106.04267499162522},
 'VNM.31.10_1': {'lat': 20.89145722200901, 'lon': 106.02768039870787},
 'VNM.33.1_1': {'lat': 9.82189134305548, 'lon': 105.04624295920364},
 'VNM.33.2_1': {'lat': 9.66078519276529, 'lon': 104.9377737470812},
 'VNM.33.3_1': {'lat': 9.94434253938821, 'lon': 105.16894304012247},
 'VNM.33.5_1': {'lat': 10.452028756976802, 'lon': 104.67255326147547},
 'VNM.33.4_1': {'lat': 9.911358353987175, 'lon': 105.36725436145832},
 'VNM.33.6_1': {'lat': 9.741238010255898, 'lon': 105.29547810087148},
 'VNM.33.7_1': {'lat': 10.38987727987213, 'lon': 104.5072332151789},
 'VNM.33.8_1': {'lat': 10.22178783432047, 'lon': 104.94104129940602},
 'VNM.33.10_1': {'lat': 10.292873060876367, 'lon': 104.65422078322271},
 'VNM.33.12_1': {'lat': 10.033412970613943, 'lon': 105.10862931137639},
 'VNM.33.13_1': {'lat': 10.091583047276695, 'lon': 105.2428713802304},
 'VNM.33.14_1': {'lat': 9.627110776786239, 'lon': 105.12641004119293},
 'VNM.33.15_1': {'lat': 9.539861138317361, 'lon': 105.23850131098114},
 'VNM.35.1_1': {'lat': 21.8262699110745, 'lon': 106.26602410175269},
 'VNM.35.2_1': {'lat': 22.056943307328723, 'lon': 106.3085045891051},
 'VNM.35.3_1': {'lat': 21.888473622526483, 'lon': 106.82414321932085},
 'VNM.35.4_1': {'lat': 21.66889992029641, 'lon': 106.61691020613308},
 'VNM.35.5_1': {'lat': 21.536422910007186, 'lon': 107.13436658194611},
 'VNM.35.6_1': {'lat': 21.56098367696176, 'lon': 106.34071485818613},
 'VNM.35.7_1': {'lat': 21.84980484698783, 'lon': 106.74330073930673},
 'VNM.35.8_1': {'lat': 21.688328830925055, 'lon': 106.94208815023626},
 'VNM.35.10_1': {'lat': 22.05615306627506, 'lon': 106.5846260079487},
 'VNM.35.11_1': {'lat': 21.83884313695012, 'lon': 106.53460443827348},
 'VNM.39.1_1': {'lat': 10.6918392583577, 'lon': 106.45107936150471},
 'VNM.39.2_1': {'lat': 10.53147319895411, 'lon': 106.60107267656078},
 'VNM.39.3_1': {'lat': 10.582793808912166, 'lon': 106.66865848293487},
 'VNM.39.4_1': {'lat': 10.45895474273421, 'lon': 106.49414656859763},
 'VNM.39.5_1': {'lat': 10.889066855350283, 'lon': 106.4091137715446},
 'VNM.39.6_1': {'lat': 10.86647999911014, 'lon': 106.25687163128751},
 'VNM.39.7_1': {'lat': 10.783936694361175, 'lon': 105.90895939749122},
 'VNM.39.8_1': {'lat': 10.753901597410978, 'lon': 106.01986807653154},
 'VNM.39.9_1': {'lat': 10.532590054761917, 'lon': 106.40271897577014},
 'VNM.39.10_1': {'lat': 10.831959555566364, 'lon': 105.68673651030059},
 'VNM.39.11_1': {'lat': 10.613863990175703, 'lon': 105.96203445578368},
 'VNM.39.12_1': {'lat': 10.533210776979717, 'lon': 106.50804701967988},
 'VNM.39.13_1': {'lat': 10.673966959890127, 'lon': 106.17520828366885},
 'VNM.39.14_1': {'lat': 10.660515339895142, 'lon': 106.33467882394308},
 'VNM.39.15_1': {'lat': 10.902587735400788, 'lon': 105.7802346280687},
 'VNM.40.1_1': {'lat': 20.249915837649464, 'lon': 106.46895278927414},
 'VNM.40.2_1': {'lat': 20.149989263323224, 'lon': 106.26927312934541},
 'VNM.40.3_1': {'lat': 20.4569570604492, 'lon': 106.13461068859391},
 'VNM.40.4_1': {'lat': 20.423719859807477, 'lon': 106.16939665154024},
 'VNM.40.5_1': {'lat': 20.33907060951831, 'lon': 106.21240169348056},
 'VNM.40.6_1': {'lat': 20.106988977754092, 'lon': 106.15647106887988},
 'VNM.40.7_1': {'lat': 20.247196147913257, 'lon': 106.24784966761479},
 'VNM.40.8_1': {'lat': 20.374485910806534, 'lon': 106.09583522304662},
 'VNM.40.9_1': {'lat': 20.30180058557385, 'lon': 106.3547654751005},
 'VNM.40.10_1': {'lat': 20.32205633968068, 'lon': 106.02431334271297},
 'VNM.41.1_1': {'lat': 18.95002832846517, 'lon': 105.05796203064723},
 'VNM.41.3_1': {'lat': 19.023673430278073, 'lon': 104.81875077622144},
 'VNM.41.4_1': {'lat': 19.00150968604149, 'lon': 105.57565829262005},
 'VNM.41.5_1': {'lat': 18.897628449433586, 'lon': 105.34443045649168},
 'VNM.41.6_1': {'lat': 19.265429551268276, 'lon': 105.70598120820475},
 'VNM.41.9_1': {'lat': 18.68006866766806, 'lon': 105.52138439596929},
 'VNM.41.10_1': {'lat': 18.811345714892692, 'lon': 105.60424893726285},
 'VNM.41.11_1': {'lat': 19.357158503603028, 'lon': 105.42503690146077},
 'VNM.41.12_1': {'lat': 19.705730824735475, 'lon': 104.89484899030262},
 'VNM.41.13_1': {'lat': 19.54023350209133, 'lon': 105.08183597338791},
 'VNM.41.14_1': {'lat': 19.322439783607564, 'lon': 105.15598108272276},
 'VNM.41.15_1': {'lat': 19.20855163517931, 'lon': 105.60441505504754},
 'VNM.41.16_1': {'lat': 19.111589287084207, 'lon': 105.21798276457946},
 'VNM.41.17_1': {'lat': 19.289646940451014, 'lon': 105.44566358033649},
 'VNM.41.18_1': {'lat': 18.73954199175892, 'lon': 105.23930859635699},
 'VNM.41.21_1': {'lat': 19.022982740648736, 'lon': 105.44160433434034},
 'VNM.42.1_1': {'lat': 20.341614245747397, 'lon': 105.86187174409822},
 'VNM.42.2_1': {'lat': 20.25379420596277, 'lon': 105.92842799324788},
 'VNM.42.3_1': {'lat': 20.057369648481362, 'lon': 106.08949192775229},
 'VNM.42.4_1': {'lat': 20.291171934076612, 'lon': 105.74399427790215},
 'VNM.42.5_1': {'lat': 20.246487750349473, 'lon': 105.97190141175145},
 'VNM.42.6_1': {'lat': 20.156536077838517, 'lon': 105.8917438965759},
 'VNM.42.7_1': {'lat': 20.18960998797833, 'lon': 106.08766414636425},
 'VNM.42.8_1': {'lat': 20.128996979058215, 'lon': 105.99584242292606},
 'VNM.44.1_1': {'lat': 21.402337332638137, 'lon': 105.09395288997722},
 'VNM.44.2_1': {'lat': 21.61830078849463, 'lon': 105.15349321003752},

In [126]:
list(dist_dict.keys()).index('VNM.44.10_1')

290

In [127]:
list(dist_dict.keys())[290:]

['VNM.44.10_1',
 'VNM.44.11_1',
 'VNM.44.12_1',
 'VNM.44.13_1',
 'VNM.46.8_1',
 'VNM.49.1_1',
 'VNM.49.2_1',
 'VNM.49.3_1',
 'VNM.49.4_1',
 'VNM.49.5_1',
 'VNM.49.6_1',
 'VNM.49.7_1',
 'VNM.49.8_1',
 'VNM.49.9_1',
 'VNM.49.10_1',
 'VNM.49.11_1',
 'VNM.49.12_1',
 'VNM.49.13_1',
 'VNM.49.14_1',
 'VNM.51.1_1',
 'VNM.51.3_1',
 'VNM.51.4_1',
 'VNM.51.5_1',
 'VNM.51.6_1',
 'VNM.51.7_1',
 'VNM.51.8_1',
 'VNM.51.9_1',
 'VNM.51.10_1',
 'VNM.51.11_1',
 'VNM.53.9_1',
 'VNM.55.1_1',
 'VNM.55.2_1',
 'VNM.55.3_1',
 'VNM.55.4_1',
 'VNM.55.5_1',
 'VNM.55.6_1',
 'VNM.55.7_1',
 'VNM.55.8_1',
 'VNM.56.1_1',
 'VNM.56.2_1',
 'VNM.56.3_1',
 'VNM.56.4_1',
 'VNM.56.5_1',
 'VNM.56.6_1',
 'VNM.56.7_1',
 'VNM.56.8_1',
 'VNM.56.9_1',
 'VNM.57.2_1',
 'VNM.57.1_1',
 'VNM.57.3_1',
 'VNM.57.4_1',
 'VNM.57.6_1',
 'VNM.57.5_1',
 'VNM.57.7_1',
 'VNM.57.8_1',
 'VNM.57.11_1',
 'VNM.57.10_1',
 'VNM.57.12_1',
 'VNM.57.13_1',
 'VNM.57.14_1',
 'VNM.57.16_1',
 'VNM.57.17_1',
 'VNM.57.15_1',
 'VNM.57.18_1',
 'VNM.57.19_1',
 'VNM.57.21_1',
 'VNM.57.22_1',
 'VNM.57.20_1',
 'VNM.57.23_1',
 'VNM.57.24_1',
 'VNM.57.25_1',
 'VNM.57.26_1',
 'VNM.57.27_1',
 'VNM.58.1_1',
 'VNM.58.3_1',
 'VNM.58.2_1',
 'VNM.58.5_1',
 'VNM.58.4_1',
 'VNM.58.8_1',
 'VNM.58.6_1',
 'VNM.58.7_1',
 'VNM.58.9_1',
 'VNM.58.10_1',
 'VNM.58.11_1',
 'VNM.59.3_1',
 'VNM.59.1_1',
 'VNM.59.9_1',
 'VNM.60.1_1',
 'VNM.60.2_1',
 'VNM.60.5_1',
 'VNM.60.6_1',
 'VNM.60.7_1',
 'VNM.61.1_1',
 'VNM.61.2_1',
 'VNM.61.3_1',
 'VNM.61.4_1',
 'VNM.61.5_1',
 'VNM.61.6_1',
 'VNM.61.7_1',
 'VNM.61.8_1',
 'VNM.62.1_1',
 'VNM.62.2_1',
 'VNM.62.3_1',
 'VNM.62.4_1',
 'VNM.62.5_1',
 'VNM.62.6_1',
 'VNM.62.7_1',
 'VNM.62.8_1',
 'VNM.62.9_1',
 'VNM.63.9_1']

In [128]:
api_key = 'ac31e02046794bd3f959fbc98fc25231'

def create_json(location_name:str, start: int, end: int) -> dict:
    global dist_dict
    lat = dist_dict[location_name]['lat']
    lon = dist_dict[location_name]['lon']
    hist_url = f'http://api.openweathermap.org/data/2.5/air_pollution/history?lat={lat}&lon={lon}&start={start}&end={end}&appid={api_key}'
    r = requests.get(hist_url)
    json_out = r.json()
    json_out['name'] = location_name

    return json_out

for location_name in list(dist_dict.keys())[290:]:

    print(location_name)
    
    # 6 month extraction to avoid request timeout from OWM
    # loc_dict = {}

    for year in list(range(2018, 2023, 1)):
        print('     ', year)
        # January - June 
        start_1 = int(time.mktime(datetime(year, 1, 1).timetuple()))
        end_1 = int(time.mktime(datetime(year, 6, 30).timetuple()))

        # Dumps json file
        json_1 = create_json(location_name, start_1, end_1)
        with open(f"owm_pollution/HN_{location_name}_16_{year}.json", "w") as outfile: 
            json.dump(json_1, outfile)

        # July - December 
        start_2 = int(time.mktime(datetime(year, 7, 1).timetuple()))
        end_2 = int(time.mktime(datetime(year, 12, 31).timetuple()))

        # Dumps json file
        json_2 = create_json(location_name, start_2, end_2)
        with open(f"owm_pollution/HN_{location_name}_712_{year}.json", "w") as outfile: 
            json.dump(json_2, outfile)

        # full_json = json_1 | json_2
    
    # loc_dict.update(full_json)

VNM.44.10_1
      2018
      2019
      2020
      2021
      2022
VNM.44.11_1
      2018
      2019
      2020
      2021
      2022
VNM.44.12_1
      2018
      2019
      2020
      2021
      2022
VNM.44.13_1
      2018
      2019
      2020
      2021
      2022
VNM.46.8_1
      2018
      2019
      2020
      2021
      2022
VNM.49.1_1
      2018
      2019
      2020
      2021
      2022
VNM.49.2_1
      2018
      2019
      2020
      2021
      2022
VNM.49.3_1
      2018
      2019
      2020
      2021
      2022
VNM.49.4_1
      2018
      2019
      2020
      2021
      2022
VNM.49.5_1
      2018
      2019
      2020
      2021
      2022
VNM.49.6_1
      2018
      2019
      2020
      2021
      2022
VNM.49.7_1
      2018
      2019
      2020
      2021
      2022
VNM.49.8_1
      2018
      2019
      2020
      2021
      2022
VNM.49.9_1
      2018
      2019
      2020
      2021
      2022
VNM.49.10_1
      2018
      2019
      2020
      2021
      2022
VNM.49.11_1
      2018
      2019
      2020
      2021
      2022
VNM.49.12_1
      2018
      2019
      2020
      2021
      2022
VNM.49.13_1
      2018
      2019
      2020
      2021
      2022
VNM.49.14_1
      2018
      2019
      2020
      2021
      2022
VNM.51.1_1
      2018
      2019
      2020
      2021
      2022
VNM.51.3_1
      2018
      2019
      2020
      2021
      2022
VNM.51.4_1
      2018
      2019
      2020
      2021
      2022
VNM.51.5_1
      2018
      2019
      2020
      2021
      2022
VNM.51.6_1
      2018
      2019
      2020
      2021
      2022
VNM.51.7_1
      2018
      2019
      2020
      2021
      2022
VNM.51.8_1
      2018
      2019
      2020
      2021
      2022
VNM.51.9_1
      2018
      2019
      2020
      2021
      2022
VNM.51.10_1
      2018
      2019
      2020
      2021
      2022
VNM.51.11_1
      2018
      2019
      2020
      2021
      2022
VNM.53.9_1
      2018
      2019
      2020
      2021
      2022
VNM.55.1_1
      2018
      2019
      2020
      2021
      2022
VNM.55.2_1
      2018
      2019
      2020
      2021
      2022
VNM.55.3_1
      2018
      2019
      2020
      2021
      2022
VNM.55.4_1
      2018
      2019
      2020
      2021
      2022
VNM.55.5_1
      2018
      2019
      2020
      2021
      2022
VNM.55.6_1
      2018
      2019
      2020
      2021
      2022
VNM.55.7_1
      2018
      2019
      2020
      2021
      2022
VNM.55.8_1
      2018
      2019
      2020
      2021
      2022
VNM.56.1_1
      2018
      2019
      2020
      2021
      2022
VNM.56.2_1
      2018
      2019
      2020
      2021
      2022
VNM.56.3_1
      2018
      2019
      2020
      2021
      2022
VNM.56.4_1
      2018
      2019
      2020
      2021
      2022
VNM.56.5_1
      2018
      2019
      2020
      2021
      2022
VNM.56.6_1
      2018
      2019
      2020
      2021
      2022
VNM.56.7_1
      2018
      2019
      2020
      2021
      2022
VNM.56.8_1
      2018
      2019
      2020
      2021
      2022
VNM.56.9_1
      2018
      2019
      2020
      2021
      2022
VNM.57.2_1
      2018
      2019
      2020
      2021
      2022
VNM.57.1_1
      2018
      2019
      2020
      2021
      2022
VNM.57.3_1
      2018
      2019
      2020
      2021
      2022
VNM.57.4_1
      2018
      2019
      2020
      2021
      2022
VNM.57.6_1
      2018
      2019
      2020
      2021
      2022
VNM.57.5_1
      2018
      2019
      2020
      2021
      2022
VNM.57.7_1
      2018
      2019
      2020
      2021
      2022
VNM.57.8_1
      2018
      2019
      2020
      2021
      2022
VNM.57.11_1
      2018
      2019
      2020
      2021
      2022
VNM.57.10_1
      2018
      2019
      2020
      2021
      2022
VNM.57.12_1
      2018
      2019
      2020
      2021
      2022
VNM.57.13_1
      2018
      2019
      2020
      2021
      2022
VNM.57.14_1
      2018
      2019
      2020
      2021
      2022
VNM.57.16_1
      2018
      2019
      2020
      2021
      2022
VNM.57.17_1
      2018
      2019
      2020
      2021
      2022
VNM.57.15_1
      2018
      2019
      2020
      2021
      2022
VNM.57.18_1
      2018
      2019
      2020
      2021
      2022
VNM.57.19_1
      2018
      2019
      2020
      2021
      2022
VNM.57.21_1
      2018
      2019
      2020
      2021
      2022
VNM.57.22_1
      2018
      2019
      2020
      2021
      2022
VNM.57.20_1
      2018
      2019
      2020
      2021
      2022
VNM.57.23_1
      2018
      2019
      2020
      2021
      2022
VNM.57.24_1
      2018
      2019
      2020
      2021
      2022
VNM.57.25_1
      2018
      2019
      2020
      2021
      2022
VNM.57.26_1
      2018
      2019
      2020
      2021
      2022
VNM.57.27_1
      2018
      2019
      2020
      2021
      2022
VNM.58.1_1
      2018
      2019
      2020
      2021
      2022
VNM.58.3_1
      2018
      2019
      2020
      2021
      2022
VNM.58.2_1
      2018
      2019
      2020
      2021
      2022
VNM.58.5_1
      2018
      2019
      2020
      2021
      2022
VNM.58.4_1
      2018
      2019
      2020
      2021
      2022
VNM.58.8_1
      2018
      2019
      2020
      2021
      2022
VNM.58.6_1
      2018
      2019
      2020
      2021
      2022
VNM.58.7_1
      2018
      2019
      2020
      2021
      2022
VNM.58.9_1
      2018
      2019
      2020
      2021
      2022
VNM.58.10_1
      2018
      2019
      2020
      2021
      2022
VNM.58.11_1
      2018
      2019
      2020
      2021
      2022
VNM.59.3_1
      2018
      2019
      2020
      2021
      2022
VNM.59.1_1
      2018
      2019
      2020
      2021
      2022
VNM.59.9_1
      2018
      2019
      2020
      2021
      2022
VNM.60.1_1
      2018
      2019
      2020
      2021
      2022
VNM.60.2_1
      2018
      2019
      2020
      2021
      2022
VNM.60.5_1
      2018
      2019
      2020
      2021
      2022
VNM.60.6_1
      2018
      2019
      2020
      2021
      2022
VNM.60.7_1
      2018
      2019
      2020
      2021
      2022
VNM.61.1_1
      2018
      2019
      2020
      2021
      2022
VNM.61.2_1
      2018
      2019
      2020
      2021
      2022
VNM.61.3_1
      2018
      2019
      2020
      2021
      2022
VNM.61.4_1
      2018
      2019
      2020
      2021
      2022
VNM.61.5_1
      2018
      2019
      2020
      2021
      2022
VNM.61.6_1
      2018
      2019
      2020
      2021
      2022
VNM.61.7_1
      2018
      2019
      2020
      2021
      2022
VNM.61.8_1
      2018
      2019
      2020
      2021
      2022
VNM.62.1_1
      2018
      2019
      2020
      2021
      2022
VNM.62.2_1
      2018
      2019
      2020
      2021
      2022
VNM.62.3_1
      2018
      2019
      2020
      2021
      2022
VNM.62.4_1
      2018
      2019
      2020
      2021
      2022
VNM.62.5_1
      2018
      2019
      2020
      2021
      2022
VNM.62.6_1
      2018
      2019
      2020
      2021
      2022
VNM.62.7_1
      2018
      2019
      2020
      2021
      2022
VNM.62.8_1
      2018
      2019
      2020
      2021
      2022
VNM.62.9_1
      2018
      2019
      2020
      2021
      2022
VNM.63.9_1
      2018
      2019
      2020
      2021
      2022

In [112]:
len(loc_dict['list'])

4297

In [4]:
paths = glob.glob('D:\Work\ADB\SAR\datasets\owm/*.json')
paths.sort()
paths

<>:1: SyntaxWarning: invalid escape sequence '\W'
<>:1: SyntaxWarning: invalid escape sequence '\W'
C:\Users\sonle\AppData\Local\Temp\ipykernel_38680\440931412.py:1: SyntaxWarning: invalid escape sequence '\W'
  paths = glob.glob('D:\Work\ADB\SAR\datasets\owm/*.json')

['D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.14197_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.18778_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.2309_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.25874_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.30186_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.35307_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.41955_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.53363_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.56058_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.57764_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.72587_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.96303_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.97111_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_105.98279_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_106.10406_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.000495_106.57927_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.14466_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.15005_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.15454_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.15993_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.1806_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.18149_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.19676_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.2309_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.28929_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.30636_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.32971_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.34947_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.36924_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.40966_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.42583_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.55609_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.89385_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_105.91901_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.001393_106.57837_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.10693_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.10963_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.20844_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.21652_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.31714_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.33151_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.34499_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.34858_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.36205_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.40787_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.48332_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.50039_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.56776_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.58304_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.60011_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_105.88667_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_106.58017_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.002292_106.59814_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.124_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.13208_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.15993_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.18239_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.19407_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.21114_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.24437_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.3387_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.34139_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.34768_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.35756_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.41325_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.42583_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.42763_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.47973_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.58663_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.95135_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.96841_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_105.98189_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_106.06004_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_106.10406_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_106.22713_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00319_106.60173_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004088_105.16173_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004088_105.18239_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004088_105.32971_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004088_105.34229_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004088_105.5507_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004088_105.57764_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004088_105.61538_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004088_105.96931_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004088_106.08699_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004088_106.22893_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.10873_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.10963_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.11142_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.12669_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.13119_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.14197_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.24527_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.27312_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.42493_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.46895_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.51117_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.51746_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.52824_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.548_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.59292_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_105.97111_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_106.03848_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_106.08879_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_106.09328_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_106.13101_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.004987_106.24061_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_105.16532_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_105.19497_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_105.24527_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_105.28839_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_105.41865_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_105.46806_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_105.47794_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_105.50219_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_105.52734_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_105.88667_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_105.93697_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_105.93967_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_105.95943_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_105.97291_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_106.16065_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_106.16605_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_106.23701_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_106.48585_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_106.58646_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.005885_106.60083_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.11053_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.14107_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.24886_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.25066_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.25426_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.25695_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.26144_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.26683_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.30636_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.43122_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.45009_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.50668_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.5516_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.55788_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.56238_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.57316_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.58573_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.58663_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_105.88847_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_106.11214_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_106.15347_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_106.15886_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_106.16245_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_106.23252_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.006783_106.23611_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.007682_105.14376_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.007682_105.15005_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.007682_105.21922_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.007682_105.2318_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.007682_105.2336_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.007682_105.33331_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.007682_105.34319_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.007682_105.35487_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.007682_105.41236_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.007682_105.43302_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.007682_105.45009_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.007682_105.60011_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.007682_105.97201_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.007682_106.07262_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.007682_106.13011_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.007682_106.15617_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.007682_106.2433_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00858_105.10423_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00858_105.12939_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00858_105.13837_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00858_105.14915_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00858_105.16711_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00858_105.19856_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00858_105.20574_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00858_105.22192_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00858_105.22282_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00858_105.24617_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00858_105.27402_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00858_105.30546_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00858_105.31714_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00858_105.35037_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00858_105.35127_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00858_105.41056_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00858_105.48422_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00858_105.50129_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00858_105.52016_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00858_105.54082_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00858_105.58035_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00858_105.58663_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00858_105.59382_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00858_105.88307_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00858_105.89925_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00858_106.10586_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00858_106.12023_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00858_106.12113_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00858_106.14628_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.00858_106.15796_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.009478_105.14376_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.009478_105.1761_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.009478_105.18598_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.009478_105.19586_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.009478_105.22461_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.009478_105.25246_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.009478_105.25695_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.009478_105.2857_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.009478_105.32162_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.009478_105.32343_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.009478_105.36205_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.009478_105.38181_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.009478_105.41415_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.009478_105.41595_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.009478_105.48782_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.009478_105.54172_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.009478_105.86511_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.009478_106.11395_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.009478_106.12652_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.009478_106.13011_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.009478_106.14539_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.009478_106.23521_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.009478_106.23971_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.010376_105.11053_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.010376_105.17789_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.010376_105.18508_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.010376_105.19676_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.010376_105.20395_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.010376_105.2839_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.010376_105.32433_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.010376_105.37014_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.010376_105.42044_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.010376_105.43122_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.010376_105.4411_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.010376_105.47165_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.010376_105.60819_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.010376_105.89835_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.010376_105.94057_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.010376_106.14539_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.010376_106.14987_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.010376_106.23791_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.010376_106.24689_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.010376_106.59634_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.011274_105.10154_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.011274_105.16173_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.011274_105.16711_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.011274_105.16801_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.011274_105.20574_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.011274_105.20844_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.011274_105.21293_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.011274_105.26414_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.011274_105.2821_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.011274_105.33241_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.011274_105.38451_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.011274_105.3881_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.011274_105.3908_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.011274_105.4474_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.011274_105.48962_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.011274_105.51117_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.011274_105.58124_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.011274_105.60191_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.011274_105.93967_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.011274_105.9774_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.011274_106.04926_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.011274_106.12562_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.012173_105.17071_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.012173_105.20664_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.012173_105.35487_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.012173_105.36115_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.012173_105.36475_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.012173_105.38631_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.012173_105.3899_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.012173_105.41955_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.012173_105.44919_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.012173_105.53184_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.012173_105.54351_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.012173_105.5516_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.012173_105.60819_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.012173_105.93787_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.012173_106.03579_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.012173_106.10855_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.012173_106.11484_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.012173_106.11754_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.012173_106.15257_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.012173_106.15976_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.012173_106.60352_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.013071_105.11501_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.013071_105.25336_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.013071_105.30726_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.013071_105.41325_2022.json',
 'D:\\Work\\ADB\\SAR\\datasets\\owm\\10.013071_105.42224_2022.json',

In [43]:
dfs = []

for path in tqdm(paths):
    with open(path, 'r') as f:
        d = json.load(f)
    dates = []
    pm25s = []

    for i in range(len(d['list'])):
        dates.append(d['list'][i]['dt'])
        pm25s.append(d['list'][i]['components']['pm2_5'])


    lat_l = path.rindex('\\')
    lat_r = path.index('_')
    lon_r = path.rindex('_')

    df_p = pd.DataFrame({'lat': path[lat_l+1:lat_r],
                        'lon': path[lat_r+1:lon_r],
                        'dt': dates,
                        'pm25': pm25s})
    df_p['dt'] = pd.to_datetime(df_p['dt'], unit='s')
    df_p['dt'] = df_p['dt'].dt.tz_localize('UTC').dt.tz_convert('Asia/Saigon')
    df_p['month'] = df_p['dt'].dt.month
    df_p = df_p.groupby(['lat', 'lon', 'month']).agg({'pm25': 'mean'}).reset_index()

    df_p['lat'] = df_p['lat'].astype('float64')
    df_p['lon'] = df_p['lon'].astype('float64')

    dfs.append(df_p)

  0%|          | 0/48010 [00:00<?, ?it/s]

In [44]:
df_all = pd.concat(dfs, axis=0).reset_index(drop=True)
df_all

              lat        lon  month       pm25
0       10.000495  105.14197      1  30.825722
1       10.000495  105.14197      2  24.829599
2       10.000495  105.14197      3  25.805780
3       10.000495  105.14197      4  35.481083
4       10.000495  105.14197      5  15.307204
...           ...        ...    ...        ...
576115   9.999597  105.98009      8  30.194556
576116   9.999597  105.98009      9  21.298597
576117   9.999597  105.98009     10  56.314220
576118   9.999597  105.98009     11  42.334556
576119   9.999597  105.98009     12  62.719615

[576120 rows x 4 columns]

In [45]:
df_out = pd.merge(df, df_all, on=['lat', 'lon'], how='right')
df_out

             id        lon        lat  month       pm25
0        273937  105.14197  10.000495      1  30.825722
1        273937  105.14197  10.000495      2  24.829599
2        273937  105.14197  10.000495      3  25.805780
3        273937  105.14197  10.000495      4  35.481083
4        273937  105.14197  10.000495      5  15.307204
...         ...        ...        ...    ...        ...
576115  1301298  105.98009   9.999597      8  30.194556
576116  1301298  105.98009   9.999597      9  21.298597
576117  1301298  105.98009   9.999597     10  56.314220
576118  1301298  105.98009   9.999597     11  42.334556
576119  1301298  105.98009   9.999597     12  62.719615

[576120 rows x 5 columns]

In [46]:
df_out.to_csv('datasets/owm_pm25_2022.csv', index=False)